// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Execution is the predicate function for execution builders.
type Execution func(*sql.Selector)

// Output is the predicate function for output builders.
type Output func(*sql.Selector)

// Param is the predicate function for param builders.
type Param func(*sql.Selector)

// Step is the predicate function for step builders.
type Step func(*sql.Selector)

// StepDepend is the predicate function for stepdepend builders.
type StepDepend func(*sql.Selector)

// StepParam is the predicate function for stepparam builders.
type StepParam func(*sql.Selector)

// Task is the predicate function for task builders.
type Task func(*sql.Selector)

// TaskParam is the predicate function for taskparam builders.
type TaskParam func(*sql.Selector)
