// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Param is the predicate function for param builders.
type Param func(*sql.Selector)

// Step is the predicate function for step builders.
type Step func(*sql.Selector)

// StepDepend is the predicate function for stepdepend builders.
type StepDepend func(*sql.Selector)

// StepParam is the predicate function for stepparam builders.
type StepParam func(*sql.Selector)

// Task is the predicate function for task builders.
type Task func(*sql.Selector)

// TaskParam is the predicate function for taskparam builders.
type TaskParam func(*sql.Selector)

// TaskStep is the predicate function for taskstep builders.
type TaskStep func(*sql.Selector)

// TaskStepOutput is the predicate function for taskstepoutput builders.
type TaskStepOutput func(*sql.Selector)
