// Code generated by ent, DO NOT EDIT.

package stepdepend

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the stepdepend type in the database.
	Label = "step_depend"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldCreatedBy holds the string denoting the created_by field in the database.
	FieldCreatedBy = "created_by"
	// FieldUpdatedBy holds the string denoting the updated_by field in the database.
	FieldUpdatedBy = "updated_by"
	// FieldStepID holds the string denoting the step_id field in the database.
	FieldStepID = "step_id"
	// FieldDependentID holds the string denoting the dependent_id field in the database.
	FieldDependentID = "dependent_id"
	// EdgeStep holds the string denoting the step edge name in mutations.
	EdgeStep = "step"
	// EdgeDependStep holds the string denoting the depend_step edge name in mutations.
	EdgeDependStep = "depend_step"
	// Table holds the table name of the stepdepend in the database.
	Table = "step_depends"
	// StepTable is the table that holds the step relation/edge.
	StepTable = "step_depends"
	// StepInverseTable is the table name for the Step entity.
	// It exists in this package in order to avoid circular dependency with the "step" package.
	StepInverseTable = "steps"
	// StepColumn is the table column denoting the step relation/edge.
	StepColumn = "step_id"
	// DependStepTable is the table that holds the depend_step relation/edge.
	DependStepTable = "step_depends"
	// DependStepInverseTable is the table name for the Step entity.
	// It exists in this package in order to avoid circular dependency with the "step" package.
	DependStepInverseTable = "steps"
	// DependStepColumn is the table column denoting the depend_step relation/edge.
	DependStepColumn = "dependent_id"
)

// Columns holds all SQL columns for stepdepend fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldCreatedBy,
	FieldUpdatedBy,
	FieldStepID,
	FieldDependentID,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the StepDepend queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByCreatedBy orders the results by the created_by field.
func ByCreatedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedBy, opts...).ToFunc()
}

// ByUpdatedBy orders the results by the updated_by field.
func ByUpdatedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedBy, opts...).ToFunc()
}

// ByStepID orders the results by the step_id field.
func ByStepID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStepID, opts...).ToFunc()
}

// ByDependentID orders the results by the dependent_id field.
func ByDependentID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDependentID, opts...).ToFunc()
}

// ByStepField orders the results by step field.
func ByStepField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newStepStep(), sql.OrderByField(field, opts...))
	}
}

// ByDependStepField orders the results by depend_step field.
func ByDependStepField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newDependStepStep(), sql.OrderByField(field, opts...))
	}
}
func newStepStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(StepInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, StepTable, StepColumn),
	)
}
func newDependStepStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(DependStepInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, DependStepTable, DependStepColumn),
	)
}
