// Code generated by ent, DO NOT EDIT.

package taskstepoutput

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/busyster996/dagflow/internal/entv1/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uint64) predicate.TaskStepOutput {
	return predicate.TaskStepOutput(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uint64) predicate.TaskStepOutput {
	return predicate.TaskStepOutput(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uint64) predicate.TaskStepOutput {
	return predicate.TaskStepOutput(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uint64) predicate.TaskStepOutput {
	return predicate.TaskStepOutput(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uint64) predicate.TaskStepOutput {
	return predicate.TaskStepOutput(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uint64) predicate.TaskStepOutput {
	return predicate.TaskStepOutput(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uint64) predicate.TaskStepOutput {
	return predicate.TaskStepOutput(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uint64) predicate.TaskStepOutput {
	return predicate.TaskStepOutput(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uint64) predicate.TaskStepOutput {
	return predicate.TaskStepOutput(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.TaskStepOutput {
	return predicate.TaskStepOutput(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.TaskStepOutput {
	return predicate.TaskStepOutput(sql.FieldEQ(FieldUpdatedAt, v))
}

// CreatedBy applies equality check predicate on the "created_by" field. It's identical to CreatedByEQ.
func CreatedBy(v string) predicate.TaskStepOutput {
	return predicate.TaskStepOutput(sql.FieldEQ(FieldCreatedBy, v))
}

// UpdatedBy applies equality check predicate on the "updated_by" field. It's identical to UpdatedByEQ.
func UpdatedBy(v string) predicate.TaskStepOutput {
	return predicate.TaskStepOutput(sql.FieldEQ(FieldUpdatedBy, v))
}

// ExecID applies equality check predicate on the "exec_id" field. It's identical to ExecIDEQ.
func ExecID(v uint64) predicate.TaskStepOutput {
	return predicate.TaskStepOutput(sql.FieldEQ(FieldExecID, v))
}

// Timestamp applies equality check predicate on the "timestamp" field. It's identical to TimestampEQ.
func Timestamp(v int64) predicate.TaskStepOutput {
	return predicate.TaskStepOutput(sql.FieldEQ(FieldTimestamp, v))
}

// Content applies equality check predicate on the "content" field. It's identical to ContentEQ.
func Content(v string) predicate.TaskStepOutput {
	return predicate.TaskStepOutput(sql.FieldEQ(FieldContent, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.TaskStepOutput {
	return predicate.TaskStepOutput(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.TaskStepOutput {
	return predicate.TaskStepOutput(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.TaskStepOutput {
	return predicate.TaskStepOutput(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.TaskStepOutput {
	return predicate.TaskStepOutput(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.TaskStepOutput {
	return predicate.TaskStepOutput(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.TaskStepOutput {
	return predicate.TaskStepOutput(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.TaskStepOutput {
	return predicate.TaskStepOutput(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.TaskStepOutput {
	return predicate.TaskStepOutput(sql.FieldLTE(FieldCreatedAt, v))
}

// CreatedAtIsNil applies the IsNil predicate on the "created_at" field.
func CreatedAtIsNil() predicate.TaskStepOutput {
	return predicate.TaskStepOutput(sql.FieldIsNull(FieldCreatedAt))
}

// CreatedAtNotNil applies the NotNil predicate on the "created_at" field.
func CreatedAtNotNil() predicate.TaskStepOutput {
	return predicate.TaskStepOutput(sql.FieldNotNull(FieldCreatedAt))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.TaskStepOutput {
	return predicate.TaskStepOutput(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.TaskStepOutput {
	return predicate.TaskStepOutput(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.TaskStepOutput {
	return predicate.TaskStepOutput(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.TaskStepOutput {
	return predicate.TaskStepOutput(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.TaskStepOutput {
	return predicate.TaskStepOutput(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.TaskStepOutput {
	return predicate.TaskStepOutput(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.TaskStepOutput {
	return predicate.TaskStepOutput(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.TaskStepOutput {
	return predicate.TaskStepOutput(sql.FieldLTE(FieldUpdatedAt, v))
}

// UpdatedAtIsNil applies the IsNil predicate on the "updated_at" field.
func UpdatedAtIsNil() predicate.TaskStepOutput {
	return predicate.TaskStepOutput(sql.FieldIsNull(FieldUpdatedAt))
}

// UpdatedAtNotNil applies the NotNil predicate on the "updated_at" field.
func UpdatedAtNotNil() predicate.TaskStepOutput {
	return predicate.TaskStepOutput(sql.FieldNotNull(FieldUpdatedAt))
}

// CreatedByEQ applies the EQ predicate on the "created_by" field.
func CreatedByEQ(v string) predicate.TaskStepOutput {
	return predicate.TaskStepOutput(sql.FieldEQ(FieldCreatedBy, v))
}

// CreatedByNEQ applies the NEQ predicate on the "created_by" field.
func CreatedByNEQ(v string) predicate.TaskStepOutput {
	return predicate.TaskStepOutput(sql.FieldNEQ(FieldCreatedBy, v))
}

// CreatedByIn applies the In predicate on the "created_by" field.
func CreatedByIn(vs ...string) predicate.TaskStepOutput {
	return predicate.TaskStepOutput(sql.FieldIn(FieldCreatedBy, vs...))
}

// CreatedByNotIn applies the NotIn predicate on the "created_by" field.
func CreatedByNotIn(vs ...string) predicate.TaskStepOutput {
	return predicate.TaskStepOutput(sql.FieldNotIn(FieldCreatedBy, vs...))
}

// CreatedByGT applies the GT predicate on the "created_by" field.
func CreatedByGT(v string) predicate.TaskStepOutput {
	return predicate.TaskStepOutput(sql.FieldGT(FieldCreatedBy, v))
}

// CreatedByGTE applies the GTE predicate on the "created_by" field.
func CreatedByGTE(v string) predicate.TaskStepOutput {
	return predicate.TaskStepOutput(sql.FieldGTE(FieldCreatedBy, v))
}

// CreatedByLT applies the LT predicate on the "created_by" field.
func CreatedByLT(v string) predicate.TaskStepOutput {
	return predicate.TaskStepOutput(sql.FieldLT(FieldCreatedBy, v))
}

// CreatedByLTE applies the LTE predicate on the "created_by" field.
func CreatedByLTE(v string) predicate.TaskStepOutput {
	return predicate.TaskStepOutput(sql.FieldLTE(FieldCreatedBy, v))
}

// CreatedByContains applies the Contains predicate on the "created_by" field.
func CreatedByContains(v string) predicate.TaskStepOutput {
	return predicate.TaskStepOutput(sql.FieldContains(FieldCreatedBy, v))
}

// CreatedByHasPrefix applies the HasPrefix predicate on the "created_by" field.
func CreatedByHasPrefix(v string) predicate.TaskStepOutput {
	return predicate.TaskStepOutput(sql.FieldHasPrefix(FieldCreatedBy, v))
}

// CreatedByHasSuffix applies the HasSuffix predicate on the "created_by" field.
func CreatedByHasSuffix(v string) predicate.TaskStepOutput {
	return predicate.TaskStepOutput(sql.FieldHasSuffix(FieldCreatedBy, v))
}

// CreatedByIsNil applies the IsNil predicate on the "created_by" field.
func CreatedByIsNil() predicate.TaskStepOutput {
	return predicate.TaskStepOutput(sql.FieldIsNull(FieldCreatedBy))
}

// CreatedByNotNil applies the NotNil predicate on the "created_by" field.
func CreatedByNotNil() predicate.TaskStepOutput {
	return predicate.TaskStepOutput(sql.FieldNotNull(FieldCreatedBy))
}

// CreatedByEqualFold applies the EqualFold predicate on the "created_by" field.
func CreatedByEqualFold(v string) predicate.TaskStepOutput {
	return predicate.TaskStepOutput(sql.FieldEqualFold(FieldCreatedBy, v))
}

// CreatedByContainsFold applies the ContainsFold predicate on the "created_by" field.
func CreatedByContainsFold(v string) predicate.TaskStepOutput {
	return predicate.TaskStepOutput(sql.FieldContainsFold(FieldCreatedBy, v))
}

// UpdatedByEQ applies the EQ predicate on the "updated_by" field.
func UpdatedByEQ(v string) predicate.TaskStepOutput {
	return predicate.TaskStepOutput(sql.FieldEQ(FieldUpdatedBy, v))
}

// UpdatedByNEQ applies the NEQ predicate on the "updated_by" field.
func UpdatedByNEQ(v string) predicate.TaskStepOutput {
	return predicate.TaskStepOutput(sql.FieldNEQ(FieldUpdatedBy, v))
}

// UpdatedByIn applies the In predicate on the "updated_by" field.
func UpdatedByIn(vs ...string) predicate.TaskStepOutput {
	return predicate.TaskStepOutput(sql.FieldIn(FieldUpdatedBy, vs...))
}

// UpdatedByNotIn applies the NotIn predicate on the "updated_by" field.
func UpdatedByNotIn(vs ...string) predicate.TaskStepOutput {
	return predicate.TaskStepOutput(sql.FieldNotIn(FieldUpdatedBy, vs...))
}

// UpdatedByGT applies the GT predicate on the "updated_by" field.
func UpdatedByGT(v string) predicate.TaskStepOutput {
	return predicate.TaskStepOutput(sql.FieldGT(FieldUpdatedBy, v))
}

// UpdatedByGTE applies the GTE predicate on the "updated_by" field.
func UpdatedByGTE(v string) predicate.TaskStepOutput {
	return predicate.TaskStepOutput(sql.FieldGTE(FieldUpdatedBy, v))
}

// UpdatedByLT applies the LT predicate on the "updated_by" field.
func UpdatedByLT(v string) predicate.TaskStepOutput {
	return predicate.TaskStepOutput(sql.FieldLT(FieldUpdatedBy, v))
}

// UpdatedByLTE applies the LTE predicate on the "updated_by" field.
func UpdatedByLTE(v string) predicate.TaskStepOutput {
	return predicate.TaskStepOutput(sql.FieldLTE(FieldUpdatedBy, v))
}

// UpdatedByContains applies the Contains predicate on the "updated_by" field.
func UpdatedByContains(v string) predicate.TaskStepOutput {
	return predicate.TaskStepOutput(sql.FieldContains(FieldUpdatedBy, v))
}

// UpdatedByHasPrefix applies the HasPrefix predicate on the "updated_by" field.
func UpdatedByHasPrefix(v string) predicate.TaskStepOutput {
	return predicate.TaskStepOutput(sql.FieldHasPrefix(FieldUpdatedBy, v))
}

// UpdatedByHasSuffix applies the HasSuffix predicate on the "updated_by" field.
func UpdatedByHasSuffix(v string) predicate.TaskStepOutput {
	return predicate.TaskStepOutput(sql.FieldHasSuffix(FieldUpdatedBy, v))
}

// UpdatedByIsNil applies the IsNil predicate on the "updated_by" field.
func UpdatedByIsNil() predicate.TaskStepOutput {
	return predicate.TaskStepOutput(sql.FieldIsNull(FieldUpdatedBy))
}

// UpdatedByNotNil applies the NotNil predicate on the "updated_by" field.
func UpdatedByNotNil() predicate.TaskStepOutput {
	return predicate.TaskStepOutput(sql.FieldNotNull(FieldUpdatedBy))
}

// UpdatedByEqualFold applies the EqualFold predicate on the "updated_by" field.
func UpdatedByEqualFold(v string) predicate.TaskStepOutput {
	return predicate.TaskStepOutput(sql.FieldEqualFold(FieldUpdatedBy, v))
}

// UpdatedByContainsFold applies the ContainsFold predicate on the "updated_by" field.
func UpdatedByContainsFold(v string) predicate.TaskStepOutput {
	return predicate.TaskStepOutput(sql.FieldContainsFold(FieldUpdatedBy, v))
}

// ExecIDEQ applies the EQ predicate on the "exec_id" field.
func ExecIDEQ(v uint64) predicate.TaskStepOutput {
	return predicate.TaskStepOutput(sql.FieldEQ(FieldExecID, v))
}

// ExecIDNEQ applies the NEQ predicate on the "exec_id" field.
func ExecIDNEQ(v uint64) predicate.TaskStepOutput {
	return predicate.TaskStepOutput(sql.FieldNEQ(FieldExecID, v))
}

// ExecIDIn applies the In predicate on the "exec_id" field.
func ExecIDIn(vs ...uint64) predicate.TaskStepOutput {
	return predicate.TaskStepOutput(sql.FieldIn(FieldExecID, vs...))
}

// ExecIDNotIn applies the NotIn predicate on the "exec_id" field.
func ExecIDNotIn(vs ...uint64) predicate.TaskStepOutput {
	return predicate.TaskStepOutput(sql.FieldNotIn(FieldExecID, vs...))
}

// TimestampEQ applies the EQ predicate on the "timestamp" field.
func TimestampEQ(v int64) predicate.TaskStepOutput {
	return predicate.TaskStepOutput(sql.FieldEQ(FieldTimestamp, v))
}

// TimestampNEQ applies the NEQ predicate on the "timestamp" field.
func TimestampNEQ(v int64) predicate.TaskStepOutput {
	return predicate.TaskStepOutput(sql.FieldNEQ(FieldTimestamp, v))
}

// TimestampIn applies the In predicate on the "timestamp" field.
func TimestampIn(vs ...int64) predicate.TaskStepOutput {
	return predicate.TaskStepOutput(sql.FieldIn(FieldTimestamp, vs...))
}

// TimestampNotIn applies the NotIn predicate on the "timestamp" field.
func TimestampNotIn(vs ...int64) predicate.TaskStepOutput {
	return predicate.TaskStepOutput(sql.FieldNotIn(FieldTimestamp, vs...))
}

// TimestampGT applies the GT predicate on the "timestamp" field.
func TimestampGT(v int64) predicate.TaskStepOutput {
	return predicate.TaskStepOutput(sql.FieldGT(FieldTimestamp, v))
}

// TimestampGTE applies the GTE predicate on the "timestamp" field.
func TimestampGTE(v int64) predicate.TaskStepOutput {
	return predicate.TaskStepOutput(sql.FieldGTE(FieldTimestamp, v))
}

// TimestampLT applies the LT predicate on the "timestamp" field.
func TimestampLT(v int64) predicate.TaskStepOutput {
	return predicate.TaskStepOutput(sql.FieldLT(FieldTimestamp, v))
}

// TimestampLTE applies the LTE predicate on the "timestamp" field.
func TimestampLTE(v int64) predicate.TaskStepOutput {
	return predicate.TaskStepOutput(sql.FieldLTE(FieldTimestamp, v))
}

// TimestampIsNil applies the IsNil predicate on the "timestamp" field.
func TimestampIsNil() predicate.TaskStepOutput {
	return predicate.TaskStepOutput(sql.FieldIsNull(FieldTimestamp))
}

// TimestampNotNil applies the NotNil predicate on the "timestamp" field.
func TimestampNotNil() predicate.TaskStepOutput {
	return predicate.TaskStepOutput(sql.FieldNotNull(FieldTimestamp))
}

// ContentEQ applies the EQ predicate on the "content" field.
func ContentEQ(v string) predicate.TaskStepOutput {
	return predicate.TaskStepOutput(sql.FieldEQ(FieldContent, v))
}

// ContentNEQ applies the NEQ predicate on the "content" field.
func ContentNEQ(v string) predicate.TaskStepOutput {
	return predicate.TaskStepOutput(sql.FieldNEQ(FieldContent, v))
}

// ContentIn applies the In predicate on the "content" field.
func ContentIn(vs ...string) predicate.TaskStepOutput {
	return predicate.TaskStepOutput(sql.FieldIn(FieldContent, vs...))
}

// ContentNotIn applies the NotIn predicate on the "content" field.
func ContentNotIn(vs ...string) predicate.TaskStepOutput {
	return predicate.TaskStepOutput(sql.FieldNotIn(FieldContent, vs...))
}

// ContentGT applies the GT predicate on the "content" field.
func ContentGT(v string) predicate.TaskStepOutput {
	return predicate.TaskStepOutput(sql.FieldGT(FieldContent, v))
}

// ContentGTE applies the GTE predicate on the "content" field.
func ContentGTE(v string) predicate.TaskStepOutput {
	return predicate.TaskStepOutput(sql.FieldGTE(FieldContent, v))
}

// ContentLT applies the LT predicate on the "content" field.
func ContentLT(v string) predicate.TaskStepOutput {
	return predicate.TaskStepOutput(sql.FieldLT(FieldContent, v))
}

// ContentLTE applies the LTE predicate on the "content" field.
func ContentLTE(v string) predicate.TaskStepOutput {
	return predicate.TaskStepOutput(sql.FieldLTE(FieldContent, v))
}

// ContentContains applies the Contains predicate on the "content" field.
func ContentContains(v string) predicate.TaskStepOutput {
	return predicate.TaskStepOutput(sql.FieldContains(FieldContent, v))
}

// ContentHasPrefix applies the HasPrefix predicate on the "content" field.
func ContentHasPrefix(v string) predicate.TaskStepOutput {
	return predicate.TaskStepOutput(sql.FieldHasPrefix(FieldContent, v))
}

// ContentHasSuffix applies the HasSuffix predicate on the "content" field.
func ContentHasSuffix(v string) predicate.TaskStepOutput {
	return predicate.TaskStepOutput(sql.FieldHasSuffix(FieldContent, v))
}

// ContentIsNil applies the IsNil predicate on the "content" field.
func ContentIsNil() predicate.TaskStepOutput {
	return predicate.TaskStepOutput(sql.FieldIsNull(FieldContent))
}

// ContentNotNil applies the NotNil predicate on the "content" field.
func ContentNotNil() predicate.TaskStepOutput {
	return predicate.TaskStepOutput(sql.FieldNotNull(FieldContent))
}

// ContentEqualFold applies the EqualFold predicate on the "content" field.
func ContentEqualFold(v string) predicate.TaskStepOutput {
	return predicate.TaskStepOutput(sql.FieldEqualFold(FieldContent, v))
}

// ContentContainsFold applies the ContainsFold predicate on the "content" field.
func ContentContainsFold(v string) predicate.TaskStepOutput {
	return predicate.TaskStepOutput(sql.FieldContainsFold(FieldContent, v))
}

// HasTaskStep applies the HasEdge predicate on the "task_step" edge.
func HasTaskStep() predicate.TaskStepOutput {
	return predicate.TaskStepOutput(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, TaskStepTable, TaskStepColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTaskStepWith applies the HasEdge predicate on the "task_step" edge with a given conditions (other predicates).
func HasTaskStepWith(preds ...predicate.TaskStep) predicate.TaskStepOutput {
	return predicate.TaskStepOutput(func(s *sql.Selector) {
		step := newTaskStepStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.TaskStepOutput) predicate.TaskStepOutput {
	return predicate.TaskStepOutput(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.TaskStepOutput) predicate.TaskStepOutput {
	return predicate.TaskStepOutput(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.TaskStepOutput) predicate.TaskStepOutput {
	return predicate.TaskStepOutput(sql.NotPredicates(p))
}
