// Code generated by ent, DO NOT EDIT.

package entv1

import (
	"context"
	"errors"
	"fmt"
	"log"
	"reflect"

	"github.com/busyster996/dagflow/internal/entv1/migrate"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/busyster996/dagflow/internal/entv1/execution"
	"github.com/busyster996/dagflow/internal/entv1/output"
	"github.com/busyster996/dagflow/internal/entv1/param"
	"github.com/busyster996/dagflow/internal/entv1/step"
	"github.com/busyster996/dagflow/internal/entv1/stepdepend"
	"github.com/busyster996/dagflow/internal/entv1/stepparam"
	"github.com/busyster996/dagflow/internal/entv1/task"
	"github.com/busyster996/dagflow/internal/entv1/taskparam"

	stdsql "database/sql"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// Execution is the client for interacting with the Execution builders.
	Execution *ExecutionClient
	// Output is the client for interacting with the Output builders.
	Output *OutputClient
	// Param is the client for interacting with the Param builders.
	Param *ParamClient
	// Step is the client for interacting with the Step builders.
	Step *StepClient
	// StepDepend is the client for interacting with the StepDepend builders.
	StepDepend *StepDependClient
	// StepParam is the client for interacting with the StepParam builders.
	StepParam *StepParamClient
	// Task is the client for interacting with the Task builders.
	Task *TaskClient
	// TaskParam is the client for interacting with the TaskParam builders.
	TaskParam *TaskParamClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	client := &Client{config: newConfig(opts...)}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.Execution = NewExecutionClient(c.config)
	c.Output = NewOutputClient(c.config)
	c.Param = NewParamClient(c.config)
	c.Step = NewStepClient(c.config)
	c.StepDepend = NewStepDependClient(c.config)
	c.StepParam = NewStepParamClient(c.config)
	c.Task = NewTaskClient(c.config)
	c.TaskParam = NewTaskParamClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
	}
	// Option function to configure the client.
	Option func(*config)
)

// newConfig creates a new config for the client.
func newConfig(opts ...Option) config {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	return cfg
}

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// ErrTxStarted is returned when trying to start a new transaction from a transactional client.
var ErrTxStarted = errors.New("entv1: cannot start a transaction within a transaction")

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, ErrTxStarted
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("entv1: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:        ctx,
		config:     cfg,
		Execution:  NewExecutionClient(cfg),
		Output:     NewOutputClient(cfg),
		Param:      NewParamClient(cfg),
		Step:       NewStepClient(cfg),
		StepDepend: NewStepDependClient(cfg),
		StepParam:  NewStepParamClient(cfg),
		Task:       NewTaskClient(cfg),
		TaskParam:  NewTaskParamClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:        ctx,
		config:     cfg,
		Execution:  NewExecutionClient(cfg),
		Output:     NewOutputClient(cfg),
		Param:      NewParamClient(cfg),
		Step:       NewStepClient(cfg),
		StepDepend: NewStepDependClient(cfg),
		StepParam:  NewStepParamClient(cfg),
		Task:       NewTaskClient(cfg),
		TaskParam:  NewTaskParamClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		Execution.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	for _, n := range []interface{ Use(...Hook) }{
		c.Execution, c.Output, c.Param, c.Step, c.StepDepend, c.StepParam, c.Task,
		c.TaskParam,
	} {
		n.Use(hooks...)
	}
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	for _, n := range []interface{ Intercept(...Interceptor) }{
		c.Execution, c.Output, c.Param, c.Step, c.StepDepend, c.StepParam, c.Task,
		c.TaskParam,
	} {
		n.Intercept(interceptors...)
	}
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *ExecutionMutation:
		return c.Execution.mutate(ctx, m)
	case *OutputMutation:
		return c.Output.mutate(ctx, m)
	case *ParamMutation:
		return c.Param.mutate(ctx, m)
	case *StepMutation:
		return c.Step.mutate(ctx, m)
	case *StepDependMutation:
		return c.StepDepend.mutate(ctx, m)
	case *StepParamMutation:
		return c.StepParam.mutate(ctx, m)
	case *TaskMutation:
		return c.Task.mutate(ctx, m)
	case *TaskParamMutation:
		return c.TaskParam.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("entv1: unknown mutation type %T", m)
	}
}

// ExecutionClient is a client for the Execution schema.
type ExecutionClient struct {
	config
}

// NewExecutionClient returns a client for the Execution from the given config.
func NewExecutionClient(c config) *ExecutionClient {
	return &ExecutionClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `execution.Hooks(f(g(h())))`.
func (c *ExecutionClient) Use(hooks ...Hook) {
	c.hooks.Execution = append(c.hooks.Execution, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `execution.Intercept(f(g(h())))`.
func (c *ExecutionClient) Intercept(interceptors ...Interceptor) {
	c.inters.Execution = append(c.inters.Execution, interceptors...)
}

// Create returns a builder for creating a Execution entity.
func (c *ExecutionClient) Create() *ExecutionCreate {
	mutation := newExecutionMutation(c.config, OpCreate)
	return &ExecutionCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Execution entities.
func (c *ExecutionClient) CreateBulk(builders ...*ExecutionCreate) *ExecutionCreateBulk {
	return &ExecutionCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *ExecutionClient) MapCreateBulk(slice any, setFunc func(*ExecutionCreate, int)) *ExecutionCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &ExecutionCreateBulk{err: fmt.Errorf("calling to ExecutionClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*ExecutionCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &ExecutionCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Execution.
func (c *ExecutionClient) Update() *ExecutionUpdate {
	mutation := newExecutionMutation(c.config, OpUpdate)
	return &ExecutionUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *ExecutionClient) UpdateOne(_m *Execution) *ExecutionUpdateOne {
	mutation := newExecutionMutation(c.config, OpUpdateOne, withExecution(_m))
	return &ExecutionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *ExecutionClient) UpdateOneID(id uint64) *ExecutionUpdateOne {
	mutation := newExecutionMutation(c.config, OpUpdateOne, withExecutionID(id))
	return &ExecutionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Execution.
func (c *ExecutionClient) Delete() *ExecutionDelete {
	mutation := newExecutionMutation(c.config, OpDelete)
	return &ExecutionDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *ExecutionClient) DeleteOne(_m *Execution) *ExecutionDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *ExecutionClient) DeleteOneID(id uint64) *ExecutionDeleteOne {
	builder := c.Delete().Where(execution.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &ExecutionDeleteOne{builder}
}

// Query returns a query builder for Execution.
func (c *ExecutionClient) Query() *ExecutionQuery {
	return &ExecutionQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeExecution},
		inters: c.Interceptors(),
	}
}

// Get returns a Execution entity by its id.
func (c *ExecutionClient) Get(ctx context.Context, id uint64) (*Execution, error) {
	return c.Query().Where(execution.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *ExecutionClient) GetX(ctx context.Context, id uint64) *Execution {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryTask queries the task edge of a Execution.
func (c *ExecutionClient) QueryTask(_m *Execution) *TaskQuery {
	query := (&TaskClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(execution.Table, execution.FieldID, id),
			sqlgraph.To(task.Table, task.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, execution.TaskTable, execution.TaskColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryStep queries the step edge of a Execution.
func (c *ExecutionClient) QueryStep(_m *Execution) *StepQuery {
	query := (&StepClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(execution.Table, execution.FieldID, id),
			sqlgraph.To(step.Table, step.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, execution.StepTable, execution.StepColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryOutputs queries the outputs edge of a Execution.
func (c *ExecutionClient) QueryOutputs(_m *Execution) *OutputQuery {
	query := (&OutputClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(execution.Table, execution.FieldID, id),
			sqlgraph.To(output.Table, output.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, execution.OutputsTable, execution.OutputsColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *ExecutionClient) Hooks() []Hook {
	return c.hooks.Execution
}

// Interceptors returns the client interceptors.
func (c *ExecutionClient) Interceptors() []Interceptor {
	return c.inters.Execution
}

func (c *ExecutionClient) mutate(ctx context.Context, m *ExecutionMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&ExecutionCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&ExecutionUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&ExecutionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&ExecutionDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("entv1: unknown Execution mutation op: %q", m.Op())
	}
}

// OutputClient is a client for the Output schema.
type OutputClient struct {
	config
}

// NewOutputClient returns a client for the Output from the given config.
func NewOutputClient(c config) *OutputClient {
	return &OutputClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `output.Hooks(f(g(h())))`.
func (c *OutputClient) Use(hooks ...Hook) {
	c.hooks.Output = append(c.hooks.Output, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `output.Intercept(f(g(h())))`.
func (c *OutputClient) Intercept(interceptors ...Interceptor) {
	c.inters.Output = append(c.inters.Output, interceptors...)
}

// Create returns a builder for creating a Output entity.
func (c *OutputClient) Create() *OutputCreate {
	mutation := newOutputMutation(c.config, OpCreate)
	return &OutputCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Output entities.
func (c *OutputClient) CreateBulk(builders ...*OutputCreate) *OutputCreateBulk {
	return &OutputCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *OutputClient) MapCreateBulk(slice any, setFunc func(*OutputCreate, int)) *OutputCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &OutputCreateBulk{err: fmt.Errorf("calling to OutputClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*OutputCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &OutputCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Output.
func (c *OutputClient) Update() *OutputUpdate {
	mutation := newOutputMutation(c.config, OpUpdate)
	return &OutputUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *OutputClient) UpdateOne(_m *Output) *OutputUpdateOne {
	mutation := newOutputMutation(c.config, OpUpdateOne, withOutput(_m))
	return &OutputUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *OutputClient) UpdateOneID(id uint64) *OutputUpdateOne {
	mutation := newOutputMutation(c.config, OpUpdateOne, withOutputID(id))
	return &OutputUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Output.
func (c *OutputClient) Delete() *OutputDelete {
	mutation := newOutputMutation(c.config, OpDelete)
	return &OutputDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *OutputClient) DeleteOne(_m *Output) *OutputDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *OutputClient) DeleteOneID(id uint64) *OutputDeleteOne {
	builder := c.Delete().Where(output.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &OutputDeleteOne{builder}
}

// Query returns a query builder for Output.
func (c *OutputClient) Query() *OutputQuery {
	return &OutputQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeOutput},
		inters: c.Interceptors(),
	}
}

// Get returns a Output entity by its id.
func (c *OutputClient) Get(ctx context.Context, id uint64) (*Output, error) {
	return c.Query().Where(output.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *OutputClient) GetX(ctx context.Context, id uint64) *Output {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryExecution queries the execution edge of a Output.
func (c *OutputClient) QueryExecution(_m *Output) *ExecutionQuery {
	query := (&ExecutionClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(output.Table, output.FieldID, id),
			sqlgraph.To(execution.Table, execution.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, output.ExecutionTable, output.ExecutionColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *OutputClient) Hooks() []Hook {
	return c.hooks.Output
}

// Interceptors returns the client interceptors.
func (c *OutputClient) Interceptors() []Interceptor {
	return c.inters.Output
}

func (c *OutputClient) mutate(ctx context.Context, m *OutputMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&OutputCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&OutputUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&OutputUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&OutputDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("entv1: unknown Output mutation op: %q", m.Op())
	}
}

// ParamClient is a client for the Param schema.
type ParamClient struct {
	config
}

// NewParamClient returns a client for the Param from the given config.
func NewParamClient(c config) *ParamClient {
	return &ParamClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `param.Hooks(f(g(h())))`.
func (c *ParamClient) Use(hooks ...Hook) {
	c.hooks.Param = append(c.hooks.Param, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `param.Intercept(f(g(h())))`.
func (c *ParamClient) Intercept(interceptors ...Interceptor) {
	c.inters.Param = append(c.inters.Param, interceptors...)
}

// Create returns a builder for creating a Param entity.
func (c *ParamClient) Create() *ParamCreate {
	mutation := newParamMutation(c.config, OpCreate)
	return &ParamCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Param entities.
func (c *ParamClient) CreateBulk(builders ...*ParamCreate) *ParamCreateBulk {
	return &ParamCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *ParamClient) MapCreateBulk(slice any, setFunc func(*ParamCreate, int)) *ParamCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &ParamCreateBulk{err: fmt.Errorf("calling to ParamClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*ParamCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &ParamCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Param.
func (c *ParamClient) Update() *ParamUpdate {
	mutation := newParamMutation(c.config, OpUpdate)
	return &ParamUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *ParamClient) UpdateOne(_m *Param) *ParamUpdateOne {
	mutation := newParamMutation(c.config, OpUpdateOne, withParam(_m))
	return &ParamUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *ParamClient) UpdateOneID(id uint64) *ParamUpdateOne {
	mutation := newParamMutation(c.config, OpUpdateOne, withParamID(id))
	return &ParamUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Param.
func (c *ParamClient) Delete() *ParamDelete {
	mutation := newParamMutation(c.config, OpDelete)
	return &ParamDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *ParamClient) DeleteOne(_m *Param) *ParamDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *ParamClient) DeleteOneID(id uint64) *ParamDeleteOne {
	builder := c.Delete().Where(param.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &ParamDeleteOne{builder}
}

// Query returns a query builder for Param.
func (c *ParamClient) Query() *ParamQuery {
	return &ParamQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeParam},
		inters: c.Interceptors(),
	}
}

// Get returns a Param entity by its id.
func (c *ParamClient) Get(ctx context.Context, id uint64) (*Param, error) {
	return c.Query().Where(param.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *ParamClient) GetX(ctx context.Context, id uint64) *Param {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryTasks queries the tasks edge of a Param.
func (c *ParamClient) QueryTasks(_m *Param) *TaskQuery {
	query := (&TaskClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(param.Table, param.FieldID, id),
			sqlgraph.To(task.Table, task.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, param.TasksTable, param.TasksPrimaryKey...),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QuerySteps queries the steps edge of a Param.
func (c *ParamClient) QuerySteps(_m *Param) *StepQuery {
	query := (&StepClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(param.Table, param.FieldID, id),
			sqlgraph.To(step.Table, step.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, param.StepsTable, param.StepsPrimaryKey...),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryTaskParams queries the task_params edge of a Param.
func (c *ParamClient) QueryTaskParams(_m *Param) *TaskParamQuery {
	query := (&TaskParamClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(param.Table, param.FieldID, id),
			sqlgraph.To(taskparam.Table, taskparam.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, true, param.TaskParamsTable, param.TaskParamsColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryStepParams queries the step_params edge of a Param.
func (c *ParamClient) QueryStepParams(_m *Param) *StepParamQuery {
	query := (&StepParamClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(param.Table, param.FieldID, id),
			sqlgraph.To(stepparam.Table, stepparam.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, true, param.StepParamsTable, param.StepParamsColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *ParamClient) Hooks() []Hook {
	return c.hooks.Param
}

// Interceptors returns the client interceptors.
func (c *ParamClient) Interceptors() []Interceptor {
	return c.inters.Param
}

func (c *ParamClient) mutate(ctx context.Context, m *ParamMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&ParamCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&ParamUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&ParamUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&ParamDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("entv1: unknown Param mutation op: %q", m.Op())
	}
}

// StepClient is a client for the Step schema.
type StepClient struct {
	config
}

// NewStepClient returns a client for the Step from the given config.
func NewStepClient(c config) *StepClient {
	return &StepClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `step.Hooks(f(g(h())))`.
func (c *StepClient) Use(hooks ...Hook) {
	c.hooks.Step = append(c.hooks.Step, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `step.Intercept(f(g(h())))`.
func (c *StepClient) Intercept(interceptors ...Interceptor) {
	c.inters.Step = append(c.inters.Step, interceptors...)
}

// Create returns a builder for creating a Step entity.
func (c *StepClient) Create() *StepCreate {
	mutation := newStepMutation(c.config, OpCreate)
	return &StepCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Step entities.
func (c *StepClient) CreateBulk(builders ...*StepCreate) *StepCreateBulk {
	return &StepCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *StepClient) MapCreateBulk(slice any, setFunc func(*StepCreate, int)) *StepCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &StepCreateBulk{err: fmt.Errorf("calling to StepClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*StepCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &StepCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Step.
func (c *StepClient) Update() *StepUpdate {
	mutation := newStepMutation(c.config, OpUpdate)
	return &StepUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *StepClient) UpdateOne(_m *Step) *StepUpdateOne {
	mutation := newStepMutation(c.config, OpUpdateOne, withStep(_m))
	return &StepUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *StepClient) UpdateOneID(id uint64) *StepUpdateOne {
	mutation := newStepMutation(c.config, OpUpdateOne, withStepID(id))
	return &StepUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Step.
func (c *StepClient) Delete() *StepDelete {
	mutation := newStepMutation(c.config, OpDelete)
	return &StepDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *StepClient) DeleteOne(_m *Step) *StepDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *StepClient) DeleteOneID(id uint64) *StepDeleteOne {
	builder := c.Delete().Where(step.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &StepDeleteOne{builder}
}

// Query returns a query builder for Step.
func (c *StepClient) Query() *StepQuery {
	return &StepQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeStep},
		inters: c.Interceptors(),
	}
}

// Get returns a Step entity by its id.
func (c *StepClient) Get(ctx context.Context, id uint64) (*Step, error) {
	return c.Query().Where(step.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *StepClient) GetX(ctx context.Context, id uint64) *Step {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryTasks queries the tasks edge of a Step.
func (c *StepClient) QueryTasks(_m *Step) *TaskQuery {
	query := (&TaskClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(step.Table, step.FieldID, id),
			sqlgraph.To(task.Table, task.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, step.TasksTable, step.TasksPrimaryKey...),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryParams queries the params edge of a Step.
func (c *StepClient) QueryParams(_m *Step) *ParamQuery {
	query := (&ParamClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(step.Table, step.FieldID, id),
			sqlgraph.To(param.Table, param.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, step.ParamsTable, step.ParamsPrimaryKey...),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryDependencies queries the dependencies edge of a Step.
func (c *StepClient) QueryDependencies(_m *Step) *StepQuery {
	query := (&StepClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(step.Table, step.FieldID, id),
			sqlgraph.To(step.Table, step.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, step.DependenciesTable, step.DependenciesPrimaryKey...),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryDependents queries the dependents edge of a Step.
func (c *StepClient) QueryDependents(_m *Step) *StepQuery {
	query := (&StepClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(step.Table, step.FieldID, id),
			sqlgraph.To(step.Table, step.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, step.DependentsTable, step.DependentsPrimaryKey...),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryExecutions queries the executions edge of a Step.
func (c *StepClient) QueryExecutions(_m *Step) *ExecutionQuery {
	query := (&ExecutionClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(step.Table, step.FieldID, id),
			sqlgraph.To(execution.Table, execution.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, true, step.ExecutionsTable, step.ExecutionsColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryStepParams queries the step_params edge of a Step.
func (c *StepClient) QueryStepParams(_m *Step) *StepParamQuery {
	query := (&StepParamClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(step.Table, step.FieldID, id),
			sqlgraph.To(stepparam.Table, stepparam.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, true, step.StepParamsTable, step.StepParamsColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryStepDepends queries the step_depends edge of a Step.
func (c *StepClient) QueryStepDepends(_m *Step) *StepDependQuery {
	query := (&StepDependClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(step.Table, step.FieldID, id),
			sqlgraph.To(stepdepend.Table, stepdepend.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, true, step.StepDependsTable, step.StepDependsColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryStepDependents queries the step_dependents edge of a Step.
func (c *StepClient) QueryStepDependents(_m *Step) *StepDependQuery {
	query := (&StepDependClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(step.Table, step.FieldID, id),
			sqlgraph.To(stepdepend.Table, stepdepend.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, true, step.StepDependentsTable, step.StepDependentsColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *StepClient) Hooks() []Hook {
	return c.hooks.Step
}

// Interceptors returns the client interceptors.
func (c *StepClient) Interceptors() []Interceptor {
	return c.inters.Step
}

func (c *StepClient) mutate(ctx context.Context, m *StepMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&StepCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&StepUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&StepUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&StepDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("entv1: unknown Step mutation op: %q", m.Op())
	}
}

// StepDependClient is a client for the StepDepend schema.
type StepDependClient struct {
	config
}

// NewStepDependClient returns a client for the StepDepend from the given config.
func NewStepDependClient(c config) *StepDependClient {
	return &StepDependClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `stepdepend.Hooks(f(g(h())))`.
func (c *StepDependClient) Use(hooks ...Hook) {
	c.hooks.StepDepend = append(c.hooks.StepDepend, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `stepdepend.Intercept(f(g(h())))`.
func (c *StepDependClient) Intercept(interceptors ...Interceptor) {
	c.inters.StepDepend = append(c.inters.StepDepend, interceptors...)
}

// Create returns a builder for creating a StepDepend entity.
func (c *StepDependClient) Create() *StepDependCreate {
	mutation := newStepDependMutation(c.config, OpCreate)
	return &StepDependCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of StepDepend entities.
func (c *StepDependClient) CreateBulk(builders ...*StepDependCreate) *StepDependCreateBulk {
	return &StepDependCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *StepDependClient) MapCreateBulk(slice any, setFunc func(*StepDependCreate, int)) *StepDependCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &StepDependCreateBulk{err: fmt.Errorf("calling to StepDependClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*StepDependCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &StepDependCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for StepDepend.
func (c *StepDependClient) Update() *StepDependUpdate {
	mutation := newStepDependMutation(c.config, OpUpdate)
	return &StepDependUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *StepDependClient) UpdateOne(_m *StepDepend) *StepDependUpdateOne {
	mutation := newStepDependMutation(c.config, OpUpdateOne, withStepDepend(_m))
	return &StepDependUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *StepDependClient) UpdateOneID(id uint64) *StepDependUpdateOne {
	mutation := newStepDependMutation(c.config, OpUpdateOne, withStepDependID(id))
	return &StepDependUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for StepDepend.
func (c *StepDependClient) Delete() *StepDependDelete {
	mutation := newStepDependMutation(c.config, OpDelete)
	return &StepDependDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *StepDependClient) DeleteOne(_m *StepDepend) *StepDependDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *StepDependClient) DeleteOneID(id uint64) *StepDependDeleteOne {
	builder := c.Delete().Where(stepdepend.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &StepDependDeleteOne{builder}
}

// Query returns a query builder for StepDepend.
func (c *StepDependClient) Query() *StepDependQuery {
	return &StepDependQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeStepDepend},
		inters: c.Interceptors(),
	}
}

// Get returns a StepDepend entity by its id.
func (c *StepDependClient) Get(ctx context.Context, id uint64) (*StepDepend, error) {
	return c.Query().Where(stepdepend.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *StepDependClient) GetX(ctx context.Context, id uint64) *StepDepend {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryStep queries the step edge of a StepDepend.
func (c *StepDependClient) QueryStep(_m *StepDepend) *StepQuery {
	query := (&StepClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(stepdepend.Table, stepdepend.FieldID, id),
			sqlgraph.To(step.Table, step.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, stepdepend.StepTable, stepdepend.StepColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryDependStep queries the depend_step edge of a StepDepend.
func (c *StepDependClient) QueryDependStep(_m *StepDepend) *StepQuery {
	query := (&StepClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(stepdepend.Table, stepdepend.FieldID, id),
			sqlgraph.To(step.Table, step.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, stepdepend.DependStepTable, stepdepend.DependStepColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *StepDependClient) Hooks() []Hook {
	return c.hooks.StepDepend
}

// Interceptors returns the client interceptors.
func (c *StepDependClient) Interceptors() []Interceptor {
	return c.inters.StepDepend
}

func (c *StepDependClient) mutate(ctx context.Context, m *StepDependMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&StepDependCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&StepDependUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&StepDependUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&StepDependDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("entv1: unknown StepDepend mutation op: %q", m.Op())
	}
}

// StepParamClient is a client for the StepParam schema.
type StepParamClient struct {
	config
}

// NewStepParamClient returns a client for the StepParam from the given config.
func NewStepParamClient(c config) *StepParamClient {
	return &StepParamClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `stepparam.Hooks(f(g(h())))`.
func (c *StepParamClient) Use(hooks ...Hook) {
	c.hooks.StepParam = append(c.hooks.StepParam, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `stepparam.Intercept(f(g(h())))`.
func (c *StepParamClient) Intercept(interceptors ...Interceptor) {
	c.inters.StepParam = append(c.inters.StepParam, interceptors...)
}

// Create returns a builder for creating a StepParam entity.
func (c *StepParamClient) Create() *StepParamCreate {
	mutation := newStepParamMutation(c.config, OpCreate)
	return &StepParamCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of StepParam entities.
func (c *StepParamClient) CreateBulk(builders ...*StepParamCreate) *StepParamCreateBulk {
	return &StepParamCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *StepParamClient) MapCreateBulk(slice any, setFunc func(*StepParamCreate, int)) *StepParamCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &StepParamCreateBulk{err: fmt.Errorf("calling to StepParamClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*StepParamCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &StepParamCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for StepParam.
func (c *StepParamClient) Update() *StepParamUpdate {
	mutation := newStepParamMutation(c.config, OpUpdate)
	return &StepParamUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *StepParamClient) UpdateOne(_m *StepParam) *StepParamUpdateOne {
	mutation := newStepParamMutation(c.config, OpUpdateOne, withStepParam(_m))
	return &StepParamUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *StepParamClient) UpdateOneID(id uint64) *StepParamUpdateOne {
	mutation := newStepParamMutation(c.config, OpUpdateOne, withStepParamID(id))
	return &StepParamUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for StepParam.
func (c *StepParamClient) Delete() *StepParamDelete {
	mutation := newStepParamMutation(c.config, OpDelete)
	return &StepParamDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *StepParamClient) DeleteOne(_m *StepParam) *StepParamDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *StepParamClient) DeleteOneID(id uint64) *StepParamDeleteOne {
	builder := c.Delete().Where(stepparam.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &StepParamDeleteOne{builder}
}

// Query returns a query builder for StepParam.
func (c *StepParamClient) Query() *StepParamQuery {
	return &StepParamQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeStepParam},
		inters: c.Interceptors(),
	}
}

// Get returns a StepParam entity by its id.
func (c *StepParamClient) Get(ctx context.Context, id uint64) (*StepParam, error) {
	return c.Query().Where(stepparam.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *StepParamClient) GetX(ctx context.Context, id uint64) *StepParam {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryStep queries the step edge of a StepParam.
func (c *StepParamClient) QueryStep(_m *StepParam) *StepQuery {
	query := (&StepClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(stepparam.Table, stepparam.FieldID, id),
			sqlgraph.To(step.Table, step.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, stepparam.StepTable, stepparam.StepColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryParam queries the param edge of a StepParam.
func (c *StepParamClient) QueryParam(_m *StepParam) *ParamQuery {
	query := (&ParamClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(stepparam.Table, stepparam.FieldID, id),
			sqlgraph.To(param.Table, param.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, stepparam.ParamTable, stepparam.ParamColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *StepParamClient) Hooks() []Hook {
	return c.hooks.StepParam
}

// Interceptors returns the client interceptors.
func (c *StepParamClient) Interceptors() []Interceptor {
	return c.inters.StepParam
}

func (c *StepParamClient) mutate(ctx context.Context, m *StepParamMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&StepParamCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&StepParamUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&StepParamUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&StepParamDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("entv1: unknown StepParam mutation op: %q", m.Op())
	}
}

// TaskClient is a client for the Task schema.
type TaskClient struct {
	config
}

// NewTaskClient returns a client for the Task from the given config.
func NewTaskClient(c config) *TaskClient {
	return &TaskClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `task.Hooks(f(g(h())))`.
func (c *TaskClient) Use(hooks ...Hook) {
	c.hooks.Task = append(c.hooks.Task, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `task.Intercept(f(g(h())))`.
func (c *TaskClient) Intercept(interceptors ...Interceptor) {
	c.inters.Task = append(c.inters.Task, interceptors...)
}

// Create returns a builder for creating a Task entity.
func (c *TaskClient) Create() *TaskCreate {
	mutation := newTaskMutation(c.config, OpCreate)
	return &TaskCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Task entities.
func (c *TaskClient) CreateBulk(builders ...*TaskCreate) *TaskCreateBulk {
	return &TaskCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *TaskClient) MapCreateBulk(slice any, setFunc func(*TaskCreate, int)) *TaskCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &TaskCreateBulk{err: fmt.Errorf("calling to TaskClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*TaskCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &TaskCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Task.
func (c *TaskClient) Update() *TaskUpdate {
	mutation := newTaskMutation(c.config, OpUpdate)
	return &TaskUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *TaskClient) UpdateOne(_m *Task) *TaskUpdateOne {
	mutation := newTaskMutation(c.config, OpUpdateOne, withTask(_m))
	return &TaskUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *TaskClient) UpdateOneID(id uint64) *TaskUpdateOne {
	mutation := newTaskMutation(c.config, OpUpdateOne, withTaskID(id))
	return &TaskUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Task.
func (c *TaskClient) Delete() *TaskDelete {
	mutation := newTaskMutation(c.config, OpDelete)
	return &TaskDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *TaskClient) DeleteOne(_m *Task) *TaskDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *TaskClient) DeleteOneID(id uint64) *TaskDeleteOne {
	builder := c.Delete().Where(task.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &TaskDeleteOne{builder}
}

// Query returns a query builder for Task.
func (c *TaskClient) Query() *TaskQuery {
	return &TaskQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeTask},
		inters: c.Interceptors(),
	}
}

// Get returns a Task entity by its id.
func (c *TaskClient) Get(ctx context.Context, id uint64) (*Task, error) {
	return c.Query().Where(task.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *TaskClient) GetX(ctx context.Context, id uint64) *Task {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QuerySteps queries the steps edge of a Task.
func (c *TaskClient) QuerySteps(_m *Task) *StepQuery {
	query := (&StepClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(task.Table, task.FieldID, id),
			sqlgraph.To(step.Table, step.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, task.StepsTable, task.StepsPrimaryKey...),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryParams queries the params edge of a Task.
func (c *TaskClient) QueryParams(_m *Task) *ParamQuery {
	query := (&ParamClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(task.Table, task.FieldID, id),
			sqlgraph.To(param.Table, param.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, task.ParamsTable, task.ParamsPrimaryKey...),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryExecutions queries the executions edge of a Task.
func (c *TaskClient) QueryExecutions(_m *Task) *ExecutionQuery {
	query := (&ExecutionClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(task.Table, task.FieldID, id),
			sqlgraph.To(execution.Table, execution.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, true, task.ExecutionsTable, task.ExecutionsColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryTaskParams queries the task_params edge of a Task.
func (c *TaskClient) QueryTaskParams(_m *Task) *TaskParamQuery {
	query := (&TaskParamClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(task.Table, task.FieldID, id),
			sqlgraph.To(taskparam.Table, taskparam.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, true, task.TaskParamsTable, task.TaskParamsColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *TaskClient) Hooks() []Hook {
	return c.hooks.Task
}

// Interceptors returns the client interceptors.
func (c *TaskClient) Interceptors() []Interceptor {
	return c.inters.Task
}

func (c *TaskClient) mutate(ctx context.Context, m *TaskMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&TaskCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&TaskUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&TaskUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&TaskDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("entv1: unknown Task mutation op: %q", m.Op())
	}
}

// TaskParamClient is a client for the TaskParam schema.
type TaskParamClient struct {
	config
}

// NewTaskParamClient returns a client for the TaskParam from the given config.
func NewTaskParamClient(c config) *TaskParamClient {
	return &TaskParamClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `taskparam.Hooks(f(g(h())))`.
func (c *TaskParamClient) Use(hooks ...Hook) {
	c.hooks.TaskParam = append(c.hooks.TaskParam, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `taskparam.Intercept(f(g(h())))`.
func (c *TaskParamClient) Intercept(interceptors ...Interceptor) {
	c.inters.TaskParam = append(c.inters.TaskParam, interceptors...)
}

// Create returns a builder for creating a TaskParam entity.
func (c *TaskParamClient) Create() *TaskParamCreate {
	mutation := newTaskParamMutation(c.config, OpCreate)
	return &TaskParamCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of TaskParam entities.
func (c *TaskParamClient) CreateBulk(builders ...*TaskParamCreate) *TaskParamCreateBulk {
	return &TaskParamCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *TaskParamClient) MapCreateBulk(slice any, setFunc func(*TaskParamCreate, int)) *TaskParamCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &TaskParamCreateBulk{err: fmt.Errorf("calling to TaskParamClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*TaskParamCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &TaskParamCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for TaskParam.
func (c *TaskParamClient) Update() *TaskParamUpdate {
	mutation := newTaskParamMutation(c.config, OpUpdate)
	return &TaskParamUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *TaskParamClient) UpdateOne(_m *TaskParam) *TaskParamUpdateOne {
	mutation := newTaskParamMutation(c.config, OpUpdateOne, withTaskParam(_m))
	return &TaskParamUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *TaskParamClient) UpdateOneID(id uint64) *TaskParamUpdateOne {
	mutation := newTaskParamMutation(c.config, OpUpdateOne, withTaskParamID(id))
	return &TaskParamUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for TaskParam.
func (c *TaskParamClient) Delete() *TaskParamDelete {
	mutation := newTaskParamMutation(c.config, OpDelete)
	return &TaskParamDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *TaskParamClient) DeleteOne(_m *TaskParam) *TaskParamDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *TaskParamClient) DeleteOneID(id uint64) *TaskParamDeleteOne {
	builder := c.Delete().Where(taskparam.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &TaskParamDeleteOne{builder}
}

// Query returns a query builder for TaskParam.
func (c *TaskParamClient) Query() *TaskParamQuery {
	return &TaskParamQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeTaskParam},
		inters: c.Interceptors(),
	}
}

// Get returns a TaskParam entity by its id.
func (c *TaskParamClient) Get(ctx context.Context, id uint64) (*TaskParam, error) {
	return c.Query().Where(taskparam.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *TaskParamClient) GetX(ctx context.Context, id uint64) *TaskParam {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryTask queries the task edge of a TaskParam.
func (c *TaskParamClient) QueryTask(_m *TaskParam) *TaskQuery {
	query := (&TaskClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(taskparam.Table, taskparam.FieldID, id),
			sqlgraph.To(task.Table, task.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, taskparam.TaskTable, taskparam.TaskColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryParam queries the param edge of a TaskParam.
func (c *TaskParamClient) QueryParam(_m *TaskParam) *ParamQuery {
	query := (&ParamClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(taskparam.Table, taskparam.FieldID, id),
			sqlgraph.To(param.Table, param.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, taskparam.ParamTable, taskparam.ParamColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *TaskParamClient) Hooks() []Hook {
	return c.hooks.TaskParam
}

// Interceptors returns the client interceptors.
func (c *TaskParamClient) Interceptors() []Interceptor {
	return c.inters.TaskParam
}

func (c *TaskParamClient) mutate(ctx context.Context, m *TaskParamMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&TaskParamCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&TaskParamUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&TaskParamUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&TaskParamDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("entv1: unknown TaskParam mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		Execution, Output, Param, Step, StepDepend, StepParam, Task,
		TaskParam []ent.Hook
	}
	inters struct {
		Execution, Output, Param, Step, StepDepend, StepParam, Task,
		TaskParam []ent.Interceptor
	}
)

// ExecContext allows calling the underlying ExecContext method of the driver if it is supported by it.
// See, database/sql#DB.ExecContext for more information.
func (c *config) ExecContext(ctx context.Context, query string, args ...any) (stdsql.Result, error) {
	ex, ok := c.driver.(interface {
		ExecContext(context.Context, string, ...any) (stdsql.Result, error)
	})
	if !ok {
		return nil, fmt.Errorf("Driver.ExecContext is not supported")
	}
	return ex.ExecContext(ctx, query, args...)
}

// QueryContext allows calling the underlying QueryContext method of the driver if it is supported by it.
// See, database/sql#DB.QueryContext for more information.
func (c *config) QueryContext(ctx context.Context, query string, args ...any) (*stdsql.Rows, error) {
	q, ok := c.driver.(interface {
		QueryContext(context.Context, string, ...any) (*stdsql.Rows, error)
	})
	if !ok {
		return nil, fmt.Errorf("Driver.QueryContext is not supported")
	}
	return q.QueryContext(ctx, query, args...)
}
