// Code generated by ent, DO NOT EDIT.

package entv1

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/busyster996/dagflow/internal/entv1/execution"
	"github.com/busyster996/dagflow/internal/entv1/output"
	"github.com/busyster996/dagflow/internal/entv1/step"
	"github.com/busyster996/dagflow/internal/entv1/task"
)

// ExecutionCreate is the builder for creating a Execution entity.
type ExecutionCreate struct {
	config
	mutation *ExecutionMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *ExecutionCreate) SetCreatedAt(v time.Time) *ExecutionCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ExecutionCreate) SetNillableCreatedAt(v *time.Time) *ExecutionCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ExecutionCreate) SetUpdatedAt(v time.Time) *ExecutionCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ExecutionCreate) SetNillableUpdatedAt(v *time.Time) *ExecutionCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetCreatedBy sets the "created_by" field.
func (_c *ExecutionCreate) SetCreatedBy(v string) *ExecutionCreate {
	_c.mutation.SetCreatedBy(v)
	return _c
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_c *ExecutionCreate) SetNillableCreatedBy(v *string) *ExecutionCreate {
	if v != nil {
		_c.SetCreatedBy(*v)
	}
	return _c
}

// SetUpdatedBy sets the "updated_by" field.
func (_c *ExecutionCreate) SetUpdatedBy(v string) *ExecutionCreate {
	_c.mutation.SetUpdatedBy(v)
	return _c
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_c *ExecutionCreate) SetNillableUpdatedBy(v *string) *ExecutionCreate {
	if v != nil {
		_c.SetUpdatedBy(*v)
	}
	return _c
}

// SetDisabled sets the "disabled" field.
func (_c *ExecutionCreate) SetDisabled(v bool) *ExecutionCreate {
	_c.mutation.SetDisabled(v)
	return _c
}

// SetNillableDisabled sets the "disabled" field if the given value is not nil.
func (_c *ExecutionCreate) SetNillableDisabled(v *bool) *ExecutionCreate {
	if v != nil {
		_c.SetDisabled(*v)
	}
	return _c
}

// SetMessage sets the "message" field.
func (_c *ExecutionCreate) SetMessage(v string) *ExecutionCreate {
	_c.mutation.SetMessage(v)
	return _c
}

// SetNillableMessage sets the "message" field if the given value is not nil.
func (_c *ExecutionCreate) SetNillableMessage(v *string) *ExecutionCreate {
	if v != nil {
		_c.SetMessage(*v)
	}
	return _c
}

// SetState sets the "state" field.
func (_c *ExecutionCreate) SetState(v execution.State) *ExecutionCreate {
	_c.mutation.SetState(v)
	return _c
}

// SetNillableState sets the "state" field if the given value is not nil.
func (_c *ExecutionCreate) SetNillableState(v *execution.State) *ExecutionCreate {
	if v != nil {
		_c.SetState(*v)
	}
	return _c
}

// SetPreviousState sets the "previous_state" field.
func (_c *ExecutionCreate) SetPreviousState(v execution.PreviousState) *ExecutionCreate {
	_c.mutation.SetPreviousState(v)
	return _c
}

// SetNillablePreviousState sets the "previous_state" field if the given value is not nil.
func (_c *ExecutionCreate) SetNillablePreviousState(v *execution.PreviousState) *ExecutionCreate {
	if v != nil {
		_c.SetPreviousState(*v)
	}
	return _c
}

// SetStartTime sets the "start_time" field.
func (_c *ExecutionCreate) SetStartTime(v time.Time) *ExecutionCreate {
	_c.mutation.SetStartTime(v)
	return _c
}

// SetNillableStartTime sets the "start_time" field if the given value is not nil.
func (_c *ExecutionCreate) SetNillableStartTime(v *time.Time) *ExecutionCreate {
	if v != nil {
		_c.SetStartTime(*v)
	}
	return _c
}

// SetEndTime sets the "end_time" field.
func (_c *ExecutionCreate) SetEndTime(v time.Time) *ExecutionCreate {
	_c.mutation.SetEndTime(v)
	return _c
}

// SetNillableEndTime sets the "end_time" field if the given value is not nil.
func (_c *ExecutionCreate) SetNillableEndTime(v *time.Time) *ExecutionCreate {
	if v != nil {
		_c.SetEndTime(*v)
	}
	return _c
}

// SetTaskID sets the "task_id" field.
func (_c *ExecutionCreate) SetTaskID(v uint64) *ExecutionCreate {
	_c.mutation.SetTaskID(v)
	return _c
}

// SetStepID sets the "step_id" field.
func (_c *ExecutionCreate) SetStepID(v uint64) *ExecutionCreate {
	_c.mutation.SetStepID(v)
	return _c
}

// SetSeqNo sets the "seq_no" field.
func (_c *ExecutionCreate) SetSeqNo(v int64) *ExecutionCreate {
	_c.mutation.SetSeqNo(v)
	return _c
}

// SetNillableSeqNo sets the "seq_no" field if the given value is not nil.
func (_c *ExecutionCreate) SetNillableSeqNo(v *int64) *ExecutionCreate {
	if v != nil {
		_c.SetSeqNo(*v)
	}
	return _c
}

// SetCode sets the "code" field.
func (_c *ExecutionCreate) SetCode(v int64) *ExecutionCreate {
	_c.mutation.SetCode(v)
	return _c
}

// SetNillableCode sets the "code" field if the given value is not nil.
func (_c *ExecutionCreate) SetNillableCode(v *int64) *ExecutionCreate {
	if v != nil {
		_c.SetCode(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *ExecutionCreate) SetID(v uint64) *ExecutionCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetTask sets the "task" edge to the Task entity.
func (_c *ExecutionCreate) SetTask(v *Task) *ExecutionCreate {
	return _c.SetTaskID(v.ID)
}

// SetStep sets the "step" edge to the Step entity.
func (_c *ExecutionCreate) SetStep(v *Step) *ExecutionCreate {
	return _c.SetStepID(v.ID)
}

// AddOutputIDs adds the "outputs" edge to the Output entity by IDs.
func (_c *ExecutionCreate) AddOutputIDs(ids ...uint64) *ExecutionCreate {
	_c.mutation.AddOutputIDs(ids...)
	return _c
}

// AddOutputs adds the "outputs" edges to the Output entity.
func (_c *ExecutionCreate) AddOutputs(v ...*Output) *ExecutionCreate {
	ids := make([]uint64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddOutputIDs(ids...)
}

// Mutation returns the ExecutionMutation object of the builder.
func (_c *ExecutionCreate) Mutation() *ExecutionMutation {
	return _c.mutation
}

// Save creates the Execution in the database.
func (_c *ExecutionCreate) Save(ctx context.Context) (*Execution, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ExecutionCreate) SaveX(ctx context.Context) *Execution {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ExecutionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ExecutionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ExecutionCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := execution.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := execution.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Disabled(); !ok {
		v := execution.DefaultDisabled
		_c.mutation.SetDisabled(v)
	}
	if _, ok := _c.mutation.State(); !ok {
		v := execution.DefaultState
		_c.mutation.SetState(v)
	}
	if _, ok := _c.mutation.PreviousState(); !ok {
		v := execution.DefaultPreviousState
		_c.mutation.SetPreviousState(v)
	}
	if _, ok := _c.mutation.SeqNo(); !ok {
		v := execution.DefaultSeqNo
		_c.mutation.SetSeqNo(v)
	}
	if _, ok := _c.mutation.Code(); !ok {
		v := execution.DefaultCode
		_c.mutation.SetCode(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ExecutionCreate) check() error {
	if v, ok := _c.mutation.State(); ok {
		if err := execution.StateValidator(v); err != nil {
			return &ValidationError{Name: "state", err: fmt.Errorf(`entv1: validator failed for field "Execution.state": %w`, err)}
		}
	}
	if v, ok := _c.mutation.PreviousState(); ok {
		if err := execution.PreviousStateValidator(v); err != nil {
			return &ValidationError{Name: "previous_state", err: fmt.Errorf(`entv1: validator failed for field "Execution.previous_state": %w`, err)}
		}
	}
	if _, ok := _c.mutation.TaskID(); !ok {
		return &ValidationError{Name: "task_id", err: errors.New(`entv1: missing required field "Execution.task_id"`)}
	}
	if _, ok := _c.mutation.StepID(); !ok {
		return &ValidationError{Name: "step_id", err: errors.New(`entv1: missing required field "Execution.step_id"`)}
	}
	if len(_c.mutation.TaskIDs()) == 0 {
		return &ValidationError{Name: "task", err: errors.New(`entv1: missing required edge "Execution.task"`)}
	}
	if len(_c.mutation.StepIDs()) == 0 {
		return &ValidationError{Name: "step", err: errors.New(`entv1: missing required edge "Execution.step"`)}
	}
	return nil
}

func (_c *ExecutionCreate) sqlSave(ctx context.Context) (*Execution, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = uint64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ExecutionCreate) createSpec() (*Execution, *sqlgraph.CreateSpec) {
	var (
		_node = &Execution{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(execution.Table, sqlgraph.NewFieldSpec(execution.FieldID, field.TypeUint64))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(execution.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = &value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(execution.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = &value
	}
	if value, ok := _c.mutation.CreatedBy(); ok {
		_spec.SetField(execution.FieldCreatedBy, field.TypeString, value)
		_node.CreatedBy = &value
	}
	if value, ok := _c.mutation.UpdatedBy(); ok {
		_spec.SetField(execution.FieldUpdatedBy, field.TypeString, value)
		_node.UpdatedBy = &value
	}
	if value, ok := _c.mutation.Disabled(); ok {
		_spec.SetField(execution.FieldDisabled, field.TypeBool, value)
		_node.Disabled = &value
	}
	if value, ok := _c.mutation.Message(); ok {
		_spec.SetField(execution.FieldMessage, field.TypeString, value)
		_node.Message = &value
	}
	if value, ok := _c.mutation.State(); ok {
		_spec.SetField(execution.FieldState, field.TypeEnum, value)
		_node.State = &value
	}
	if value, ok := _c.mutation.PreviousState(); ok {
		_spec.SetField(execution.FieldPreviousState, field.TypeEnum, value)
		_node.PreviousState = &value
	}
	if value, ok := _c.mutation.StartTime(); ok {
		_spec.SetField(execution.FieldStartTime, field.TypeTime, value)
		_node.StartTime = &value
	}
	if value, ok := _c.mutation.EndTime(); ok {
		_spec.SetField(execution.FieldEndTime, field.TypeTime, value)
		_node.EndTime = &value
	}
	if value, ok := _c.mutation.SeqNo(); ok {
		_spec.SetField(execution.FieldSeqNo, field.TypeInt64, value)
		_node.SeqNo = &value
	}
	if value, ok := _c.mutation.Code(); ok {
		_spec.SetField(execution.FieldCode, field.TypeInt64, value)
		_node.Code = &value
	}
	if nodes := _c.mutation.TaskIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   execution.TaskTable,
			Columns: []string{execution.TaskColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeUint64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.TaskID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.StepIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   execution.StepTable,
			Columns: []string{execution.StepColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(step.FieldID, field.TypeUint64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.StepID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.OutputsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   execution.OutputsTable,
			Columns: []string{execution.OutputsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(output.FieldID, field.TypeUint64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Execution.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ExecutionUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *ExecutionCreate) OnConflict(opts ...sql.ConflictOption) *ExecutionUpsertOne {
	_c.conflict = opts
	return &ExecutionUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Execution.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ExecutionCreate) OnConflictColumns(columns ...string) *ExecutionUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ExecutionUpsertOne{
		create: _c,
	}
}

type (
	// ExecutionUpsertOne is the builder for "upsert"-ing
	//  one Execution node.
	ExecutionUpsertOne struct {
		create *ExecutionCreate
	}

	// ExecutionUpsert is the "OnConflict" setter.
	ExecutionUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *ExecutionUpsert) SetUpdatedAt(v time.Time) *ExecutionUpsert {
	u.Set(execution.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ExecutionUpsert) UpdateUpdatedAt() *ExecutionUpsert {
	u.SetExcluded(execution.FieldUpdatedAt)
	return u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (u *ExecutionUpsert) ClearUpdatedAt() *ExecutionUpsert {
	u.SetNull(execution.FieldUpdatedAt)
	return u
}

// SetCreatedBy sets the "created_by" field.
func (u *ExecutionUpsert) SetCreatedBy(v string) *ExecutionUpsert {
	u.Set(execution.FieldCreatedBy, v)
	return u
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *ExecutionUpsert) UpdateCreatedBy() *ExecutionUpsert {
	u.SetExcluded(execution.FieldCreatedBy)
	return u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (u *ExecutionUpsert) ClearCreatedBy() *ExecutionUpsert {
	u.SetNull(execution.FieldCreatedBy)
	return u
}

// SetUpdatedBy sets the "updated_by" field.
func (u *ExecutionUpsert) SetUpdatedBy(v string) *ExecutionUpsert {
	u.Set(execution.FieldUpdatedBy, v)
	return u
}

// UpdateUpdatedBy sets the "updated_by" field to the value that was provided on create.
func (u *ExecutionUpsert) UpdateUpdatedBy() *ExecutionUpsert {
	u.SetExcluded(execution.FieldUpdatedBy)
	return u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (u *ExecutionUpsert) ClearUpdatedBy() *ExecutionUpsert {
	u.SetNull(execution.FieldUpdatedBy)
	return u
}

// SetDisabled sets the "disabled" field.
func (u *ExecutionUpsert) SetDisabled(v bool) *ExecutionUpsert {
	u.Set(execution.FieldDisabled, v)
	return u
}

// UpdateDisabled sets the "disabled" field to the value that was provided on create.
func (u *ExecutionUpsert) UpdateDisabled() *ExecutionUpsert {
	u.SetExcluded(execution.FieldDisabled)
	return u
}

// ClearDisabled clears the value of the "disabled" field.
func (u *ExecutionUpsert) ClearDisabled() *ExecutionUpsert {
	u.SetNull(execution.FieldDisabled)
	return u
}

// SetMessage sets the "message" field.
func (u *ExecutionUpsert) SetMessage(v string) *ExecutionUpsert {
	u.Set(execution.FieldMessage, v)
	return u
}

// UpdateMessage sets the "message" field to the value that was provided on create.
func (u *ExecutionUpsert) UpdateMessage() *ExecutionUpsert {
	u.SetExcluded(execution.FieldMessage)
	return u
}

// ClearMessage clears the value of the "message" field.
func (u *ExecutionUpsert) ClearMessage() *ExecutionUpsert {
	u.SetNull(execution.FieldMessage)
	return u
}

// SetState sets the "state" field.
func (u *ExecutionUpsert) SetState(v execution.State) *ExecutionUpsert {
	u.Set(execution.FieldState, v)
	return u
}

// UpdateState sets the "state" field to the value that was provided on create.
func (u *ExecutionUpsert) UpdateState() *ExecutionUpsert {
	u.SetExcluded(execution.FieldState)
	return u
}

// ClearState clears the value of the "state" field.
func (u *ExecutionUpsert) ClearState() *ExecutionUpsert {
	u.SetNull(execution.FieldState)
	return u
}

// SetPreviousState sets the "previous_state" field.
func (u *ExecutionUpsert) SetPreviousState(v execution.PreviousState) *ExecutionUpsert {
	u.Set(execution.FieldPreviousState, v)
	return u
}

// UpdatePreviousState sets the "previous_state" field to the value that was provided on create.
func (u *ExecutionUpsert) UpdatePreviousState() *ExecutionUpsert {
	u.SetExcluded(execution.FieldPreviousState)
	return u
}

// ClearPreviousState clears the value of the "previous_state" field.
func (u *ExecutionUpsert) ClearPreviousState() *ExecutionUpsert {
	u.SetNull(execution.FieldPreviousState)
	return u
}

// SetStartTime sets the "start_time" field.
func (u *ExecutionUpsert) SetStartTime(v time.Time) *ExecutionUpsert {
	u.Set(execution.FieldStartTime, v)
	return u
}

// UpdateStartTime sets the "start_time" field to the value that was provided on create.
func (u *ExecutionUpsert) UpdateStartTime() *ExecutionUpsert {
	u.SetExcluded(execution.FieldStartTime)
	return u
}

// ClearStartTime clears the value of the "start_time" field.
func (u *ExecutionUpsert) ClearStartTime() *ExecutionUpsert {
	u.SetNull(execution.FieldStartTime)
	return u
}

// SetEndTime sets the "end_time" field.
func (u *ExecutionUpsert) SetEndTime(v time.Time) *ExecutionUpsert {
	u.Set(execution.FieldEndTime, v)
	return u
}

// UpdateEndTime sets the "end_time" field to the value that was provided on create.
func (u *ExecutionUpsert) UpdateEndTime() *ExecutionUpsert {
	u.SetExcluded(execution.FieldEndTime)
	return u
}

// ClearEndTime clears the value of the "end_time" field.
func (u *ExecutionUpsert) ClearEndTime() *ExecutionUpsert {
	u.SetNull(execution.FieldEndTime)
	return u
}

// SetTaskID sets the "task_id" field.
func (u *ExecutionUpsert) SetTaskID(v uint64) *ExecutionUpsert {
	u.Set(execution.FieldTaskID, v)
	return u
}

// UpdateTaskID sets the "task_id" field to the value that was provided on create.
func (u *ExecutionUpsert) UpdateTaskID() *ExecutionUpsert {
	u.SetExcluded(execution.FieldTaskID)
	return u
}

// SetStepID sets the "step_id" field.
func (u *ExecutionUpsert) SetStepID(v uint64) *ExecutionUpsert {
	u.Set(execution.FieldStepID, v)
	return u
}

// UpdateStepID sets the "step_id" field to the value that was provided on create.
func (u *ExecutionUpsert) UpdateStepID() *ExecutionUpsert {
	u.SetExcluded(execution.FieldStepID)
	return u
}

// SetSeqNo sets the "seq_no" field.
func (u *ExecutionUpsert) SetSeqNo(v int64) *ExecutionUpsert {
	u.Set(execution.FieldSeqNo, v)
	return u
}

// UpdateSeqNo sets the "seq_no" field to the value that was provided on create.
func (u *ExecutionUpsert) UpdateSeqNo() *ExecutionUpsert {
	u.SetExcluded(execution.FieldSeqNo)
	return u
}

// AddSeqNo adds v to the "seq_no" field.
func (u *ExecutionUpsert) AddSeqNo(v int64) *ExecutionUpsert {
	u.Add(execution.FieldSeqNo, v)
	return u
}

// ClearSeqNo clears the value of the "seq_no" field.
func (u *ExecutionUpsert) ClearSeqNo() *ExecutionUpsert {
	u.SetNull(execution.FieldSeqNo)
	return u
}

// SetCode sets the "code" field.
func (u *ExecutionUpsert) SetCode(v int64) *ExecutionUpsert {
	u.Set(execution.FieldCode, v)
	return u
}

// UpdateCode sets the "code" field to the value that was provided on create.
func (u *ExecutionUpsert) UpdateCode() *ExecutionUpsert {
	u.SetExcluded(execution.FieldCode)
	return u
}

// AddCode adds v to the "code" field.
func (u *ExecutionUpsert) AddCode(v int64) *ExecutionUpsert {
	u.Add(execution.FieldCode, v)
	return u
}

// ClearCode clears the value of the "code" field.
func (u *ExecutionUpsert) ClearCode() *ExecutionUpsert {
	u.SetNull(execution.FieldCode)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.Execution.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(execution.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *ExecutionUpsertOne) UpdateNewValues() *ExecutionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(execution.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(execution.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Execution.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ExecutionUpsertOne) Ignore() *ExecutionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ExecutionUpsertOne) DoNothing() *ExecutionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ExecutionCreate.OnConflict
// documentation for more info.
func (u *ExecutionUpsertOne) Update(set func(*ExecutionUpsert)) *ExecutionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ExecutionUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ExecutionUpsertOne) SetUpdatedAt(v time.Time) *ExecutionUpsertOne {
	return u.Update(func(s *ExecutionUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ExecutionUpsertOne) UpdateUpdatedAt() *ExecutionUpsertOne {
	return u.Update(func(s *ExecutionUpsert) {
		s.UpdateUpdatedAt()
	})
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (u *ExecutionUpsertOne) ClearUpdatedAt() *ExecutionUpsertOne {
	return u.Update(func(s *ExecutionUpsert) {
		s.ClearUpdatedAt()
	})
}

// SetCreatedBy sets the "created_by" field.
func (u *ExecutionUpsertOne) SetCreatedBy(v string) *ExecutionUpsertOne {
	return u.Update(func(s *ExecutionUpsert) {
		s.SetCreatedBy(v)
	})
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *ExecutionUpsertOne) UpdateCreatedBy() *ExecutionUpsertOne {
	return u.Update(func(s *ExecutionUpsert) {
		s.UpdateCreatedBy()
	})
}

// ClearCreatedBy clears the value of the "created_by" field.
func (u *ExecutionUpsertOne) ClearCreatedBy() *ExecutionUpsertOne {
	return u.Update(func(s *ExecutionUpsert) {
		s.ClearCreatedBy()
	})
}

// SetUpdatedBy sets the "updated_by" field.
func (u *ExecutionUpsertOne) SetUpdatedBy(v string) *ExecutionUpsertOne {
	return u.Update(func(s *ExecutionUpsert) {
		s.SetUpdatedBy(v)
	})
}

// UpdateUpdatedBy sets the "updated_by" field to the value that was provided on create.
func (u *ExecutionUpsertOne) UpdateUpdatedBy() *ExecutionUpsertOne {
	return u.Update(func(s *ExecutionUpsert) {
		s.UpdateUpdatedBy()
	})
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (u *ExecutionUpsertOne) ClearUpdatedBy() *ExecutionUpsertOne {
	return u.Update(func(s *ExecutionUpsert) {
		s.ClearUpdatedBy()
	})
}

// SetDisabled sets the "disabled" field.
func (u *ExecutionUpsertOne) SetDisabled(v bool) *ExecutionUpsertOne {
	return u.Update(func(s *ExecutionUpsert) {
		s.SetDisabled(v)
	})
}

// UpdateDisabled sets the "disabled" field to the value that was provided on create.
func (u *ExecutionUpsertOne) UpdateDisabled() *ExecutionUpsertOne {
	return u.Update(func(s *ExecutionUpsert) {
		s.UpdateDisabled()
	})
}

// ClearDisabled clears the value of the "disabled" field.
func (u *ExecutionUpsertOne) ClearDisabled() *ExecutionUpsertOne {
	return u.Update(func(s *ExecutionUpsert) {
		s.ClearDisabled()
	})
}

// SetMessage sets the "message" field.
func (u *ExecutionUpsertOne) SetMessage(v string) *ExecutionUpsertOne {
	return u.Update(func(s *ExecutionUpsert) {
		s.SetMessage(v)
	})
}

// UpdateMessage sets the "message" field to the value that was provided on create.
func (u *ExecutionUpsertOne) UpdateMessage() *ExecutionUpsertOne {
	return u.Update(func(s *ExecutionUpsert) {
		s.UpdateMessage()
	})
}

// ClearMessage clears the value of the "message" field.
func (u *ExecutionUpsertOne) ClearMessage() *ExecutionUpsertOne {
	return u.Update(func(s *ExecutionUpsert) {
		s.ClearMessage()
	})
}

// SetState sets the "state" field.
func (u *ExecutionUpsertOne) SetState(v execution.State) *ExecutionUpsertOne {
	return u.Update(func(s *ExecutionUpsert) {
		s.SetState(v)
	})
}

// UpdateState sets the "state" field to the value that was provided on create.
func (u *ExecutionUpsertOne) UpdateState() *ExecutionUpsertOne {
	return u.Update(func(s *ExecutionUpsert) {
		s.UpdateState()
	})
}

// ClearState clears the value of the "state" field.
func (u *ExecutionUpsertOne) ClearState() *ExecutionUpsertOne {
	return u.Update(func(s *ExecutionUpsert) {
		s.ClearState()
	})
}

// SetPreviousState sets the "previous_state" field.
func (u *ExecutionUpsertOne) SetPreviousState(v execution.PreviousState) *ExecutionUpsertOne {
	return u.Update(func(s *ExecutionUpsert) {
		s.SetPreviousState(v)
	})
}

// UpdatePreviousState sets the "previous_state" field to the value that was provided on create.
func (u *ExecutionUpsertOne) UpdatePreviousState() *ExecutionUpsertOne {
	return u.Update(func(s *ExecutionUpsert) {
		s.UpdatePreviousState()
	})
}

// ClearPreviousState clears the value of the "previous_state" field.
func (u *ExecutionUpsertOne) ClearPreviousState() *ExecutionUpsertOne {
	return u.Update(func(s *ExecutionUpsert) {
		s.ClearPreviousState()
	})
}

// SetStartTime sets the "start_time" field.
func (u *ExecutionUpsertOne) SetStartTime(v time.Time) *ExecutionUpsertOne {
	return u.Update(func(s *ExecutionUpsert) {
		s.SetStartTime(v)
	})
}

// UpdateStartTime sets the "start_time" field to the value that was provided on create.
func (u *ExecutionUpsertOne) UpdateStartTime() *ExecutionUpsertOne {
	return u.Update(func(s *ExecutionUpsert) {
		s.UpdateStartTime()
	})
}

// ClearStartTime clears the value of the "start_time" field.
func (u *ExecutionUpsertOne) ClearStartTime() *ExecutionUpsertOne {
	return u.Update(func(s *ExecutionUpsert) {
		s.ClearStartTime()
	})
}

// SetEndTime sets the "end_time" field.
func (u *ExecutionUpsertOne) SetEndTime(v time.Time) *ExecutionUpsertOne {
	return u.Update(func(s *ExecutionUpsert) {
		s.SetEndTime(v)
	})
}

// UpdateEndTime sets the "end_time" field to the value that was provided on create.
func (u *ExecutionUpsertOne) UpdateEndTime() *ExecutionUpsertOne {
	return u.Update(func(s *ExecutionUpsert) {
		s.UpdateEndTime()
	})
}

// ClearEndTime clears the value of the "end_time" field.
func (u *ExecutionUpsertOne) ClearEndTime() *ExecutionUpsertOne {
	return u.Update(func(s *ExecutionUpsert) {
		s.ClearEndTime()
	})
}

// SetTaskID sets the "task_id" field.
func (u *ExecutionUpsertOne) SetTaskID(v uint64) *ExecutionUpsertOne {
	return u.Update(func(s *ExecutionUpsert) {
		s.SetTaskID(v)
	})
}

// UpdateTaskID sets the "task_id" field to the value that was provided on create.
func (u *ExecutionUpsertOne) UpdateTaskID() *ExecutionUpsertOne {
	return u.Update(func(s *ExecutionUpsert) {
		s.UpdateTaskID()
	})
}

// SetStepID sets the "step_id" field.
func (u *ExecutionUpsertOne) SetStepID(v uint64) *ExecutionUpsertOne {
	return u.Update(func(s *ExecutionUpsert) {
		s.SetStepID(v)
	})
}

// UpdateStepID sets the "step_id" field to the value that was provided on create.
func (u *ExecutionUpsertOne) UpdateStepID() *ExecutionUpsertOne {
	return u.Update(func(s *ExecutionUpsert) {
		s.UpdateStepID()
	})
}

// SetSeqNo sets the "seq_no" field.
func (u *ExecutionUpsertOne) SetSeqNo(v int64) *ExecutionUpsertOne {
	return u.Update(func(s *ExecutionUpsert) {
		s.SetSeqNo(v)
	})
}

// AddSeqNo adds v to the "seq_no" field.
func (u *ExecutionUpsertOne) AddSeqNo(v int64) *ExecutionUpsertOne {
	return u.Update(func(s *ExecutionUpsert) {
		s.AddSeqNo(v)
	})
}

// UpdateSeqNo sets the "seq_no" field to the value that was provided on create.
func (u *ExecutionUpsertOne) UpdateSeqNo() *ExecutionUpsertOne {
	return u.Update(func(s *ExecutionUpsert) {
		s.UpdateSeqNo()
	})
}

// ClearSeqNo clears the value of the "seq_no" field.
func (u *ExecutionUpsertOne) ClearSeqNo() *ExecutionUpsertOne {
	return u.Update(func(s *ExecutionUpsert) {
		s.ClearSeqNo()
	})
}

// SetCode sets the "code" field.
func (u *ExecutionUpsertOne) SetCode(v int64) *ExecutionUpsertOne {
	return u.Update(func(s *ExecutionUpsert) {
		s.SetCode(v)
	})
}

// AddCode adds v to the "code" field.
func (u *ExecutionUpsertOne) AddCode(v int64) *ExecutionUpsertOne {
	return u.Update(func(s *ExecutionUpsert) {
		s.AddCode(v)
	})
}

// UpdateCode sets the "code" field to the value that was provided on create.
func (u *ExecutionUpsertOne) UpdateCode() *ExecutionUpsertOne {
	return u.Update(func(s *ExecutionUpsert) {
		s.UpdateCode()
	})
}

// ClearCode clears the value of the "code" field.
func (u *ExecutionUpsertOne) ClearCode() *ExecutionUpsertOne {
	return u.Update(func(s *ExecutionUpsert) {
		s.ClearCode()
	})
}

// Exec executes the query.
func (u *ExecutionUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("entv1: missing options for ExecutionCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ExecutionUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ExecutionUpsertOne) ID(ctx context.Context) (id uint64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ExecutionUpsertOne) IDX(ctx context.Context) uint64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ExecutionCreateBulk is the builder for creating many Execution entities in bulk.
type ExecutionCreateBulk struct {
	config
	err      error
	builders []*ExecutionCreate
	conflict []sql.ConflictOption
}

// Save creates the Execution entities in the database.
func (_c *ExecutionCreateBulk) Save(ctx context.Context) ([]*Execution, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Execution, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ExecutionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = uint64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ExecutionCreateBulk) SaveX(ctx context.Context) []*Execution {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ExecutionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ExecutionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Execution.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ExecutionUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *ExecutionCreateBulk) OnConflict(opts ...sql.ConflictOption) *ExecutionUpsertBulk {
	_c.conflict = opts
	return &ExecutionUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Execution.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ExecutionCreateBulk) OnConflictColumns(columns ...string) *ExecutionUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ExecutionUpsertBulk{
		create: _c,
	}
}

// ExecutionUpsertBulk is the builder for "upsert"-ing
// a bulk of Execution nodes.
type ExecutionUpsertBulk struct {
	create *ExecutionCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Execution.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(execution.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *ExecutionUpsertBulk) UpdateNewValues() *ExecutionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(execution.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(execution.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Execution.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ExecutionUpsertBulk) Ignore() *ExecutionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ExecutionUpsertBulk) DoNothing() *ExecutionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ExecutionCreateBulk.OnConflict
// documentation for more info.
func (u *ExecutionUpsertBulk) Update(set func(*ExecutionUpsert)) *ExecutionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ExecutionUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ExecutionUpsertBulk) SetUpdatedAt(v time.Time) *ExecutionUpsertBulk {
	return u.Update(func(s *ExecutionUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ExecutionUpsertBulk) UpdateUpdatedAt() *ExecutionUpsertBulk {
	return u.Update(func(s *ExecutionUpsert) {
		s.UpdateUpdatedAt()
	})
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (u *ExecutionUpsertBulk) ClearUpdatedAt() *ExecutionUpsertBulk {
	return u.Update(func(s *ExecutionUpsert) {
		s.ClearUpdatedAt()
	})
}

// SetCreatedBy sets the "created_by" field.
func (u *ExecutionUpsertBulk) SetCreatedBy(v string) *ExecutionUpsertBulk {
	return u.Update(func(s *ExecutionUpsert) {
		s.SetCreatedBy(v)
	})
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *ExecutionUpsertBulk) UpdateCreatedBy() *ExecutionUpsertBulk {
	return u.Update(func(s *ExecutionUpsert) {
		s.UpdateCreatedBy()
	})
}

// ClearCreatedBy clears the value of the "created_by" field.
func (u *ExecutionUpsertBulk) ClearCreatedBy() *ExecutionUpsertBulk {
	return u.Update(func(s *ExecutionUpsert) {
		s.ClearCreatedBy()
	})
}

// SetUpdatedBy sets the "updated_by" field.
func (u *ExecutionUpsertBulk) SetUpdatedBy(v string) *ExecutionUpsertBulk {
	return u.Update(func(s *ExecutionUpsert) {
		s.SetUpdatedBy(v)
	})
}

// UpdateUpdatedBy sets the "updated_by" field to the value that was provided on create.
func (u *ExecutionUpsertBulk) UpdateUpdatedBy() *ExecutionUpsertBulk {
	return u.Update(func(s *ExecutionUpsert) {
		s.UpdateUpdatedBy()
	})
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (u *ExecutionUpsertBulk) ClearUpdatedBy() *ExecutionUpsertBulk {
	return u.Update(func(s *ExecutionUpsert) {
		s.ClearUpdatedBy()
	})
}

// SetDisabled sets the "disabled" field.
func (u *ExecutionUpsertBulk) SetDisabled(v bool) *ExecutionUpsertBulk {
	return u.Update(func(s *ExecutionUpsert) {
		s.SetDisabled(v)
	})
}

// UpdateDisabled sets the "disabled" field to the value that was provided on create.
func (u *ExecutionUpsertBulk) UpdateDisabled() *ExecutionUpsertBulk {
	return u.Update(func(s *ExecutionUpsert) {
		s.UpdateDisabled()
	})
}

// ClearDisabled clears the value of the "disabled" field.
func (u *ExecutionUpsertBulk) ClearDisabled() *ExecutionUpsertBulk {
	return u.Update(func(s *ExecutionUpsert) {
		s.ClearDisabled()
	})
}

// SetMessage sets the "message" field.
func (u *ExecutionUpsertBulk) SetMessage(v string) *ExecutionUpsertBulk {
	return u.Update(func(s *ExecutionUpsert) {
		s.SetMessage(v)
	})
}

// UpdateMessage sets the "message" field to the value that was provided on create.
func (u *ExecutionUpsertBulk) UpdateMessage() *ExecutionUpsertBulk {
	return u.Update(func(s *ExecutionUpsert) {
		s.UpdateMessage()
	})
}

// ClearMessage clears the value of the "message" field.
func (u *ExecutionUpsertBulk) ClearMessage() *ExecutionUpsertBulk {
	return u.Update(func(s *ExecutionUpsert) {
		s.ClearMessage()
	})
}

// SetState sets the "state" field.
func (u *ExecutionUpsertBulk) SetState(v execution.State) *ExecutionUpsertBulk {
	return u.Update(func(s *ExecutionUpsert) {
		s.SetState(v)
	})
}

// UpdateState sets the "state" field to the value that was provided on create.
func (u *ExecutionUpsertBulk) UpdateState() *ExecutionUpsertBulk {
	return u.Update(func(s *ExecutionUpsert) {
		s.UpdateState()
	})
}

// ClearState clears the value of the "state" field.
func (u *ExecutionUpsertBulk) ClearState() *ExecutionUpsertBulk {
	return u.Update(func(s *ExecutionUpsert) {
		s.ClearState()
	})
}

// SetPreviousState sets the "previous_state" field.
func (u *ExecutionUpsertBulk) SetPreviousState(v execution.PreviousState) *ExecutionUpsertBulk {
	return u.Update(func(s *ExecutionUpsert) {
		s.SetPreviousState(v)
	})
}

// UpdatePreviousState sets the "previous_state" field to the value that was provided on create.
func (u *ExecutionUpsertBulk) UpdatePreviousState() *ExecutionUpsertBulk {
	return u.Update(func(s *ExecutionUpsert) {
		s.UpdatePreviousState()
	})
}

// ClearPreviousState clears the value of the "previous_state" field.
func (u *ExecutionUpsertBulk) ClearPreviousState() *ExecutionUpsertBulk {
	return u.Update(func(s *ExecutionUpsert) {
		s.ClearPreviousState()
	})
}

// SetStartTime sets the "start_time" field.
func (u *ExecutionUpsertBulk) SetStartTime(v time.Time) *ExecutionUpsertBulk {
	return u.Update(func(s *ExecutionUpsert) {
		s.SetStartTime(v)
	})
}

// UpdateStartTime sets the "start_time" field to the value that was provided on create.
func (u *ExecutionUpsertBulk) UpdateStartTime() *ExecutionUpsertBulk {
	return u.Update(func(s *ExecutionUpsert) {
		s.UpdateStartTime()
	})
}

// ClearStartTime clears the value of the "start_time" field.
func (u *ExecutionUpsertBulk) ClearStartTime() *ExecutionUpsertBulk {
	return u.Update(func(s *ExecutionUpsert) {
		s.ClearStartTime()
	})
}

// SetEndTime sets the "end_time" field.
func (u *ExecutionUpsertBulk) SetEndTime(v time.Time) *ExecutionUpsertBulk {
	return u.Update(func(s *ExecutionUpsert) {
		s.SetEndTime(v)
	})
}

// UpdateEndTime sets the "end_time" field to the value that was provided on create.
func (u *ExecutionUpsertBulk) UpdateEndTime() *ExecutionUpsertBulk {
	return u.Update(func(s *ExecutionUpsert) {
		s.UpdateEndTime()
	})
}

// ClearEndTime clears the value of the "end_time" field.
func (u *ExecutionUpsertBulk) ClearEndTime() *ExecutionUpsertBulk {
	return u.Update(func(s *ExecutionUpsert) {
		s.ClearEndTime()
	})
}

// SetTaskID sets the "task_id" field.
func (u *ExecutionUpsertBulk) SetTaskID(v uint64) *ExecutionUpsertBulk {
	return u.Update(func(s *ExecutionUpsert) {
		s.SetTaskID(v)
	})
}

// UpdateTaskID sets the "task_id" field to the value that was provided on create.
func (u *ExecutionUpsertBulk) UpdateTaskID() *ExecutionUpsertBulk {
	return u.Update(func(s *ExecutionUpsert) {
		s.UpdateTaskID()
	})
}

// SetStepID sets the "step_id" field.
func (u *ExecutionUpsertBulk) SetStepID(v uint64) *ExecutionUpsertBulk {
	return u.Update(func(s *ExecutionUpsert) {
		s.SetStepID(v)
	})
}

// UpdateStepID sets the "step_id" field to the value that was provided on create.
func (u *ExecutionUpsertBulk) UpdateStepID() *ExecutionUpsertBulk {
	return u.Update(func(s *ExecutionUpsert) {
		s.UpdateStepID()
	})
}

// SetSeqNo sets the "seq_no" field.
func (u *ExecutionUpsertBulk) SetSeqNo(v int64) *ExecutionUpsertBulk {
	return u.Update(func(s *ExecutionUpsert) {
		s.SetSeqNo(v)
	})
}

// AddSeqNo adds v to the "seq_no" field.
func (u *ExecutionUpsertBulk) AddSeqNo(v int64) *ExecutionUpsertBulk {
	return u.Update(func(s *ExecutionUpsert) {
		s.AddSeqNo(v)
	})
}

// UpdateSeqNo sets the "seq_no" field to the value that was provided on create.
func (u *ExecutionUpsertBulk) UpdateSeqNo() *ExecutionUpsertBulk {
	return u.Update(func(s *ExecutionUpsert) {
		s.UpdateSeqNo()
	})
}

// ClearSeqNo clears the value of the "seq_no" field.
func (u *ExecutionUpsertBulk) ClearSeqNo() *ExecutionUpsertBulk {
	return u.Update(func(s *ExecutionUpsert) {
		s.ClearSeqNo()
	})
}

// SetCode sets the "code" field.
func (u *ExecutionUpsertBulk) SetCode(v int64) *ExecutionUpsertBulk {
	return u.Update(func(s *ExecutionUpsert) {
		s.SetCode(v)
	})
}

// AddCode adds v to the "code" field.
func (u *ExecutionUpsertBulk) AddCode(v int64) *ExecutionUpsertBulk {
	return u.Update(func(s *ExecutionUpsert) {
		s.AddCode(v)
	})
}

// UpdateCode sets the "code" field to the value that was provided on create.
func (u *ExecutionUpsertBulk) UpdateCode() *ExecutionUpsertBulk {
	return u.Update(func(s *ExecutionUpsert) {
		s.UpdateCode()
	})
}

// ClearCode clears the value of the "code" field.
func (u *ExecutionUpsertBulk) ClearCode() *ExecutionUpsertBulk {
	return u.Update(func(s *ExecutionUpsert) {
		s.ClearCode()
	})
}

// Exec executes the query.
func (u *ExecutionUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("entv1: OnConflict was set for builder %d. Set it on the ExecutionCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("entv1: missing options for ExecutionCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ExecutionUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
