// Code generated by ent, DO NOT EDIT.

package entv1

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/busyster996/dagflow/internal/entv1/execution"
	"github.com/busyster996/dagflow/internal/entv1/output"
)

// OutputCreate is the builder for creating a Output entity.
type OutputCreate struct {
	config
	mutation *OutputMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *OutputCreate) SetCreatedAt(v time.Time) *OutputCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *OutputCreate) SetNillableCreatedAt(v *time.Time) *OutputCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *OutputCreate) SetUpdatedAt(v time.Time) *OutputCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *OutputCreate) SetNillableUpdatedAt(v *time.Time) *OutputCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetCreatedBy sets the "created_by" field.
func (_c *OutputCreate) SetCreatedBy(v string) *OutputCreate {
	_c.mutation.SetCreatedBy(v)
	return _c
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_c *OutputCreate) SetNillableCreatedBy(v *string) *OutputCreate {
	if v != nil {
		_c.SetCreatedBy(*v)
	}
	return _c
}

// SetUpdatedBy sets the "updated_by" field.
func (_c *OutputCreate) SetUpdatedBy(v string) *OutputCreate {
	_c.mutation.SetUpdatedBy(v)
	return _c
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_c *OutputCreate) SetNillableUpdatedBy(v *string) *OutputCreate {
	if v != nil {
		_c.SetUpdatedBy(*v)
	}
	return _c
}

// SetExecID sets the "exec_id" field.
func (_c *OutputCreate) SetExecID(v uint64) *OutputCreate {
	_c.mutation.SetExecID(v)
	return _c
}

// SetTimestamp sets the "timestamp" field.
func (_c *OutputCreate) SetTimestamp(v int64) *OutputCreate {
	_c.mutation.SetTimestamp(v)
	return _c
}

// SetNillableTimestamp sets the "timestamp" field if the given value is not nil.
func (_c *OutputCreate) SetNillableTimestamp(v *int64) *OutputCreate {
	if v != nil {
		_c.SetTimestamp(*v)
	}
	return _c
}

// SetContent sets the "content" field.
func (_c *OutputCreate) SetContent(v string) *OutputCreate {
	_c.mutation.SetContent(v)
	return _c
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_c *OutputCreate) SetNillableContent(v *string) *OutputCreate {
	if v != nil {
		_c.SetContent(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *OutputCreate) SetID(v uint64) *OutputCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetExecutionID sets the "execution" edge to the Execution entity by ID.
func (_c *OutputCreate) SetExecutionID(id uint64) *OutputCreate {
	_c.mutation.SetExecutionID(id)
	return _c
}

// SetExecution sets the "execution" edge to the Execution entity.
func (_c *OutputCreate) SetExecution(v *Execution) *OutputCreate {
	return _c.SetExecutionID(v.ID)
}

// Mutation returns the OutputMutation object of the builder.
func (_c *OutputCreate) Mutation() *OutputMutation {
	return _c.mutation
}

// Save creates the Output in the database.
func (_c *OutputCreate) Save(ctx context.Context) (*Output, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *OutputCreate) SaveX(ctx context.Context) *Output {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OutputCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OutputCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *OutputCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := output.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := output.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Timestamp(); !ok {
		v := output.DefaultTimestamp()
		_c.mutation.SetTimestamp(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *OutputCreate) check() error {
	if _, ok := _c.mutation.ExecID(); !ok {
		return &ValidationError{Name: "exec_id", err: errors.New(`entv1: missing required field "Output.exec_id"`)}
	}
	if len(_c.mutation.ExecutionIDs()) == 0 {
		return &ValidationError{Name: "execution", err: errors.New(`entv1: missing required edge "Output.execution"`)}
	}
	return nil
}

func (_c *OutputCreate) sqlSave(ctx context.Context) (*Output, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = uint64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *OutputCreate) createSpec() (*Output, *sqlgraph.CreateSpec) {
	var (
		_node = &Output{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(output.Table, sqlgraph.NewFieldSpec(output.FieldID, field.TypeUint64))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(output.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = &value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(output.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = &value
	}
	if value, ok := _c.mutation.CreatedBy(); ok {
		_spec.SetField(output.FieldCreatedBy, field.TypeString, value)
		_node.CreatedBy = &value
	}
	if value, ok := _c.mutation.UpdatedBy(); ok {
		_spec.SetField(output.FieldUpdatedBy, field.TypeString, value)
		_node.UpdatedBy = &value
	}
	if value, ok := _c.mutation.Timestamp(); ok {
		_spec.SetField(output.FieldTimestamp, field.TypeInt64, value)
		_node.Timestamp = &value
	}
	if value, ok := _c.mutation.Content(); ok {
		_spec.SetField(output.FieldContent, field.TypeString, value)
		_node.Content = &value
	}
	if nodes := _c.mutation.ExecutionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   output.ExecutionTable,
			Columns: []string{output.ExecutionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(execution.FieldID, field.TypeUint64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ExecID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Output.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.OutputUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *OutputCreate) OnConflict(opts ...sql.ConflictOption) *OutputUpsertOne {
	_c.conflict = opts
	return &OutputUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Output.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *OutputCreate) OnConflictColumns(columns ...string) *OutputUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &OutputUpsertOne{
		create: _c,
	}
}

type (
	// OutputUpsertOne is the builder for "upsert"-ing
	//  one Output node.
	OutputUpsertOne struct {
		create *OutputCreate
	}

	// OutputUpsert is the "OnConflict" setter.
	OutputUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *OutputUpsert) SetUpdatedAt(v time.Time) *OutputUpsert {
	u.Set(output.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *OutputUpsert) UpdateUpdatedAt() *OutputUpsert {
	u.SetExcluded(output.FieldUpdatedAt)
	return u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (u *OutputUpsert) ClearUpdatedAt() *OutputUpsert {
	u.SetNull(output.FieldUpdatedAt)
	return u
}

// SetCreatedBy sets the "created_by" field.
func (u *OutputUpsert) SetCreatedBy(v string) *OutputUpsert {
	u.Set(output.FieldCreatedBy, v)
	return u
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *OutputUpsert) UpdateCreatedBy() *OutputUpsert {
	u.SetExcluded(output.FieldCreatedBy)
	return u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (u *OutputUpsert) ClearCreatedBy() *OutputUpsert {
	u.SetNull(output.FieldCreatedBy)
	return u
}

// SetUpdatedBy sets the "updated_by" field.
func (u *OutputUpsert) SetUpdatedBy(v string) *OutputUpsert {
	u.Set(output.FieldUpdatedBy, v)
	return u
}

// UpdateUpdatedBy sets the "updated_by" field to the value that was provided on create.
func (u *OutputUpsert) UpdateUpdatedBy() *OutputUpsert {
	u.SetExcluded(output.FieldUpdatedBy)
	return u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (u *OutputUpsert) ClearUpdatedBy() *OutputUpsert {
	u.SetNull(output.FieldUpdatedBy)
	return u
}

// SetExecID sets the "exec_id" field.
func (u *OutputUpsert) SetExecID(v uint64) *OutputUpsert {
	u.Set(output.FieldExecID, v)
	return u
}

// UpdateExecID sets the "exec_id" field to the value that was provided on create.
func (u *OutputUpsert) UpdateExecID() *OutputUpsert {
	u.SetExcluded(output.FieldExecID)
	return u
}

// SetTimestamp sets the "timestamp" field.
func (u *OutputUpsert) SetTimestamp(v int64) *OutputUpsert {
	u.Set(output.FieldTimestamp, v)
	return u
}

// UpdateTimestamp sets the "timestamp" field to the value that was provided on create.
func (u *OutputUpsert) UpdateTimestamp() *OutputUpsert {
	u.SetExcluded(output.FieldTimestamp)
	return u
}

// AddTimestamp adds v to the "timestamp" field.
func (u *OutputUpsert) AddTimestamp(v int64) *OutputUpsert {
	u.Add(output.FieldTimestamp, v)
	return u
}

// ClearTimestamp clears the value of the "timestamp" field.
func (u *OutputUpsert) ClearTimestamp() *OutputUpsert {
	u.SetNull(output.FieldTimestamp)
	return u
}

// SetContent sets the "content" field.
func (u *OutputUpsert) SetContent(v string) *OutputUpsert {
	u.Set(output.FieldContent, v)
	return u
}

// UpdateContent sets the "content" field to the value that was provided on create.
func (u *OutputUpsert) UpdateContent() *OutputUpsert {
	u.SetExcluded(output.FieldContent)
	return u
}

// ClearContent clears the value of the "content" field.
func (u *OutputUpsert) ClearContent() *OutputUpsert {
	u.SetNull(output.FieldContent)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.Output.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(output.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *OutputUpsertOne) UpdateNewValues() *OutputUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(output.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(output.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Output.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *OutputUpsertOne) Ignore() *OutputUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *OutputUpsertOne) DoNothing() *OutputUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the OutputCreate.OnConflict
// documentation for more info.
func (u *OutputUpsertOne) Update(set func(*OutputUpsert)) *OutputUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&OutputUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *OutputUpsertOne) SetUpdatedAt(v time.Time) *OutputUpsertOne {
	return u.Update(func(s *OutputUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *OutputUpsertOne) UpdateUpdatedAt() *OutputUpsertOne {
	return u.Update(func(s *OutputUpsert) {
		s.UpdateUpdatedAt()
	})
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (u *OutputUpsertOne) ClearUpdatedAt() *OutputUpsertOne {
	return u.Update(func(s *OutputUpsert) {
		s.ClearUpdatedAt()
	})
}

// SetCreatedBy sets the "created_by" field.
func (u *OutputUpsertOne) SetCreatedBy(v string) *OutputUpsertOne {
	return u.Update(func(s *OutputUpsert) {
		s.SetCreatedBy(v)
	})
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *OutputUpsertOne) UpdateCreatedBy() *OutputUpsertOne {
	return u.Update(func(s *OutputUpsert) {
		s.UpdateCreatedBy()
	})
}

// ClearCreatedBy clears the value of the "created_by" field.
func (u *OutputUpsertOne) ClearCreatedBy() *OutputUpsertOne {
	return u.Update(func(s *OutputUpsert) {
		s.ClearCreatedBy()
	})
}

// SetUpdatedBy sets the "updated_by" field.
func (u *OutputUpsertOne) SetUpdatedBy(v string) *OutputUpsertOne {
	return u.Update(func(s *OutputUpsert) {
		s.SetUpdatedBy(v)
	})
}

// UpdateUpdatedBy sets the "updated_by" field to the value that was provided on create.
func (u *OutputUpsertOne) UpdateUpdatedBy() *OutputUpsertOne {
	return u.Update(func(s *OutputUpsert) {
		s.UpdateUpdatedBy()
	})
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (u *OutputUpsertOne) ClearUpdatedBy() *OutputUpsertOne {
	return u.Update(func(s *OutputUpsert) {
		s.ClearUpdatedBy()
	})
}

// SetExecID sets the "exec_id" field.
func (u *OutputUpsertOne) SetExecID(v uint64) *OutputUpsertOne {
	return u.Update(func(s *OutputUpsert) {
		s.SetExecID(v)
	})
}

// UpdateExecID sets the "exec_id" field to the value that was provided on create.
func (u *OutputUpsertOne) UpdateExecID() *OutputUpsertOne {
	return u.Update(func(s *OutputUpsert) {
		s.UpdateExecID()
	})
}

// SetTimestamp sets the "timestamp" field.
func (u *OutputUpsertOne) SetTimestamp(v int64) *OutputUpsertOne {
	return u.Update(func(s *OutputUpsert) {
		s.SetTimestamp(v)
	})
}

// AddTimestamp adds v to the "timestamp" field.
func (u *OutputUpsertOne) AddTimestamp(v int64) *OutputUpsertOne {
	return u.Update(func(s *OutputUpsert) {
		s.AddTimestamp(v)
	})
}

// UpdateTimestamp sets the "timestamp" field to the value that was provided on create.
func (u *OutputUpsertOne) UpdateTimestamp() *OutputUpsertOne {
	return u.Update(func(s *OutputUpsert) {
		s.UpdateTimestamp()
	})
}

// ClearTimestamp clears the value of the "timestamp" field.
func (u *OutputUpsertOne) ClearTimestamp() *OutputUpsertOne {
	return u.Update(func(s *OutputUpsert) {
		s.ClearTimestamp()
	})
}

// SetContent sets the "content" field.
func (u *OutputUpsertOne) SetContent(v string) *OutputUpsertOne {
	return u.Update(func(s *OutputUpsert) {
		s.SetContent(v)
	})
}

// UpdateContent sets the "content" field to the value that was provided on create.
func (u *OutputUpsertOne) UpdateContent() *OutputUpsertOne {
	return u.Update(func(s *OutputUpsert) {
		s.UpdateContent()
	})
}

// ClearContent clears the value of the "content" field.
func (u *OutputUpsertOne) ClearContent() *OutputUpsertOne {
	return u.Update(func(s *OutputUpsert) {
		s.ClearContent()
	})
}

// Exec executes the query.
func (u *OutputUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("entv1: missing options for OutputCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *OutputUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *OutputUpsertOne) ID(ctx context.Context) (id uint64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *OutputUpsertOne) IDX(ctx context.Context) uint64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// OutputCreateBulk is the builder for creating many Output entities in bulk.
type OutputCreateBulk struct {
	config
	err      error
	builders []*OutputCreate
	conflict []sql.ConflictOption
}

// Save creates the Output entities in the database.
func (_c *OutputCreateBulk) Save(ctx context.Context) ([]*Output, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Output, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*OutputMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = uint64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *OutputCreateBulk) SaveX(ctx context.Context) []*Output {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OutputCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OutputCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Output.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.OutputUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *OutputCreateBulk) OnConflict(opts ...sql.ConflictOption) *OutputUpsertBulk {
	_c.conflict = opts
	return &OutputUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Output.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *OutputCreateBulk) OnConflictColumns(columns ...string) *OutputUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &OutputUpsertBulk{
		create: _c,
	}
}

// OutputUpsertBulk is the builder for "upsert"-ing
// a bulk of Output nodes.
type OutputUpsertBulk struct {
	create *OutputCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Output.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(output.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *OutputUpsertBulk) UpdateNewValues() *OutputUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(output.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(output.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Output.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *OutputUpsertBulk) Ignore() *OutputUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *OutputUpsertBulk) DoNothing() *OutputUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the OutputCreateBulk.OnConflict
// documentation for more info.
func (u *OutputUpsertBulk) Update(set func(*OutputUpsert)) *OutputUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&OutputUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *OutputUpsertBulk) SetUpdatedAt(v time.Time) *OutputUpsertBulk {
	return u.Update(func(s *OutputUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *OutputUpsertBulk) UpdateUpdatedAt() *OutputUpsertBulk {
	return u.Update(func(s *OutputUpsert) {
		s.UpdateUpdatedAt()
	})
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (u *OutputUpsertBulk) ClearUpdatedAt() *OutputUpsertBulk {
	return u.Update(func(s *OutputUpsert) {
		s.ClearUpdatedAt()
	})
}

// SetCreatedBy sets the "created_by" field.
func (u *OutputUpsertBulk) SetCreatedBy(v string) *OutputUpsertBulk {
	return u.Update(func(s *OutputUpsert) {
		s.SetCreatedBy(v)
	})
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *OutputUpsertBulk) UpdateCreatedBy() *OutputUpsertBulk {
	return u.Update(func(s *OutputUpsert) {
		s.UpdateCreatedBy()
	})
}

// ClearCreatedBy clears the value of the "created_by" field.
func (u *OutputUpsertBulk) ClearCreatedBy() *OutputUpsertBulk {
	return u.Update(func(s *OutputUpsert) {
		s.ClearCreatedBy()
	})
}

// SetUpdatedBy sets the "updated_by" field.
func (u *OutputUpsertBulk) SetUpdatedBy(v string) *OutputUpsertBulk {
	return u.Update(func(s *OutputUpsert) {
		s.SetUpdatedBy(v)
	})
}

// UpdateUpdatedBy sets the "updated_by" field to the value that was provided on create.
func (u *OutputUpsertBulk) UpdateUpdatedBy() *OutputUpsertBulk {
	return u.Update(func(s *OutputUpsert) {
		s.UpdateUpdatedBy()
	})
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (u *OutputUpsertBulk) ClearUpdatedBy() *OutputUpsertBulk {
	return u.Update(func(s *OutputUpsert) {
		s.ClearUpdatedBy()
	})
}

// SetExecID sets the "exec_id" field.
func (u *OutputUpsertBulk) SetExecID(v uint64) *OutputUpsertBulk {
	return u.Update(func(s *OutputUpsert) {
		s.SetExecID(v)
	})
}

// UpdateExecID sets the "exec_id" field to the value that was provided on create.
func (u *OutputUpsertBulk) UpdateExecID() *OutputUpsertBulk {
	return u.Update(func(s *OutputUpsert) {
		s.UpdateExecID()
	})
}

// SetTimestamp sets the "timestamp" field.
func (u *OutputUpsertBulk) SetTimestamp(v int64) *OutputUpsertBulk {
	return u.Update(func(s *OutputUpsert) {
		s.SetTimestamp(v)
	})
}

// AddTimestamp adds v to the "timestamp" field.
func (u *OutputUpsertBulk) AddTimestamp(v int64) *OutputUpsertBulk {
	return u.Update(func(s *OutputUpsert) {
		s.AddTimestamp(v)
	})
}

// UpdateTimestamp sets the "timestamp" field to the value that was provided on create.
func (u *OutputUpsertBulk) UpdateTimestamp() *OutputUpsertBulk {
	return u.Update(func(s *OutputUpsert) {
		s.UpdateTimestamp()
	})
}

// ClearTimestamp clears the value of the "timestamp" field.
func (u *OutputUpsertBulk) ClearTimestamp() *OutputUpsertBulk {
	return u.Update(func(s *OutputUpsert) {
		s.ClearTimestamp()
	})
}

// SetContent sets the "content" field.
func (u *OutputUpsertBulk) SetContent(v string) *OutputUpsertBulk {
	return u.Update(func(s *OutputUpsert) {
		s.SetContent(v)
	})
}

// UpdateContent sets the "content" field to the value that was provided on create.
func (u *OutputUpsertBulk) UpdateContent() *OutputUpsertBulk {
	return u.Update(func(s *OutputUpsert) {
		s.UpdateContent()
	})
}

// ClearContent clears the value of the "content" field.
func (u *OutputUpsertBulk) ClearContent() *OutputUpsertBulk {
	return u.Update(func(s *OutputUpsert) {
		s.ClearContent()
	})
}

// Exec executes the query.
func (u *OutputUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("entv1: OnConflict was set for builder %d. Set it on the OutputCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("entv1: missing options for OutputCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *OutputUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
