// Code generated by ent, DO NOT EDIT.

package entv1

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/busyster996/dagflow/internal/entv1/param"
	"github.com/busyster996/dagflow/internal/entv1/predicate"
	"github.com/busyster996/dagflow/internal/entv1/step"
	"github.com/busyster996/dagflow/internal/entv1/stepparam"
	"github.com/busyster996/dagflow/internal/entv1/task"
	"github.com/busyster996/dagflow/internal/entv1/taskparam"
)

// ParamUpdate is the builder for updating Param entities.
type ParamUpdate struct {
	config
	hooks     []Hook
	mutation  *ParamMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the ParamUpdate builder.
func (_u *ParamUpdate) Where(ps ...predicate.Param) *ParamUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ParamUpdate) SetUpdatedAt(v time.Time) *ParamUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (_u *ParamUpdate) ClearUpdatedAt() *ParamUpdate {
	_u.mutation.ClearUpdatedAt()
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *ParamUpdate) SetCreatedBy(v string) *ParamUpdate {
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *ParamUpdate) SetNillableCreatedBy(v *string) *ParamUpdate {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (_u *ParamUpdate) ClearCreatedBy() *ParamUpdate {
	_u.mutation.ClearCreatedBy()
	return _u
}

// SetUpdatedBy sets the "updated_by" field.
func (_u *ParamUpdate) SetUpdatedBy(v string) *ParamUpdate {
	_u.mutation.SetUpdatedBy(v)
	return _u
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_u *ParamUpdate) SetNillableUpdatedBy(v *string) *ParamUpdate {
	if v != nil {
		_u.SetUpdatedBy(*v)
	}
	return _u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (_u *ParamUpdate) ClearUpdatedBy() *ParamUpdate {
	_u.mutation.ClearUpdatedBy()
	return _u
}

// SetName sets the "name" field.
func (_u *ParamUpdate) SetName(v string) *ParamUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ParamUpdate) SetNillableName(v *string) *ParamUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetValue sets the "value" field.
func (_u *ParamUpdate) SetValue(v string) *ParamUpdate {
	_u.mutation.SetValue(v)
	return _u
}

// SetNillableValue sets the "value" field if the given value is not nil.
func (_u *ParamUpdate) SetNillableValue(v *string) *ParamUpdate {
	if v != nil {
		_u.SetValue(*v)
	}
	return _u
}

// ClearValue clears the value of the "value" field.
func (_u *ParamUpdate) ClearValue() *ParamUpdate {
	_u.mutation.ClearValue()
	return _u
}

// AddTaskIDs adds the "tasks" edge to the Task entity by IDs.
func (_u *ParamUpdate) AddTaskIDs(ids ...uint64) *ParamUpdate {
	_u.mutation.AddTaskIDs(ids...)
	return _u
}

// AddTasks adds the "tasks" edges to the Task entity.
func (_u *ParamUpdate) AddTasks(v ...*Task) *ParamUpdate {
	ids := make([]uint64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddTaskIDs(ids...)
}

// AddStepIDs adds the "steps" edge to the Step entity by IDs.
func (_u *ParamUpdate) AddStepIDs(ids ...uint64) *ParamUpdate {
	_u.mutation.AddStepIDs(ids...)
	return _u
}

// AddSteps adds the "steps" edges to the Step entity.
func (_u *ParamUpdate) AddSteps(v ...*Step) *ParamUpdate {
	ids := make([]uint64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddStepIDs(ids...)
}

// AddTaskParamIDs adds the "task_params" edge to the TaskParam entity by IDs.
func (_u *ParamUpdate) AddTaskParamIDs(ids ...uint64) *ParamUpdate {
	_u.mutation.AddTaskParamIDs(ids...)
	return _u
}

// AddTaskParams adds the "task_params" edges to the TaskParam entity.
func (_u *ParamUpdate) AddTaskParams(v ...*TaskParam) *ParamUpdate {
	ids := make([]uint64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddTaskParamIDs(ids...)
}

// AddStepParamIDs adds the "step_params" edge to the StepParam entity by IDs.
func (_u *ParamUpdate) AddStepParamIDs(ids ...uint64) *ParamUpdate {
	_u.mutation.AddStepParamIDs(ids...)
	return _u
}

// AddStepParams adds the "step_params" edges to the StepParam entity.
func (_u *ParamUpdate) AddStepParams(v ...*StepParam) *ParamUpdate {
	ids := make([]uint64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddStepParamIDs(ids...)
}

// Mutation returns the ParamMutation object of the builder.
func (_u *ParamUpdate) Mutation() *ParamMutation {
	return _u.mutation
}

// ClearTasks clears all "tasks" edges to the Task entity.
func (_u *ParamUpdate) ClearTasks() *ParamUpdate {
	_u.mutation.ClearTasks()
	return _u
}

// RemoveTaskIDs removes the "tasks" edge to Task entities by IDs.
func (_u *ParamUpdate) RemoveTaskIDs(ids ...uint64) *ParamUpdate {
	_u.mutation.RemoveTaskIDs(ids...)
	return _u
}

// RemoveTasks removes "tasks" edges to Task entities.
func (_u *ParamUpdate) RemoveTasks(v ...*Task) *ParamUpdate {
	ids := make([]uint64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveTaskIDs(ids...)
}

// ClearSteps clears all "steps" edges to the Step entity.
func (_u *ParamUpdate) ClearSteps() *ParamUpdate {
	_u.mutation.ClearSteps()
	return _u
}

// RemoveStepIDs removes the "steps" edge to Step entities by IDs.
func (_u *ParamUpdate) RemoveStepIDs(ids ...uint64) *ParamUpdate {
	_u.mutation.RemoveStepIDs(ids...)
	return _u
}

// RemoveSteps removes "steps" edges to Step entities.
func (_u *ParamUpdate) RemoveSteps(v ...*Step) *ParamUpdate {
	ids := make([]uint64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveStepIDs(ids...)
}

// ClearTaskParams clears all "task_params" edges to the TaskParam entity.
func (_u *ParamUpdate) ClearTaskParams() *ParamUpdate {
	_u.mutation.ClearTaskParams()
	return _u
}

// RemoveTaskParamIDs removes the "task_params" edge to TaskParam entities by IDs.
func (_u *ParamUpdate) RemoveTaskParamIDs(ids ...uint64) *ParamUpdate {
	_u.mutation.RemoveTaskParamIDs(ids...)
	return _u
}

// RemoveTaskParams removes "task_params" edges to TaskParam entities.
func (_u *ParamUpdate) RemoveTaskParams(v ...*TaskParam) *ParamUpdate {
	ids := make([]uint64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveTaskParamIDs(ids...)
}

// ClearStepParams clears all "step_params" edges to the StepParam entity.
func (_u *ParamUpdate) ClearStepParams() *ParamUpdate {
	_u.mutation.ClearStepParams()
	return _u
}

// RemoveStepParamIDs removes the "step_params" edge to StepParam entities by IDs.
func (_u *ParamUpdate) RemoveStepParamIDs(ids ...uint64) *ParamUpdate {
	_u.mutation.RemoveStepParamIDs(ids...)
	return _u
}

// RemoveStepParams removes "step_params" edges to StepParam entities.
func (_u *ParamUpdate) RemoveStepParams(v ...*StepParam) *ParamUpdate {
	ids := make([]uint64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveStepParamIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ParamUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ParamUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ParamUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ParamUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ParamUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok && !_u.mutation.UpdatedAtCleared() {
		v := param.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ParamUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := param.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`entv1: validator failed for field "Param.name": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *ParamUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *ParamUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *ParamUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(param.Table, param.Columns, sqlgraph.NewFieldSpec(param.FieldID, field.TypeUint64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.CreatedAtCleared() {
		_spec.ClearField(param.FieldCreatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(param.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UpdatedAtCleared() {
		_spec.ClearField(param.FieldUpdatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(param.FieldCreatedBy, field.TypeString, value)
	}
	if _u.mutation.CreatedByCleared() {
		_spec.ClearField(param.FieldCreatedBy, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedBy(); ok {
		_spec.SetField(param.FieldUpdatedBy, field.TypeString, value)
	}
	if _u.mutation.UpdatedByCleared() {
		_spec.ClearField(param.FieldUpdatedBy, field.TypeString)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(param.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Value(); ok {
		_spec.SetField(param.FieldValue, field.TypeString, value)
	}
	if _u.mutation.ValueCleared() {
		_spec.ClearField(param.FieldValue, field.TypeString)
	}
	if _u.mutation.TasksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   param.TasksTable,
			Columns: param.TasksPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeUint64),
			},
		}
		createE := &TaskParamCreate{config: _u.config, mutation: newTaskParamMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedTasksIDs(); len(nodes) > 0 && !_u.mutation.TasksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   param.TasksTable,
			Columns: param.TasksPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeUint64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		createE := &TaskParamCreate{config: _u.config, mutation: newTaskParamMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TasksIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   param.TasksTable,
			Columns: param.TasksPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeUint64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		createE := &TaskParamCreate{config: _u.config, mutation: newTaskParamMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.StepsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   param.StepsTable,
			Columns: param.StepsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(step.FieldID, field.TypeUint64),
			},
		}
		createE := &StepParamCreate{config: _u.config, mutation: newStepParamMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedStepsIDs(); len(nodes) > 0 && !_u.mutation.StepsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   param.StepsTable,
			Columns: param.StepsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(step.FieldID, field.TypeUint64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		createE := &StepParamCreate{config: _u.config, mutation: newStepParamMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.StepsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   param.StepsTable,
			Columns: param.StepsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(step.FieldID, field.TypeUint64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		createE := &StepParamCreate{config: _u.config, mutation: newStepParamMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TaskParamsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   param.TaskParamsTable,
			Columns: []string{param.TaskParamsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(taskparam.FieldID, field.TypeUint64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedTaskParamsIDs(); len(nodes) > 0 && !_u.mutation.TaskParamsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   param.TaskParamsTable,
			Columns: []string{param.TaskParamsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(taskparam.FieldID, field.TypeUint64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TaskParamsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   param.TaskParamsTable,
			Columns: []string{param.TaskParamsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(taskparam.FieldID, field.TypeUint64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.StepParamsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   param.StepParamsTable,
			Columns: []string{param.StepParamsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(stepparam.FieldID, field.TypeUint64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedStepParamsIDs(); len(nodes) > 0 && !_u.mutation.StepParamsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   param.StepParamsTable,
			Columns: []string{param.StepParamsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(stepparam.FieldID, field.TypeUint64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.StepParamsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   param.StepParamsTable,
			Columns: []string{param.StepParamsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(stepparam.FieldID, field.TypeUint64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{param.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ParamUpdateOne is the builder for updating a single Param entity.
type ParamUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *ParamMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ParamUpdateOne) SetUpdatedAt(v time.Time) *ParamUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (_u *ParamUpdateOne) ClearUpdatedAt() *ParamUpdateOne {
	_u.mutation.ClearUpdatedAt()
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *ParamUpdateOne) SetCreatedBy(v string) *ParamUpdateOne {
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *ParamUpdateOne) SetNillableCreatedBy(v *string) *ParamUpdateOne {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (_u *ParamUpdateOne) ClearCreatedBy() *ParamUpdateOne {
	_u.mutation.ClearCreatedBy()
	return _u
}

// SetUpdatedBy sets the "updated_by" field.
func (_u *ParamUpdateOne) SetUpdatedBy(v string) *ParamUpdateOne {
	_u.mutation.SetUpdatedBy(v)
	return _u
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_u *ParamUpdateOne) SetNillableUpdatedBy(v *string) *ParamUpdateOne {
	if v != nil {
		_u.SetUpdatedBy(*v)
	}
	return _u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (_u *ParamUpdateOne) ClearUpdatedBy() *ParamUpdateOne {
	_u.mutation.ClearUpdatedBy()
	return _u
}

// SetName sets the "name" field.
func (_u *ParamUpdateOne) SetName(v string) *ParamUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ParamUpdateOne) SetNillableName(v *string) *ParamUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetValue sets the "value" field.
func (_u *ParamUpdateOne) SetValue(v string) *ParamUpdateOne {
	_u.mutation.SetValue(v)
	return _u
}

// SetNillableValue sets the "value" field if the given value is not nil.
func (_u *ParamUpdateOne) SetNillableValue(v *string) *ParamUpdateOne {
	if v != nil {
		_u.SetValue(*v)
	}
	return _u
}

// ClearValue clears the value of the "value" field.
func (_u *ParamUpdateOne) ClearValue() *ParamUpdateOne {
	_u.mutation.ClearValue()
	return _u
}

// AddTaskIDs adds the "tasks" edge to the Task entity by IDs.
func (_u *ParamUpdateOne) AddTaskIDs(ids ...uint64) *ParamUpdateOne {
	_u.mutation.AddTaskIDs(ids...)
	return _u
}

// AddTasks adds the "tasks" edges to the Task entity.
func (_u *ParamUpdateOne) AddTasks(v ...*Task) *ParamUpdateOne {
	ids := make([]uint64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddTaskIDs(ids...)
}

// AddStepIDs adds the "steps" edge to the Step entity by IDs.
func (_u *ParamUpdateOne) AddStepIDs(ids ...uint64) *ParamUpdateOne {
	_u.mutation.AddStepIDs(ids...)
	return _u
}

// AddSteps adds the "steps" edges to the Step entity.
func (_u *ParamUpdateOne) AddSteps(v ...*Step) *ParamUpdateOne {
	ids := make([]uint64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddStepIDs(ids...)
}

// AddTaskParamIDs adds the "task_params" edge to the TaskParam entity by IDs.
func (_u *ParamUpdateOne) AddTaskParamIDs(ids ...uint64) *ParamUpdateOne {
	_u.mutation.AddTaskParamIDs(ids...)
	return _u
}

// AddTaskParams adds the "task_params" edges to the TaskParam entity.
func (_u *ParamUpdateOne) AddTaskParams(v ...*TaskParam) *ParamUpdateOne {
	ids := make([]uint64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddTaskParamIDs(ids...)
}

// AddStepParamIDs adds the "step_params" edge to the StepParam entity by IDs.
func (_u *ParamUpdateOne) AddStepParamIDs(ids ...uint64) *ParamUpdateOne {
	_u.mutation.AddStepParamIDs(ids...)
	return _u
}

// AddStepParams adds the "step_params" edges to the StepParam entity.
func (_u *ParamUpdateOne) AddStepParams(v ...*StepParam) *ParamUpdateOne {
	ids := make([]uint64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddStepParamIDs(ids...)
}

// Mutation returns the ParamMutation object of the builder.
func (_u *ParamUpdateOne) Mutation() *ParamMutation {
	return _u.mutation
}

// ClearTasks clears all "tasks" edges to the Task entity.
func (_u *ParamUpdateOne) ClearTasks() *ParamUpdateOne {
	_u.mutation.ClearTasks()
	return _u
}

// RemoveTaskIDs removes the "tasks" edge to Task entities by IDs.
func (_u *ParamUpdateOne) RemoveTaskIDs(ids ...uint64) *ParamUpdateOne {
	_u.mutation.RemoveTaskIDs(ids...)
	return _u
}

// RemoveTasks removes "tasks" edges to Task entities.
func (_u *ParamUpdateOne) RemoveTasks(v ...*Task) *ParamUpdateOne {
	ids := make([]uint64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveTaskIDs(ids...)
}

// ClearSteps clears all "steps" edges to the Step entity.
func (_u *ParamUpdateOne) ClearSteps() *ParamUpdateOne {
	_u.mutation.ClearSteps()
	return _u
}

// RemoveStepIDs removes the "steps" edge to Step entities by IDs.
func (_u *ParamUpdateOne) RemoveStepIDs(ids ...uint64) *ParamUpdateOne {
	_u.mutation.RemoveStepIDs(ids...)
	return _u
}

// RemoveSteps removes "steps" edges to Step entities.
func (_u *ParamUpdateOne) RemoveSteps(v ...*Step) *ParamUpdateOne {
	ids := make([]uint64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveStepIDs(ids...)
}

// ClearTaskParams clears all "task_params" edges to the TaskParam entity.
func (_u *ParamUpdateOne) ClearTaskParams() *ParamUpdateOne {
	_u.mutation.ClearTaskParams()
	return _u
}

// RemoveTaskParamIDs removes the "task_params" edge to TaskParam entities by IDs.
func (_u *ParamUpdateOne) RemoveTaskParamIDs(ids ...uint64) *ParamUpdateOne {
	_u.mutation.RemoveTaskParamIDs(ids...)
	return _u
}

// RemoveTaskParams removes "task_params" edges to TaskParam entities.
func (_u *ParamUpdateOne) RemoveTaskParams(v ...*TaskParam) *ParamUpdateOne {
	ids := make([]uint64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveTaskParamIDs(ids...)
}

// ClearStepParams clears all "step_params" edges to the StepParam entity.
func (_u *ParamUpdateOne) ClearStepParams() *ParamUpdateOne {
	_u.mutation.ClearStepParams()
	return _u
}

// RemoveStepParamIDs removes the "step_params" edge to StepParam entities by IDs.
func (_u *ParamUpdateOne) RemoveStepParamIDs(ids ...uint64) *ParamUpdateOne {
	_u.mutation.RemoveStepParamIDs(ids...)
	return _u
}

// RemoveStepParams removes "step_params" edges to StepParam entities.
func (_u *ParamUpdateOne) RemoveStepParams(v ...*StepParam) *ParamUpdateOne {
	ids := make([]uint64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveStepParamIDs(ids...)
}

// Where appends a list predicates to the ParamUpdate builder.
func (_u *ParamUpdateOne) Where(ps ...predicate.Param) *ParamUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ParamUpdateOne) Select(field string, fields ...string) *ParamUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Param entity.
func (_u *ParamUpdateOne) Save(ctx context.Context) (*Param, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ParamUpdateOne) SaveX(ctx context.Context) *Param {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ParamUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ParamUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ParamUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok && !_u.mutation.UpdatedAtCleared() {
		v := param.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ParamUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := param.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`entv1: validator failed for field "Param.name": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *ParamUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *ParamUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *ParamUpdateOne) sqlSave(ctx context.Context) (_node *Param, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(param.Table, param.Columns, sqlgraph.NewFieldSpec(param.FieldID, field.TypeUint64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`entv1: missing "Param.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, param.FieldID)
		for _, f := range fields {
			if !param.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("entv1: invalid field %q for query", f)}
			}
			if f != param.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.CreatedAtCleared() {
		_spec.ClearField(param.FieldCreatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(param.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UpdatedAtCleared() {
		_spec.ClearField(param.FieldUpdatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(param.FieldCreatedBy, field.TypeString, value)
	}
	if _u.mutation.CreatedByCleared() {
		_spec.ClearField(param.FieldCreatedBy, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedBy(); ok {
		_spec.SetField(param.FieldUpdatedBy, field.TypeString, value)
	}
	if _u.mutation.UpdatedByCleared() {
		_spec.ClearField(param.FieldUpdatedBy, field.TypeString)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(param.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Value(); ok {
		_spec.SetField(param.FieldValue, field.TypeString, value)
	}
	if _u.mutation.ValueCleared() {
		_spec.ClearField(param.FieldValue, field.TypeString)
	}
	if _u.mutation.TasksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   param.TasksTable,
			Columns: param.TasksPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeUint64),
			},
		}
		createE := &TaskParamCreate{config: _u.config, mutation: newTaskParamMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedTasksIDs(); len(nodes) > 0 && !_u.mutation.TasksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   param.TasksTable,
			Columns: param.TasksPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeUint64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		createE := &TaskParamCreate{config: _u.config, mutation: newTaskParamMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TasksIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   param.TasksTable,
			Columns: param.TasksPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeUint64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		createE := &TaskParamCreate{config: _u.config, mutation: newTaskParamMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.StepsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   param.StepsTable,
			Columns: param.StepsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(step.FieldID, field.TypeUint64),
			},
		}
		createE := &StepParamCreate{config: _u.config, mutation: newStepParamMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedStepsIDs(); len(nodes) > 0 && !_u.mutation.StepsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   param.StepsTable,
			Columns: param.StepsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(step.FieldID, field.TypeUint64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		createE := &StepParamCreate{config: _u.config, mutation: newStepParamMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.StepsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   param.StepsTable,
			Columns: param.StepsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(step.FieldID, field.TypeUint64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		createE := &StepParamCreate{config: _u.config, mutation: newStepParamMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TaskParamsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   param.TaskParamsTable,
			Columns: []string{param.TaskParamsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(taskparam.FieldID, field.TypeUint64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedTaskParamsIDs(); len(nodes) > 0 && !_u.mutation.TaskParamsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   param.TaskParamsTable,
			Columns: []string{param.TaskParamsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(taskparam.FieldID, field.TypeUint64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TaskParamsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   param.TaskParamsTable,
			Columns: []string{param.TaskParamsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(taskparam.FieldID, field.TypeUint64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.StepParamsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   param.StepParamsTable,
			Columns: []string{param.StepParamsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(stepparam.FieldID, field.TypeUint64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedStepParamsIDs(); len(nodes) > 0 && !_u.mutation.StepParamsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   param.StepParamsTable,
			Columns: []string{param.StepParamsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(stepparam.FieldID, field.TypeUint64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.StepParamsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   param.StepParamsTable,
			Columns: []string{param.StepParamsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(stepparam.FieldID, field.TypeUint64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &Param{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{param.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
