// Code generated by ent, DO NOT EDIT.

package entv1

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/busyster996/dagflow/internal/entv1/param"
	"github.com/busyster996/dagflow/internal/entv1/predicate"
)

// ParamDelete is the builder for deleting a Param entity.
type ParamDelete struct {
	config
	hooks    []Hook
	mutation *ParamMutation
}

// Where appends a list predicates to the ParamDelete builder.
func (_d *ParamDelete) Where(ps ...predicate.Param) *ParamDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *ParamDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ParamDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *ParamDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(param.Table, sqlgraph.NewFieldSpec(param.FieldID, field.TypeUint64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// ParamDeleteOne is the builder for deleting a single Param entity.
type ParamDeleteOne struct {
	_d *ParamDelete
}

// Where appends a list predicates to the ParamDelete builder.
func (_d *ParamDeleteOne) Where(ps ...predicate.Param) *ParamDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *ParamDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{param.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ParamDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
