// Code generated by ent, DO NOT EDIT.

package entv1

func (_c *ParamCreate) SetParam(input *Param) *ParamCreate {
	if input.CreatedAt != nil {
		_c.SetCreatedAt(*input.CreatedAt)
	}
	if input.UpdatedAt != nil {
		_c.SetUpdatedAt(*input.UpdatedAt)
	}
	if input.CreatedBy != nil {
		_c.SetCreatedBy(*input.CreatedBy)
	}
	if input.UpdatedBy != nil {
		_c.SetUpdatedBy(*input.UpdatedBy)
	}
	_c.SetName(input.Name)
	if input.Value != nil {
		_c.SetValue(*input.Value)
	}
	return _c
}

func (_c *StepCreate) SetStep(input *Step) *StepCreate {
	if input.CreatedAt != nil {
		_c.SetCreatedAt(*input.CreatedAt)
	}
	if input.UpdatedAt != nil {
		_c.SetUpdatedAt(*input.UpdatedAt)
	}
	if input.CreatedBy != nil {
		_c.SetCreatedBy(*input.CreatedBy)
	}
	if input.UpdatedBy != nil {
		_c.SetUpdatedBy(*input.UpdatedBy)
	}
	_c.SetName(input.Name)
	if input.Desc != nil {
		_c.SetDesc(*input.Desc)
	}
	if input.Kind != nil {
		_c.SetKind(*input.Kind)
	}
	if input.Content != nil {
		_c.SetContent(*input.Content)
	}
	if input.Timeout != nil {
		_c.SetTimeout(*input.Timeout)
	}
	if input.Action != nil {
		_c.SetAction(*input.Action)
	}
	if input.Rule != nil {
		_c.SetRule(*input.Rule)
	}
	_c.SetRetryPolicy(input.RetryPolicy)
	_c.SetMetadata(input.Metadata)
	return _c
}

func (_c *StepDependCreate) SetStepDepend(input *StepDepend) *StepDependCreate {
	if input.CreatedAt != nil {
		_c.SetCreatedAt(*input.CreatedAt)
	}
	if input.UpdatedAt != nil {
		_c.SetUpdatedAt(*input.UpdatedAt)
	}
	if input.CreatedBy != nil {
		_c.SetCreatedBy(*input.CreatedBy)
	}
	if input.UpdatedBy != nil {
		_c.SetUpdatedBy(*input.UpdatedBy)
	}
	_c.SetStepID(input.StepID)
	_c.SetDependentID(input.DependentID)
	return _c
}

func (_c *StepParamCreate) SetStepParam(input *StepParam) *StepParamCreate {
	if input.CreatedAt != nil {
		_c.SetCreatedAt(*input.CreatedAt)
	}
	if input.UpdatedAt != nil {
		_c.SetUpdatedAt(*input.UpdatedAt)
	}
	if input.CreatedBy != nil {
		_c.SetCreatedBy(*input.CreatedBy)
	}
	if input.UpdatedBy != nil {
		_c.SetUpdatedBy(*input.UpdatedBy)
	}
	_c.SetStepID(input.StepID)
	_c.SetParamID(input.ParamID)
	return _c
}

func (_c *TaskCreate) SetTask(input *Task) *TaskCreate {
	if input.CreatedAt != nil {
		_c.SetCreatedAt(*input.CreatedAt)
	}
	if input.UpdatedAt != nil {
		_c.SetUpdatedAt(*input.UpdatedAt)
	}
	if input.CreatedBy != nil {
		_c.SetCreatedBy(*input.CreatedBy)
	}
	if input.UpdatedBy != nil {
		_c.SetUpdatedBy(*input.UpdatedBy)
	}
	if input.Disabled != nil {
		_c.SetDisabled(*input.Disabled)
	}
	if input.Message != nil {
		_c.SetMessage(*input.Message)
	}
	if input.State != nil {
		_c.SetState(*input.State)
	}
	if input.PreviousState != nil {
		_c.SetPreviousState(*input.PreviousState)
	}
	if input.StartTime != nil {
		_c.SetStartTime(*input.StartTime)
	}
	if input.EndTime != nil {
		_c.SetEndTime(*input.EndTime)
	}
	_c.SetName(input.Name)
	if input.Desc != nil {
		_c.SetDesc(*input.Desc)
	}
	if input.Kind != nil {
		_c.SetKind(*input.Kind)
	}
	if input.Node != nil {
		_c.SetNode(*input.Node)
	}
	if input.Timeout != nil {
		_c.SetTimeout(*input.Timeout)
	}
	_c.SetRetryPolicy(input.RetryPolicy)
	if input.IsTpl != nil {
		_c.SetIsTpl(*input.IsTpl)
	}
	return _c
}

func (_c *TaskParamCreate) SetTaskParam(input *TaskParam) *TaskParamCreate {
	if input.CreatedAt != nil {
		_c.SetCreatedAt(*input.CreatedAt)
	}
	if input.UpdatedAt != nil {
		_c.SetUpdatedAt(*input.UpdatedAt)
	}
	if input.CreatedBy != nil {
		_c.SetCreatedBy(*input.CreatedBy)
	}
	if input.UpdatedBy != nil {
		_c.SetUpdatedBy(*input.UpdatedBy)
	}
	_c.SetTaskID(input.TaskID)
	_c.SetParamID(input.ParamID)
	return _c
}

func (_c *TaskStepCreate) SetTaskStep(input *TaskStep) *TaskStepCreate {
	if input.CreatedAt != nil {
		_c.SetCreatedAt(*input.CreatedAt)
	}
	if input.UpdatedAt != nil {
		_c.SetUpdatedAt(*input.UpdatedAt)
	}
	if input.CreatedBy != nil {
		_c.SetCreatedBy(*input.CreatedBy)
	}
	if input.UpdatedBy != nil {
		_c.SetUpdatedBy(*input.UpdatedBy)
	}
	if input.Disabled != nil {
		_c.SetDisabled(*input.Disabled)
	}
	if input.Message != nil {
		_c.SetMessage(*input.Message)
	}
	if input.State != nil {
		_c.SetState(*input.State)
	}
	if input.PreviousState != nil {
		_c.SetPreviousState(*input.PreviousState)
	}
	if input.StartTime != nil {
		_c.SetStartTime(*input.StartTime)
	}
	if input.EndTime != nil {
		_c.SetEndTime(*input.EndTime)
	}
	_c.SetTaskID(input.TaskID)
	_c.SetStepID(input.StepID)
	if input.SeqNo != nil {
		_c.SetSeqNo(*input.SeqNo)
	}
	if input.Code != nil {
		_c.SetCode(*input.Code)
	}
	return _c
}

func (_c *TaskStepOutputCreate) SetTaskStepOutput(input *TaskStepOutput) *TaskStepOutputCreate {
	if input.CreatedAt != nil {
		_c.SetCreatedAt(*input.CreatedAt)
	}
	if input.UpdatedAt != nil {
		_c.SetUpdatedAt(*input.UpdatedAt)
	}
	if input.CreatedBy != nil {
		_c.SetCreatedBy(*input.CreatedBy)
	}
	if input.UpdatedBy != nil {
		_c.SetUpdatedBy(*input.UpdatedBy)
	}
	_c.SetExecID(input.ExecID)
	if input.Timestamp != nil {
		_c.SetTimestamp(*input.Timestamp)
	}
	if input.Content != nil {
		_c.SetContent(*input.Content)
	}
	return _c
}
