// Code generated by ent, DO NOT EDIT.

package entv1

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/busyster996/dagflow/internal/entv1/param"
	"github.com/busyster996/dagflow/internal/entv1/predicate"
	"github.com/busyster996/dagflow/internal/entv1/step"
	"github.com/busyster996/dagflow/internal/entv1/stepdepend"
	"github.com/busyster996/dagflow/internal/entv1/stepparam"
	"github.com/busyster996/dagflow/internal/entv1/task"
	"github.com/busyster996/dagflow/internal/entv1/taskstep"
)

// StepQuery is the builder for querying Step entities.
type StepQuery struct {
	config
	ctx                *QueryContext
	order              []step.OrderOption
	inters             []Interceptor
	predicates         []predicate.Step
	withTasks          *TaskQuery
	withParams         *ParamQuery
	withDependencies   *StepQuery
	withDependents     *StepQuery
	withTaskSteps      *TaskStepQuery
	withStepParams     *StepParamQuery
	withStepDepends    *StepDependQuery
	withStepDependents *StepDependQuery
	modifiers          []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the StepQuery builder.
func (_q *StepQuery) Where(ps ...predicate.Step) *StepQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *StepQuery) Limit(limit int) *StepQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *StepQuery) Offset(offset int) *StepQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *StepQuery) Unique(unique bool) *StepQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *StepQuery) Order(o ...step.OrderOption) *StepQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryTasks chains the current query on the "tasks" edge.
func (_q *StepQuery) QueryTasks() *TaskQuery {
	query := (&TaskClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(step.Table, step.FieldID, selector),
			sqlgraph.To(task.Table, task.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, step.TasksTable, step.TasksPrimaryKey...),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryParams chains the current query on the "params" edge.
func (_q *StepQuery) QueryParams() *ParamQuery {
	query := (&ParamClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(step.Table, step.FieldID, selector),
			sqlgraph.To(param.Table, param.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, step.ParamsTable, step.ParamsPrimaryKey...),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryDependencies chains the current query on the "dependencies" edge.
func (_q *StepQuery) QueryDependencies() *StepQuery {
	query := (&StepClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(step.Table, step.FieldID, selector),
			sqlgraph.To(step.Table, step.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, step.DependenciesTable, step.DependenciesPrimaryKey...),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryDependents chains the current query on the "dependents" edge.
func (_q *StepQuery) QueryDependents() *StepQuery {
	query := (&StepClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(step.Table, step.FieldID, selector),
			sqlgraph.To(step.Table, step.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, step.DependentsTable, step.DependentsPrimaryKey...),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryTaskSteps chains the current query on the "task_steps" edge.
func (_q *StepQuery) QueryTaskSteps() *TaskStepQuery {
	query := (&TaskStepClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(step.Table, step.FieldID, selector),
			sqlgraph.To(taskstep.Table, taskstep.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, true, step.TaskStepsTable, step.TaskStepsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryStepParams chains the current query on the "step_params" edge.
func (_q *StepQuery) QueryStepParams() *StepParamQuery {
	query := (&StepParamClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(step.Table, step.FieldID, selector),
			sqlgraph.To(stepparam.Table, stepparam.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, true, step.StepParamsTable, step.StepParamsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryStepDepends chains the current query on the "step_depends" edge.
func (_q *StepQuery) QueryStepDepends() *StepDependQuery {
	query := (&StepDependClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(step.Table, step.FieldID, selector),
			sqlgraph.To(stepdepend.Table, stepdepend.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, true, step.StepDependsTable, step.StepDependsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryStepDependents chains the current query on the "step_dependents" edge.
func (_q *StepQuery) QueryStepDependents() *StepDependQuery {
	query := (&StepDependClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(step.Table, step.FieldID, selector),
			sqlgraph.To(stepdepend.Table, stepdepend.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, true, step.StepDependentsTable, step.StepDependentsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Step entity from the query.
// Returns a *NotFoundError when no Step was found.
func (_q *StepQuery) First(ctx context.Context) (*Step, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{step.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *StepQuery) FirstX(ctx context.Context) *Step {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Step ID from the query.
// Returns a *NotFoundError when no Step ID was found.
func (_q *StepQuery) FirstID(ctx context.Context) (id uint64, err error) {
	var ids []uint64
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{step.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *StepQuery) FirstIDX(ctx context.Context) uint64 {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Step entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Step entity is found.
// Returns a *NotFoundError when no Step entities are found.
func (_q *StepQuery) Only(ctx context.Context) (*Step, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{step.Label}
	default:
		return nil, &NotSingularError{step.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *StepQuery) OnlyX(ctx context.Context) *Step {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Step ID in the query.
// Returns a *NotSingularError when more than one Step ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *StepQuery) OnlyID(ctx context.Context) (id uint64, err error) {
	var ids []uint64
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{step.Label}
	default:
		err = &NotSingularError{step.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *StepQuery) OnlyIDX(ctx context.Context) uint64 {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Steps.
func (_q *StepQuery) All(ctx context.Context) ([]*Step, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Step, *StepQuery]()
	return withInterceptors[[]*Step](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *StepQuery) AllX(ctx context.Context) []*Step {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Step IDs.
func (_q *StepQuery) IDs(ctx context.Context) (ids []uint64, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(step.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *StepQuery) IDsX(ctx context.Context) []uint64 {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *StepQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*StepQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *StepQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *StepQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("entv1: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *StepQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the StepQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *StepQuery) Clone() *StepQuery {
	if _q == nil {
		return nil
	}
	return &StepQuery{
		config:             _q.config,
		ctx:                _q.ctx.Clone(),
		order:              append([]step.OrderOption{}, _q.order...),
		inters:             append([]Interceptor{}, _q.inters...),
		predicates:         append([]predicate.Step{}, _q.predicates...),
		withTasks:          _q.withTasks.Clone(),
		withParams:         _q.withParams.Clone(),
		withDependencies:   _q.withDependencies.Clone(),
		withDependents:     _q.withDependents.Clone(),
		withTaskSteps:      _q.withTaskSteps.Clone(),
		withStepParams:     _q.withStepParams.Clone(),
		withStepDepends:    _q.withStepDepends.Clone(),
		withStepDependents: _q.withStepDependents.Clone(),
		// clone intermediate query.
		sql:       _q.sql.Clone(),
		path:      _q.path,
		modifiers: append([]func(*sql.Selector){}, _q.modifiers...),
	}
}

// WithTasks tells the query-builder to eager-load the nodes that are connected to
// the "tasks" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *StepQuery) WithTasks(opts ...func(*TaskQuery)) *StepQuery {
	query := (&TaskClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withTasks = query
	return _q
}

// WithParams tells the query-builder to eager-load the nodes that are connected to
// the "params" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *StepQuery) WithParams(opts ...func(*ParamQuery)) *StepQuery {
	query := (&ParamClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withParams = query
	return _q
}

// WithDependencies tells the query-builder to eager-load the nodes that are connected to
// the "dependencies" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *StepQuery) WithDependencies(opts ...func(*StepQuery)) *StepQuery {
	query := (&StepClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withDependencies = query
	return _q
}

// WithDependents tells the query-builder to eager-load the nodes that are connected to
// the "dependents" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *StepQuery) WithDependents(opts ...func(*StepQuery)) *StepQuery {
	query := (&StepClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withDependents = query
	return _q
}

// WithTaskSteps tells the query-builder to eager-load the nodes that are connected to
// the "task_steps" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *StepQuery) WithTaskSteps(opts ...func(*TaskStepQuery)) *StepQuery {
	query := (&TaskStepClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withTaskSteps = query
	return _q
}

// WithStepParams tells the query-builder to eager-load the nodes that are connected to
// the "step_params" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *StepQuery) WithStepParams(opts ...func(*StepParamQuery)) *StepQuery {
	query := (&StepParamClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withStepParams = query
	return _q
}

// WithStepDepends tells the query-builder to eager-load the nodes that are connected to
// the "step_depends" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *StepQuery) WithStepDepends(opts ...func(*StepDependQuery)) *StepQuery {
	query := (&StepDependClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withStepDepends = query
	return _q
}

// WithStepDependents tells the query-builder to eager-load the nodes that are connected to
// the "step_dependents" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *StepQuery) WithStepDependents(opts ...func(*StepDependQuery)) *StepQuery {
	query := (&StepDependClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withStepDependents = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Step.Query().
//		GroupBy(step.FieldCreatedAt).
//		Aggregate(entv1.Count()).
//		Scan(ctx, &v)
func (_q *StepQuery) GroupBy(field string, fields ...string) *StepGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &StepGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = step.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.Step.Query().
//		Select(step.FieldCreatedAt).
//		Scan(ctx, &v)
func (_q *StepQuery) Select(fields ...string) *StepSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &StepSelect{StepQuery: _q}
	sbuild.label = step.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a StepSelect configured with the given aggregations.
func (_q *StepQuery) Aggregate(fns ...AggregateFunc) *StepSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *StepQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("entv1: uninitialized interceptor (forgotten import entv1/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !step.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("entv1: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *StepQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Step, error) {
	var (
		nodes       = []*Step{}
		_spec       = _q.querySpec()
		loadedTypes = [8]bool{
			_q.withTasks != nil,
			_q.withParams != nil,
			_q.withDependencies != nil,
			_q.withDependents != nil,
			_q.withTaskSteps != nil,
			_q.withStepParams != nil,
			_q.withStepDepends != nil,
			_q.withStepDependents != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Step).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Step{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withTasks; query != nil {
		if err := _q.loadTasks(ctx, query, nodes,
			func(n *Step) { n.Edges.Tasks = []*Task{} },
			func(n *Step, e *Task) { n.Edges.Tasks = append(n.Edges.Tasks, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withParams; query != nil {
		if err := _q.loadParams(ctx, query, nodes,
			func(n *Step) { n.Edges.Params = []*Param{} },
			func(n *Step, e *Param) { n.Edges.Params = append(n.Edges.Params, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withDependencies; query != nil {
		if err := _q.loadDependencies(ctx, query, nodes,
			func(n *Step) { n.Edges.Dependencies = []*Step{} },
			func(n *Step, e *Step) { n.Edges.Dependencies = append(n.Edges.Dependencies, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withDependents; query != nil {
		if err := _q.loadDependents(ctx, query, nodes,
			func(n *Step) { n.Edges.Dependents = []*Step{} },
			func(n *Step, e *Step) { n.Edges.Dependents = append(n.Edges.Dependents, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withTaskSteps; query != nil {
		if err := _q.loadTaskSteps(ctx, query, nodes,
			func(n *Step) { n.Edges.TaskSteps = []*TaskStep{} },
			func(n *Step, e *TaskStep) { n.Edges.TaskSteps = append(n.Edges.TaskSteps, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withStepParams; query != nil {
		if err := _q.loadStepParams(ctx, query, nodes,
			func(n *Step) { n.Edges.StepParams = []*StepParam{} },
			func(n *Step, e *StepParam) { n.Edges.StepParams = append(n.Edges.StepParams, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withStepDepends; query != nil {
		if err := _q.loadStepDepends(ctx, query, nodes,
			func(n *Step) { n.Edges.StepDepends = []*StepDepend{} },
			func(n *Step, e *StepDepend) { n.Edges.StepDepends = append(n.Edges.StepDepends, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withStepDependents; query != nil {
		if err := _q.loadStepDependents(ctx, query, nodes,
			func(n *Step) { n.Edges.StepDependents = []*StepDepend{} },
			func(n *Step, e *StepDepend) { n.Edges.StepDependents = append(n.Edges.StepDependents, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *StepQuery) loadTasks(ctx context.Context, query *TaskQuery, nodes []*Step, init func(*Step), assign func(*Step, *Task)) error {
	edgeIDs := make([]driver.Value, len(nodes))
	byID := make(map[uint64]*Step)
	nids := make(map[uint64]map[*Step]struct{})
	for i, node := range nodes {
		edgeIDs[i] = node.ID
		byID[node.ID] = node
		if init != nil {
			init(node)
		}
	}
	query.Where(func(s *sql.Selector) {
		joinT := sql.Table(step.TasksTable)
		s.Join(joinT).On(s.C(task.FieldID), joinT.C(step.TasksPrimaryKey[0]))
		s.Where(sql.InValues(joinT.C(step.TasksPrimaryKey[1]), edgeIDs...))
		columns := s.SelectedColumns()
		s.Select(joinT.C(step.TasksPrimaryKey[1]))
		s.AppendSelect(columns...)
		s.SetDistinct(false)
	})
	if err := query.prepareQuery(ctx); err != nil {
		return err
	}
	qr := QuerierFunc(func(ctx context.Context, q Query) (Value, error) {
		return query.sqlAll(ctx, func(_ context.Context, spec *sqlgraph.QuerySpec) {
			assign := spec.Assign
			values := spec.ScanValues
			spec.ScanValues = func(columns []string) ([]any, error) {
				values, err := values(columns[1:])
				if err != nil {
					return nil, err
				}
				return append([]any{new(sql.NullInt64)}, values...), nil
			}
			spec.Assign = func(columns []string, values []any) error {
				outValue := uint64(values[0].(*sql.NullInt64).Int64)
				inValue := uint64(values[1].(*sql.NullInt64).Int64)
				if nids[inValue] == nil {
					nids[inValue] = map[*Step]struct{}{byID[outValue]: {}}
					return assign(columns[1:], values[1:])
				}
				nids[inValue][byID[outValue]] = struct{}{}
				return nil
			}
		})
	})
	neighbors, err := withInterceptors[[]*Task](ctx, query, qr, query.inters)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected "tasks" node returned %v`, n.ID)
		}
		for kn := range nodes {
			assign(kn, n)
		}
	}
	return nil
}
func (_q *StepQuery) loadParams(ctx context.Context, query *ParamQuery, nodes []*Step, init func(*Step), assign func(*Step, *Param)) error {
	edgeIDs := make([]driver.Value, len(nodes))
	byID := make(map[uint64]*Step)
	nids := make(map[uint64]map[*Step]struct{})
	for i, node := range nodes {
		edgeIDs[i] = node.ID
		byID[node.ID] = node
		if init != nil {
			init(node)
		}
	}
	query.Where(func(s *sql.Selector) {
		joinT := sql.Table(step.ParamsTable)
		s.Join(joinT).On(s.C(param.FieldID), joinT.C(step.ParamsPrimaryKey[1]))
		s.Where(sql.InValues(joinT.C(step.ParamsPrimaryKey[0]), edgeIDs...))
		columns := s.SelectedColumns()
		s.Select(joinT.C(step.ParamsPrimaryKey[0]))
		s.AppendSelect(columns...)
		s.SetDistinct(false)
	})
	if err := query.prepareQuery(ctx); err != nil {
		return err
	}
	qr := QuerierFunc(func(ctx context.Context, q Query) (Value, error) {
		return query.sqlAll(ctx, func(_ context.Context, spec *sqlgraph.QuerySpec) {
			assign := spec.Assign
			values := spec.ScanValues
			spec.ScanValues = func(columns []string) ([]any, error) {
				values, err := values(columns[1:])
				if err != nil {
					return nil, err
				}
				return append([]any{new(sql.NullInt64)}, values...), nil
			}
			spec.Assign = func(columns []string, values []any) error {
				outValue := uint64(values[0].(*sql.NullInt64).Int64)
				inValue := uint64(values[1].(*sql.NullInt64).Int64)
				if nids[inValue] == nil {
					nids[inValue] = map[*Step]struct{}{byID[outValue]: {}}
					return assign(columns[1:], values[1:])
				}
				nids[inValue][byID[outValue]] = struct{}{}
				return nil
			}
		})
	})
	neighbors, err := withInterceptors[[]*Param](ctx, query, qr, query.inters)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected "params" node returned %v`, n.ID)
		}
		for kn := range nodes {
			assign(kn, n)
		}
	}
	return nil
}
func (_q *StepQuery) loadDependencies(ctx context.Context, query *StepQuery, nodes []*Step, init func(*Step), assign func(*Step, *Step)) error {
	edgeIDs := make([]driver.Value, len(nodes))
	byID := make(map[uint64]*Step)
	nids := make(map[uint64]map[*Step]struct{})
	for i, node := range nodes {
		edgeIDs[i] = node.ID
		byID[node.ID] = node
		if init != nil {
			init(node)
		}
	}
	query.Where(func(s *sql.Selector) {
		joinT := sql.Table(step.DependenciesTable)
		s.Join(joinT).On(s.C(step.FieldID), joinT.C(step.DependenciesPrimaryKey[1]))
		s.Where(sql.InValues(joinT.C(step.DependenciesPrimaryKey[0]), edgeIDs...))
		columns := s.SelectedColumns()
		s.Select(joinT.C(step.DependenciesPrimaryKey[0]))
		s.AppendSelect(columns...)
		s.SetDistinct(false)
	})
	if err := query.prepareQuery(ctx); err != nil {
		return err
	}
	qr := QuerierFunc(func(ctx context.Context, q Query) (Value, error) {
		return query.sqlAll(ctx, func(_ context.Context, spec *sqlgraph.QuerySpec) {
			assign := spec.Assign
			values := spec.ScanValues
			spec.ScanValues = func(columns []string) ([]any, error) {
				values, err := values(columns[1:])
				if err != nil {
					return nil, err
				}
				return append([]any{new(sql.NullInt64)}, values...), nil
			}
			spec.Assign = func(columns []string, values []any) error {
				outValue := uint64(values[0].(*sql.NullInt64).Int64)
				inValue := uint64(values[1].(*sql.NullInt64).Int64)
				if nids[inValue] == nil {
					nids[inValue] = map[*Step]struct{}{byID[outValue]: {}}
					return assign(columns[1:], values[1:])
				}
				nids[inValue][byID[outValue]] = struct{}{}
				return nil
			}
		})
	})
	neighbors, err := withInterceptors[[]*Step](ctx, query, qr, query.inters)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected "dependencies" node returned %v`, n.ID)
		}
		for kn := range nodes {
			assign(kn, n)
		}
	}
	return nil
}
func (_q *StepQuery) loadDependents(ctx context.Context, query *StepQuery, nodes []*Step, init func(*Step), assign func(*Step, *Step)) error {
	edgeIDs := make([]driver.Value, len(nodes))
	byID := make(map[uint64]*Step)
	nids := make(map[uint64]map[*Step]struct{})
	for i, node := range nodes {
		edgeIDs[i] = node.ID
		byID[node.ID] = node
		if init != nil {
			init(node)
		}
	}
	query.Where(func(s *sql.Selector) {
		joinT := sql.Table(step.DependentsTable)
		s.Join(joinT).On(s.C(step.FieldID), joinT.C(step.DependentsPrimaryKey[0]))
		s.Where(sql.InValues(joinT.C(step.DependentsPrimaryKey[1]), edgeIDs...))
		columns := s.SelectedColumns()
		s.Select(joinT.C(step.DependentsPrimaryKey[1]))
		s.AppendSelect(columns...)
		s.SetDistinct(false)
	})
	if err := query.prepareQuery(ctx); err != nil {
		return err
	}
	qr := QuerierFunc(func(ctx context.Context, q Query) (Value, error) {
		return query.sqlAll(ctx, func(_ context.Context, spec *sqlgraph.QuerySpec) {
			assign := spec.Assign
			values := spec.ScanValues
			spec.ScanValues = func(columns []string) ([]any, error) {
				values, err := values(columns[1:])
				if err != nil {
					return nil, err
				}
				return append([]any{new(sql.NullInt64)}, values...), nil
			}
			spec.Assign = func(columns []string, values []any) error {
				outValue := uint64(values[0].(*sql.NullInt64).Int64)
				inValue := uint64(values[1].(*sql.NullInt64).Int64)
				if nids[inValue] == nil {
					nids[inValue] = map[*Step]struct{}{byID[outValue]: {}}
					return assign(columns[1:], values[1:])
				}
				nids[inValue][byID[outValue]] = struct{}{}
				return nil
			}
		})
	})
	neighbors, err := withInterceptors[[]*Step](ctx, query, qr, query.inters)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected "dependents" node returned %v`, n.ID)
		}
		for kn := range nodes {
			assign(kn, n)
		}
	}
	return nil
}
func (_q *StepQuery) loadTaskSteps(ctx context.Context, query *TaskStepQuery, nodes []*Step, init func(*Step), assign func(*Step, *TaskStep)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uint64]*Step)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(taskstep.FieldStepID)
	}
	query.Where(predicate.TaskStep(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(step.TaskStepsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.StepID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "step_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *StepQuery) loadStepParams(ctx context.Context, query *StepParamQuery, nodes []*Step, init func(*Step), assign func(*Step, *StepParam)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uint64]*Step)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(stepparam.FieldStepID)
	}
	query.Where(predicate.StepParam(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(step.StepParamsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.StepID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "step_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *StepQuery) loadStepDepends(ctx context.Context, query *StepDependQuery, nodes []*Step, init func(*Step), assign func(*Step, *StepDepend)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uint64]*Step)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(stepdepend.FieldStepID)
	}
	query.Where(predicate.StepDepend(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(step.StepDependsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.StepID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "step_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *StepQuery) loadStepDependents(ctx context.Context, query *StepDependQuery, nodes []*Step, init func(*Step), assign func(*Step, *StepDepend)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uint64]*Step)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(stepdepend.FieldDependentID)
	}
	query.Where(predicate.StepDepend(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(step.StepDependentsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.DependentID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "dependent_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (_q *StepQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *StepQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(step.Table, step.Columns, sqlgraph.NewFieldSpec(step.FieldID, field.TypeUint64))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, step.FieldID)
		for i := range fields {
			if fields[i] != step.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *StepQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(step.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = step.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range _q.modifiers {
		m(selector)
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ForUpdate locks the selected rows against concurrent updates, and prevent them from being
// updated, deleted or "selected ... for update" by other sessions, until the transaction is
// either committed or rolled-back.
func (_q *StepQuery) ForUpdate(opts ...sql.LockOption) *StepQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForUpdate(opts...)
	})
	return _q
}

// ForShare behaves similarly to ForUpdate, except that it acquires a shared mode lock
// on any rows that are read. Other sessions can read the rows, but cannot modify them
// until your transaction commits.
func (_q *StepQuery) ForShare(opts ...sql.LockOption) *StepQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForShare(opts...)
	})
	return _q
}

// Modify adds a query modifier for attaching custom logic to queries.
func (_q *StepQuery) Modify(modifiers ...func(s *sql.Selector)) *StepSelect {
	_q.modifiers = append(_q.modifiers, modifiers...)
	return _q.Select()
}

// StepGroupBy is the group-by builder for Step entities.
type StepGroupBy struct {
	selector
	build *StepQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *StepGroupBy) Aggregate(fns ...AggregateFunc) *StepGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *StepGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*StepQuery, *StepGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *StepGroupBy) sqlScan(ctx context.Context, root *StepQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// StepSelect is the builder for selecting fields of Step entities.
type StepSelect struct {
	*StepQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *StepSelect) Aggregate(fns ...AggregateFunc) *StepSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *StepSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*StepQuery, *StepSelect](ctx, _s.StepQuery, _s, _s.inters, v)
}

func (_s *StepSelect) sqlScan(ctx context.Context, root *StepQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (_s *StepSelect) Modify(modifiers ...func(s *sql.Selector)) *StepSelect {
	_s.modifiers = append(_s.modifiers, modifiers...)
	return _s
}
