// Code generated by ent, DO NOT EDIT.

package entv1

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/busyster996/dagflow/internal/entv1/schema"
	"github.com/busyster996/dagflow/internal/entv1/step"
)

// Step is the model entity for the Step schema.
type Step struct {
	config `json:"-"`
	// ID of the ent.
	ID uint64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt *time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
	// CreatedBy holds the value of the "created_by" field.
	CreatedBy *string `json:"created_by,omitempty"`
	// UpdatedBy holds the value of the "updated_by" field.
	UpdatedBy *string `json:"updated_by,omitempty"`
	// 名称
	Name string `json:"name,omitempty"`
	// 描述
	Desc *string `json:"desc,omitempty"`
	// 类型
	Kind *string `json:"kind,omitempty"`
	// 内容
	Content *string `json:"content,omitempty"`
	// 超时时间(毫秒)
	Timeout *int64 `json:"timeout,omitempty"`
	// 动作
	Action *string `json:"action,omitempty"`
	// 规则
	Rule *string `json:"rule,omitempty"`
	// 重试策略
	RetryPolicy *schema.RetryPolicy `json:"retry_policy,omitempty"`
	// 元数据
	Metadata map[string]interface{} `json:"metadata,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the StepQuery when eager-loading is set.
	Edges        StepEdges `json:"edges"`
	selectValues sql.SelectValues
}

// StepEdges holds the relations/edges for other nodes in the graph.
type StepEdges struct {
	// Tasks holds the value of the tasks edge.
	Tasks []*Task `json:"tasks,omitempty"`
	// Params holds the value of the params edge.
	Params []*Param `json:"params,omitempty"`
	// Dependencies holds the value of the dependencies edge.
	Dependencies []*Step `json:"dependencies,omitempty"`
	// Dependents holds the value of the dependents edge.
	Dependents []*Step `json:"dependents,omitempty"`
	// TaskSteps holds the value of the task_steps edge.
	TaskSteps []*TaskStep `json:"task_steps,omitempty"`
	// StepParams holds the value of the step_params edge.
	StepParams []*StepParam `json:"step_params,omitempty"`
	// StepDepends holds the value of the step_depends edge.
	StepDepends []*StepDepend `json:"step_depends,omitempty"`
	// StepDependents holds the value of the step_dependents edge.
	StepDependents []*StepDepend `json:"step_dependents,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [8]bool
}

// TasksOrErr returns the Tasks value or an error if the edge
// was not loaded in eager-loading.
func (e StepEdges) TasksOrErr() ([]*Task, error) {
	if e.loadedTypes[0] {
		return e.Tasks, nil
	}
	return nil, &NotLoadedError{edge: "tasks"}
}

// ParamsOrErr returns the Params value or an error if the edge
// was not loaded in eager-loading.
func (e StepEdges) ParamsOrErr() ([]*Param, error) {
	if e.loadedTypes[1] {
		return e.Params, nil
	}
	return nil, &NotLoadedError{edge: "params"}
}

// DependenciesOrErr returns the Dependencies value or an error if the edge
// was not loaded in eager-loading.
func (e StepEdges) DependenciesOrErr() ([]*Step, error) {
	if e.loadedTypes[2] {
		return e.Dependencies, nil
	}
	return nil, &NotLoadedError{edge: "dependencies"}
}

// DependentsOrErr returns the Dependents value or an error if the edge
// was not loaded in eager-loading.
func (e StepEdges) DependentsOrErr() ([]*Step, error) {
	if e.loadedTypes[3] {
		return e.Dependents, nil
	}
	return nil, &NotLoadedError{edge: "dependents"}
}

// TaskStepsOrErr returns the TaskSteps value or an error if the edge
// was not loaded in eager-loading.
func (e StepEdges) TaskStepsOrErr() ([]*TaskStep, error) {
	if e.loadedTypes[4] {
		return e.TaskSteps, nil
	}
	return nil, &NotLoadedError{edge: "task_steps"}
}

// StepParamsOrErr returns the StepParams value or an error if the edge
// was not loaded in eager-loading.
func (e StepEdges) StepParamsOrErr() ([]*StepParam, error) {
	if e.loadedTypes[5] {
		return e.StepParams, nil
	}
	return nil, &NotLoadedError{edge: "step_params"}
}

// StepDependsOrErr returns the StepDepends value or an error if the edge
// was not loaded in eager-loading.
func (e StepEdges) StepDependsOrErr() ([]*StepDepend, error) {
	if e.loadedTypes[6] {
		return e.StepDepends, nil
	}
	return nil, &NotLoadedError{edge: "step_depends"}
}

// StepDependentsOrErr returns the StepDependents value or an error if the edge
// was not loaded in eager-loading.
func (e StepEdges) StepDependentsOrErr() ([]*StepDepend, error) {
	if e.loadedTypes[7] {
		return e.StepDependents, nil
	}
	return nil, &NotLoadedError{edge: "step_dependents"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Step) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case step.FieldRetryPolicy, step.FieldMetadata:
			values[i] = new([]byte)
		case step.FieldID, step.FieldTimeout:
			values[i] = new(sql.NullInt64)
		case step.FieldCreatedBy, step.FieldUpdatedBy, step.FieldName, step.FieldDesc, step.FieldKind, step.FieldContent, step.FieldAction, step.FieldRule:
			values[i] = new(sql.NullString)
		case step.FieldCreatedAt, step.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Step fields.
func (_m *Step) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case step.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = uint64(value.Int64)
		case step.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = new(time.Time)
				*_m.CreatedAt = value.Time
			}
		case step.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = new(time.Time)
				*_m.UpdatedAt = value.Time
			}
		case step.FieldCreatedBy:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field created_by", values[i])
			} else if value.Valid {
				_m.CreatedBy = new(string)
				*_m.CreatedBy = value.String
			}
		case step.FieldUpdatedBy:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field updated_by", values[i])
			} else if value.Valid {
				_m.UpdatedBy = new(string)
				*_m.UpdatedBy = value.String
			}
		case step.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case step.FieldDesc:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field desc", values[i])
			} else if value.Valid {
				_m.Desc = new(string)
				*_m.Desc = value.String
			}
		case step.FieldKind:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field kind", values[i])
			} else if value.Valid {
				_m.Kind = new(string)
				*_m.Kind = value.String
			}
		case step.FieldContent:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field content", values[i])
			} else if value.Valid {
				_m.Content = new(string)
				*_m.Content = value.String
			}
		case step.FieldTimeout:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field timeout", values[i])
			} else if value.Valid {
				_m.Timeout = new(int64)
				*_m.Timeout = value.Int64
			}
		case step.FieldAction:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field action", values[i])
			} else if value.Valid {
				_m.Action = new(string)
				*_m.Action = value.String
			}
		case step.FieldRule:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field rule", values[i])
			} else if value.Valid {
				_m.Rule = new(string)
				*_m.Rule = value.String
			}
		case step.FieldRetryPolicy:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field retry_policy", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.RetryPolicy); err != nil {
					return fmt.Errorf("unmarshal field retry_policy: %w", err)
				}
			}
		case step.FieldMetadata:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field metadata", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Metadata); err != nil {
					return fmt.Errorf("unmarshal field metadata: %w", err)
				}
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Step.
// This includes values selected through modifiers, order, etc.
func (_m *Step) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryTasks queries the "tasks" edge of the Step entity.
func (_m *Step) QueryTasks() *TaskQuery {
	return NewStepClient(_m.config).QueryTasks(_m)
}

// QueryParams queries the "params" edge of the Step entity.
func (_m *Step) QueryParams() *ParamQuery {
	return NewStepClient(_m.config).QueryParams(_m)
}

// QueryDependencies queries the "dependencies" edge of the Step entity.
func (_m *Step) QueryDependencies() *StepQuery {
	return NewStepClient(_m.config).QueryDependencies(_m)
}

// QueryDependents queries the "dependents" edge of the Step entity.
func (_m *Step) QueryDependents() *StepQuery {
	return NewStepClient(_m.config).QueryDependents(_m)
}

// QueryTaskSteps queries the "task_steps" edge of the Step entity.
func (_m *Step) QueryTaskSteps() *TaskStepQuery {
	return NewStepClient(_m.config).QueryTaskSteps(_m)
}

// QueryStepParams queries the "step_params" edge of the Step entity.
func (_m *Step) QueryStepParams() *StepParamQuery {
	return NewStepClient(_m.config).QueryStepParams(_m)
}

// QueryStepDepends queries the "step_depends" edge of the Step entity.
func (_m *Step) QueryStepDepends() *StepDependQuery {
	return NewStepClient(_m.config).QueryStepDepends(_m)
}

// QueryStepDependents queries the "step_dependents" edge of the Step entity.
func (_m *Step) QueryStepDependents() *StepDependQuery {
	return NewStepClient(_m.config).QueryStepDependents(_m)
}

// Update returns a builder for updating this Step.
// Note that you need to call Step.Unwrap() before calling this method if this Step
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Step) Update() *StepUpdateOne {
	return NewStepClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Step entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Step) Unwrap() *Step {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("entv1: Step is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Step) String() string {
	var builder strings.Builder
	builder.WriteString("Step(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	if v := _m.CreatedAt; v != nil {
		builder.WriteString("created_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.UpdatedAt; v != nil {
		builder.WriteString("updated_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.CreatedBy; v != nil {
		builder.WriteString("created_by=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.UpdatedBy; v != nil {
		builder.WriteString("updated_by=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	if v := _m.Desc; v != nil {
		builder.WriteString("desc=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.Kind; v != nil {
		builder.WriteString("kind=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.Content; v != nil {
		builder.WriteString("content=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.Timeout; v != nil {
		builder.WriteString("timeout=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.Action; v != nil {
		builder.WriteString("action=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.Rule; v != nil {
		builder.WriteString("rule=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("retry_policy=")
	builder.WriteString(fmt.Sprintf("%v", _m.RetryPolicy))
	builder.WriteString(", ")
	builder.WriteString("metadata=")
	builder.WriteString(fmt.Sprintf("%v", _m.Metadata))
	builder.WriteByte(')')
	return builder.String()
}

// Steps is a parsable slice of Step.
type Steps []*Step
