// Code generated by ent, DO NOT EDIT.

package entv1

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/busyster996/dagflow/internal/entv1/step"
	"github.com/busyster996/dagflow/internal/entv1/task"
	"github.com/busyster996/dagflow/internal/entv1/taskstep"
	"github.com/busyster996/dagflow/internal/entv1/taskstepoutput"
)

// TaskStepCreate is the builder for creating a TaskStep entity.
type TaskStepCreate struct {
	config
	mutation *TaskStepMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *TaskStepCreate) SetCreatedAt(v time.Time) *TaskStepCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *TaskStepCreate) SetNillableCreatedAt(v *time.Time) *TaskStepCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *TaskStepCreate) SetUpdatedAt(v time.Time) *TaskStepCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *TaskStepCreate) SetNillableUpdatedAt(v *time.Time) *TaskStepCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetCreatedBy sets the "created_by" field.
func (_c *TaskStepCreate) SetCreatedBy(v string) *TaskStepCreate {
	_c.mutation.SetCreatedBy(v)
	return _c
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_c *TaskStepCreate) SetNillableCreatedBy(v *string) *TaskStepCreate {
	if v != nil {
		_c.SetCreatedBy(*v)
	}
	return _c
}

// SetUpdatedBy sets the "updated_by" field.
func (_c *TaskStepCreate) SetUpdatedBy(v string) *TaskStepCreate {
	_c.mutation.SetUpdatedBy(v)
	return _c
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_c *TaskStepCreate) SetNillableUpdatedBy(v *string) *TaskStepCreate {
	if v != nil {
		_c.SetUpdatedBy(*v)
	}
	return _c
}

// SetDisabled sets the "disabled" field.
func (_c *TaskStepCreate) SetDisabled(v bool) *TaskStepCreate {
	_c.mutation.SetDisabled(v)
	return _c
}

// SetNillableDisabled sets the "disabled" field if the given value is not nil.
func (_c *TaskStepCreate) SetNillableDisabled(v *bool) *TaskStepCreate {
	if v != nil {
		_c.SetDisabled(*v)
	}
	return _c
}

// SetMessage sets the "message" field.
func (_c *TaskStepCreate) SetMessage(v string) *TaskStepCreate {
	_c.mutation.SetMessage(v)
	return _c
}

// SetNillableMessage sets the "message" field if the given value is not nil.
func (_c *TaskStepCreate) SetNillableMessage(v *string) *TaskStepCreate {
	if v != nil {
		_c.SetMessage(*v)
	}
	return _c
}

// SetState sets the "state" field.
func (_c *TaskStepCreate) SetState(v taskstep.State) *TaskStepCreate {
	_c.mutation.SetState(v)
	return _c
}

// SetNillableState sets the "state" field if the given value is not nil.
func (_c *TaskStepCreate) SetNillableState(v *taskstep.State) *TaskStepCreate {
	if v != nil {
		_c.SetState(*v)
	}
	return _c
}

// SetPreviousState sets the "previous_state" field.
func (_c *TaskStepCreate) SetPreviousState(v taskstep.PreviousState) *TaskStepCreate {
	_c.mutation.SetPreviousState(v)
	return _c
}

// SetNillablePreviousState sets the "previous_state" field if the given value is not nil.
func (_c *TaskStepCreate) SetNillablePreviousState(v *taskstep.PreviousState) *TaskStepCreate {
	if v != nil {
		_c.SetPreviousState(*v)
	}
	return _c
}

// SetStartTime sets the "start_time" field.
func (_c *TaskStepCreate) SetStartTime(v time.Time) *TaskStepCreate {
	_c.mutation.SetStartTime(v)
	return _c
}

// SetNillableStartTime sets the "start_time" field if the given value is not nil.
func (_c *TaskStepCreate) SetNillableStartTime(v *time.Time) *TaskStepCreate {
	if v != nil {
		_c.SetStartTime(*v)
	}
	return _c
}

// SetEndTime sets the "end_time" field.
func (_c *TaskStepCreate) SetEndTime(v time.Time) *TaskStepCreate {
	_c.mutation.SetEndTime(v)
	return _c
}

// SetNillableEndTime sets the "end_time" field if the given value is not nil.
func (_c *TaskStepCreate) SetNillableEndTime(v *time.Time) *TaskStepCreate {
	if v != nil {
		_c.SetEndTime(*v)
	}
	return _c
}

// SetTaskID sets the "task_id" field.
func (_c *TaskStepCreate) SetTaskID(v uint64) *TaskStepCreate {
	_c.mutation.SetTaskID(v)
	return _c
}

// SetStepID sets the "step_id" field.
func (_c *TaskStepCreate) SetStepID(v uint64) *TaskStepCreate {
	_c.mutation.SetStepID(v)
	return _c
}

// SetSeqNo sets the "seq_no" field.
func (_c *TaskStepCreate) SetSeqNo(v int64) *TaskStepCreate {
	_c.mutation.SetSeqNo(v)
	return _c
}

// SetNillableSeqNo sets the "seq_no" field if the given value is not nil.
func (_c *TaskStepCreate) SetNillableSeqNo(v *int64) *TaskStepCreate {
	if v != nil {
		_c.SetSeqNo(*v)
	}
	return _c
}

// SetCode sets the "code" field.
func (_c *TaskStepCreate) SetCode(v int64) *TaskStepCreate {
	_c.mutation.SetCode(v)
	return _c
}

// SetNillableCode sets the "code" field if the given value is not nil.
func (_c *TaskStepCreate) SetNillableCode(v *int64) *TaskStepCreate {
	if v != nil {
		_c.SetCode(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *TaskStepCreate) SetID(v uint64) *TaskStepCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetTask sets the "task" edge to the Task entity.
func (_c *TaskStepCreate) SetTask(v *Task) *TaskStepCreate {
	return _c.SetTaskID(v.ID)
}

// SetStep sets the "step" edge to the Step entity.
func (_c *TaskStepCreate) SetStep(v *Step) *TaskStepCreate {
	return _c.SetStepID(v.ID)
}

// AddOutputIDs adds the "outputs" edge to the TaskStepOutput entity by IDs.
func (_c *TaskStepCreate) AddOutputIDs(ids ...uint64) *TaskStepCreate {
	_c.mutation.AddOutputIDs(ids...)
	return _c
}

// AddOutputs adds the "outputs" edges to the TaskStepOutput entity.
func (_c *TaskStepCreate) AddOutputs(v ...*TaskStepOutput) *TaskStepCreate {
	ids := make([]uint64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddOutputIDs(ids...)
}

// Mutation returns the TaskStepMutation object of the builder.
func (_c *TaskStepCreate) Mutation() *TaskStepMutation {
	return _c.mutation
}

// Save creates the TaskStep in the database.
func (_c *TaskStepCreate) Save(ctx context.Context) (*TaskStep, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *TaskStepCreate) SaveX(ctx context.Context) *TaskStep {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TaskStepCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TaskStepCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *TaskStepCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := taskstep.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := taskstep.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Disabled(); !ok {
		v := taskstep.DefaultDisabled
		_c.mutation.SetDisabled(v)
	}
	if _, ok := _c.mutation.State(); !ok {
		v := taskstep.DefaultState
		_c.mutation.SetState(v)
	}
	if _, ok := _c.mutation.PreviousState(); !ok {
		v := taskstep.DefaultPreviousState
		_c.mutation.SetPreviousState(v)
	}
	if _, ok := _c.mutation.SeqNo(); !ok {
		v := taskstep.DefaultSeqNo
		_c.mutation.SetSeqNo(v)
	}
	if _, ok := _c.mutation.Code(); !ok {
		v := taskstep.DefaultCode
		_c.mutation.SetCode(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *TaskStepCreate) check() error {
	if v, ok := _c.mutation.State(); ok {
		if err := taskstep.StateValidator(v); err != nil {
			return &ValidationError{Name: "state", err: fmt.Errorf(`entv1: validator failed for field "TaskStep.state": %w`, err)}
		}
	}
	if v, ok := _c.mutation.PreviousState(); ok {
		if err := taskstep.PreviousStateValidator(v); err != nil {
			return &ValidationError{Name: "previous_state", err: fmt.Errorf(`entv1: validator failed for field "TaskStep.previous_state": %w`, err)}
		}
	}
	if _, ok := _c.mutation.TaskID(); !ok {
		return &ValidationError{Name: "task_id", err: errors.New(`entv1: missing required field "TaskStep.task_id"`)}
	}
	if _, ok := _c.mutation.StepID(); !ok {
		return &ValidationError{Name: "step_id", err: errors.New(`entv1: missing required field "TaskStep.step_id"`)}
	}
	if len(_c.mutation.TaskIDs()) == 0 {
		return &ValidationError{Name: "task", err: errors.New(`entv1: missing required edge "TaskStep.task"`)}
	}
	if len(_c.mutation.StepIDs()) == 0 {
		return &ValidationError{Name: "step", err: errors.New(`entv1: missing required edge "TaskStep.step"`)}
	}
	return nil
}

func (_c *TaskStepCreate) sqlSave(ctx context.Context) (*TaskStep, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = uint64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *TaskStepCreate) createSpec() (*TaskStep, *sqlgraph.CreateSpec) {
	var (
		_node = &TaskStep{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(taskstep.Table, sqlgraph.NewFieldSpec(taskstep.FieldID, field.TypeUint64))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(taskstep.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = &value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(taskstep.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = &value
	}
	if value, ok := _c.mutation.CreatedBy(); ok {
		_spec.SetField(taskstep.FieldCreatedBy, field.TypeString, value)
		_node.CreatedBy = &value
	}
	if value, ok := _c.mutation.UpdatedBy(); ok {
		_spec.SetField(taskstep.FieldUpdatedBy, field.TypeString, value)
		_node.UpdatedBy = &value
	}
	if value, ok := _c.mutation.Disabled(); ok {
		_spec.SetField(taskstep.FieldDisabled, field.TypeBool, value)
		_node.Disabled = &value
	}
	if value, ok := _c.mutation.Message(); ok {
		_spec.SetField(taskstep.FieldMessage, field.TypeString, value)
		_node.Message = &value
	}
	if value, ok := _c.mutation.State(); ok {
		_spec.SetField(taskstep.FieldState, field.TypeEnum, value)
		_node.State = &value
	}
	if value, ok := _c.mutation.PreviousState(); ok {
		_spec.SetField(taskstep.FieldPreviousState, field.TypeEnum, value)
		_node.PreviousState = &value
	}
	if value, ok := _c.mutation.StartTime(); ok {
		_spec.SetField(taskstep.FieldStartTime, field.TypeTime, value)
		_node.StartTime = &value
	}
	if value, ok := _c.mutation.EndTime(); ok {
		_spec.SetField(taskstep.FieldEndTime, field.TypeTime, value)
		_node.EndTime = &value
	}
	if value, ok := _c.mutation.SeqNo(); ok {
		_spec.SetField(taskstep.FieldSeqNo, field.TypeInt64, value)
		_node.SeqNo = &value
	}
	if value, ok := _c.mutation.Code(); ok {
		_spec.SetField(taskstep.FieldCode, field.TypeInt64, value)
		_node.Code = &value
	}
	if nodes := _c.mutation.TaskIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   taskstep.TaskTable,
			Columns: []string{taskstep.TaskColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeUint64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.TaskID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.StepIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   taskstep.StepTable,
			Columns: []string{taskstep.StepColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(step.FieldID, field.TypeUint64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.StepID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.OutputsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   taskstep.OutputsTable,
			Columns: []string{taskstep.OutputsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(taskstepoutput.FieldID, field.TypeUint64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.TaskStep.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.TaskStepUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *TaskStepCreate) OnConflict(opts ...sql.ConflictOption) *TaskStepUpsertOne {
	_c.conflict = opts
	return &TaskStepUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.TaskStep.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *TaskStepCreate) OnConflictColumns(columns ...string) *TaskStepUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &TaskStepUpsertOne{
		create: _c,
	}
}

type (
	// TaskStepUpsertOne is the builder for "upsert"-ing
	//  one TaskStep node.
	TaskStepUpsertOne struct {
		create *TaskStepCreate
	}

	// TaskStepUpsert is the "OnConflict" setter.
	TaskStepUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *TaskStepUpsert) SetUpdatedAt(v time.Time) *TaskStepUpsert {
	u.Set(taskstep.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *TaskStepUpsert) UpdateUpdatedAt() *TaskStepUpsert {
	u.SetExcluded(taskstep.FieldUpdatedAt)
	return u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (u *TaskStepUpsert) ClearUpdatedAt() *TaskStepUpsert {
	u.SetNull(taskstep.FieldUpdatedAt)
	return u
}

// SetCreatedBy sets the "created_by" field.
func (u *TaskStepUpsert) SetCreatedBy(v string) *TaskStepUpsert {
	u.Set(taskstep.FieldCreatedBy, v)
	return u
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *TaskStepUpsert) UpdateCreatedBy() *TaskStepUpsert {
	u.SetExcluded(taskstep.FieldCreatedBy)
	return u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (u *TaskStepUpsert) ClearCreatedBy() *TaskStepUpsert {
	u.SetNull(taskstep.FieldCreatedBy)
	return u
}

// SetUpdatedBy sets the "updated_by" field.
func (u *TaskStepUpsert) SetUpdatedBy(v string) *TaskStepUpsert {
	u.Set(taskstep.FieldUpdatedBy, v)
	return u
}

// UpdateUpdatedBy sets the "updated_by" field to the value that was provided on create.
func (u *TaskStepUpsert) UpdateUpdatedBy() *TaskStepUpsert {
	u.SetExcluded(taskstep.FieldUpdatedBy)
	return u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (u *TaskStepUpsert) ClearUpdatedBy() *TaskStepUpsert {
	u.SetNull(taskstep.FieldUpdatedBy)
	return u
}

// SetDisabled sets the "disabled" field.
func (u *TaskStepUpsert) SetDisabled(v bool) *TaskStepUpsert {
	u.Set(taskstep.FieldDisabled, v)
	return u
}

// UpdateDisabled sets the "disabled" field to the value that was provided on create.
func (u *TaskStepUpsert) UpdateDisabled() *TaskStepUpsert {
	u.SetExcluded(taskstep.FieldDisabled)
	return u
}

// ClearDisabled clears the value of the "disabled" field.
func (u *TaskStepUpsert) ClearDisabled() *TaskStepUpsert {
	u.SetNull(taskstep.FieldDisabled)
	return u
}

// SetMessage sets the "message" field.
func (u *TaskStepUpsert) SetMessage(v string) *TaskStepUpsert {
	u.Set(taskstep.FieldMessage, v)
	return u
}

// UpdateMessage sets the "message" field to the value that was provided on create.
func (u *TaskStepUpsert) UpdateMessage() *TaskStepUpsert {
	u.SetExcluded(taskstep.FieldMessage)
	return u
}

// ClearMessage clears the value of the "message" field.
func (u *TaskStepUpsert) ClearMessage() *TaskStepUpsert {
	u.SetNull(taskstep.FieldMessage)
	return u
}

// SetState sets the "state" field.
func (u *TaskStepUpsert) SetState(v taskstep.State) *TaskStepUpsert {
	u.Set(taskstep.FieldState, v)
	return u
}

// UpdateState sets the "state" field to the value that was provided on create.
func (u *TaskStepUpsert) UpdateState() *TaskStepUpsert {
	u.SetExcluded(taskstep.FieldState)
	return u
}

// ClearState clears the value of the "state" field.
func (u *TaskStepUpsert) ClearState() *TaskStepUpsert {
	u.SetNull(taskstep.FieldState)
	return u
}

// SetPreviousState sets the "previous_state" field.
func (u *TaskStepUpsert) SetPreviousState(v taskstep.PreviousState) *TaskStepUpsert {
	u.Set(taskstep.FieldPreviousState, v)
	return u
}

// UpdatePreviousState sets the "previous_state" field to the value that was provided on create.
func (u *TaskStepUpsert) UpdatePreviousState() *TaskStepUpsert {
	u.SetExcluded(taskstep.FieldPreviousState)
	return u
}

// ClearPreviousState clears the value of the "previous_state" field.
func (u *TaskStepUpsert) ClearPreviousState() *TaskStepUpsert {
	u.SetNull(taskstep.FieldPreviousState)
	return u
}

// SetStartTime sets the "start_time" field.
func (u *TaskStepUpsert) SetStartTime(v time.Time) *TaskStepUpsert {
	u.Set(taskstep.FieldStartTime, v)
	return u
}

// UpdateStartTime sets the "start_time" field to the value that was provided on create.
func (u *TaskStepUpsert) UpdateStartTime() *TaskStepUpsert {
	u.SetExcluded(taskstep.FieldStartTime)
	return u
}

// ClearStartTime clears the value of the "start_time" field.
func (u *TaskStepUpsert) ClearStartTime() *TaskStepUpsert {
	u.SetNull(taskstep.FieldStartTime)
	return u
}

// SetEndTime sets the "end_time" field.
func (u *TaskStepUpsert) SetEndTime(v time.Time) *TaskStepUpsert {
	u.Set(taskstep.FieldEndTime, v)
	return u
}

// UpdateEndTime sets the "end_time" field to the value that was provided on create.
func (u *TaskStepUpsert) UpdateEndTime() *TaskStepUpsert {
	u.SetExcluded(taskstep.FieldEndTime)
	return u
}

// ClearEndTime clears the value of the "end_time" field.
func (u *TaskStepUpsert) ClearEndTime() *TaskStepUpsert {
	u.SetNull(taskstep.FieldEndTime)
	return u
}

// SetTaskID sets the "task_id" field.
func (u *TaskStepUpsert) SetTaskID(v uint64) *TaskStepUpsert {
	u.Set(taskstep.FieldTaskID, v)
	return u
}

// UpdateTaskID sets the "task_id" field to the value that was provided on create.
func (u *TaskStepUpsert) UpdateTaskID() *TaskStepUpsert {
	u.SetExcluded(taskstep.FieldTaskID)
	return u
}

// SetStepID sets the "step_id" field.
func (u *TaskStepUpsert) SetStepID(v uint64) *TaskStepUpsert {
	u.Set(taskstep.FieldStepID, v)
	return u
}

// UpdateStepID sets the "step_id" field to the value that was provided on create.
func (u *TaskStepUpsert) UpdateStepID() *TaskStepUpsert {
	u.SetExcluded(taskstep.FieldStepID)
	return u
}

// SetSeqNo sets the "seq_no" field.
func (u *TaskStepUpsert) SetSeqNo(v int64) *TaskStepUpsert {
	u.Set(taskstep.FieldSeqNo, v)
	return u
}

// UpdateSeqNo sets the "seq_no" field to the value that was provided on create.
func (u *TaskStepUpsert) UpdateSeqNo() *TaskStepUpsert {
	u.SetExcluded(taskstep.FieldSeqNo)
	return u
}

// AddSeqNo adds v to the "seq_no" field.
func (u *TaskStepUpsert) AddSeqNo(v int64) *TaskStepUpsert {
	u.Add(taskstep.FieldSeqNo, v)
	return u
}

// ClearSeqNo clears the value of the "seq_no" field.
func (u *TaskStepUpsert) ClearSeqNo() *TaskStepUpsert {
	u.SetNull(taskstep.FieldSeqNo)
	return u
}

// SetCode sets the "code" field.
func (u *TaskStepUpsert) SetCode(v int64) *TaskStepUpsert {
	u.Set(taskstep.FieldCode, v)
	return u
}

// UpdateCode sets the "code" field to the value that was provided on create.
func (u *TaskStepUpsert) UpdateCode() *TaskStepUpsert {
	u.SetExcluded(taskstep.FieldCode)
	return u
}

// AddCode adds v to the "code" field.
func (u *TaskStepUpsert) AddCode(v int64) *TaskStepUpsert {
	u.Add(taskstep.FieldCode, v)
	return u
}

// ClearCode clears the value of the "code" field.
func (u *TaskStepUpsert) ClearCode() *TaskStepUpsert {
	u.SetNull(taskstep.FieldCode)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.TaskStep.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(taskstep.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *TaskStepUpsertOne) UpdateNewValues() *TaskStepUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(taskstep.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(taskstep.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.TaskStep.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *TaskStepUpsertOne) Ignore() *TaskStepUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *TaskStepUpsertOne) DoNothing() *TaskStepUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the TaskStepCreate.OnConflict
// documentation for more info.
func (u *TaskStepUpsertOne) Update(set func(*TaskStepUpsert)) *TaskStepUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&TaskStepUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *TaskStepUpsertOne) SetUpdatedAt(v time.Time) *TaskStepUpsertOne {
	return u.Update(func(s *TaskStepUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *TaskStepUpsertOne) UpdateUpdatedAt() *TaskStepUpsertOne {
	return u.Update(func(s *TaskStepUpsert) {
		s.UpdateUpdatedAt()
	})
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (u *TaskStepUpsertOne) ClearUpdatedAt() *TaskStepUpsertOne {
	return u.Update(func(s *TaskStepUpsert) {
		s.ClearUpdatedAt()
	})
}

// SetCreatedBy sets the "created_by" field.
func (u *TaskStepUpsertOne) SetCreatedBy(v string) *TaskStepUpsertOne {
	return u.Update(func(s *TaskStepUpsert) {
		s.SetCreatedBy(v)
	})
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *TaskStepUpsertOne) UpdateCreatedBy() *TaskStepUpsertOne {
	return u.Update(func(s *TaskStepUpsert) {
		s.UpdateCreatedBy()
	})
}

// ClearCreatedBy clears the value of the "created_by" field.
func (u *TaskStepUpsertOne) ClearCreatedBy() *TaskStepUpsertOne {
	return u.Update(func(s *TaskStepUpsert) {
		s.ClearCreatedBy()
	})
}

// SetUpdatedBy sets the "updated_by" field.
func (u *TaskStepUpsertOne) SetUpdatedBy(v string) *TaskStepUpsertOne {
	return u.Update(func(s *TaskStepUpsert) {
		s.SetUpdatedBy(v)
	})
}

// UpdateUpdatedBy sets the "updated_by" field to the value that was provided on create.
func (u *TaskStepUpsertOne) UpdateUpdatedBy() *TaskStepUpsertOne {
	return u.Update(func(s *TaskStepUpsert) {
		s.UpdateUpdatedBy()
	})
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (u *TaskStepUpsertOne) ClearUpdatedBy() *TaskStepUpsertOne {
	return u.Update(func(s *TaskStepUpsert) {
		s.ClearUpdatedBy()
	})
}

// SetDisabled sets the "disabled" field.
func (u *TaskStepUpsertOne) SetDisabled(v bool) *TaskStepUpsertOne {
	return u.Update(func(s *TaskStepUpsert) {
		s.SetDisabled(v)
	})
}

// UpdateDisabled sets the "disabled" field to the value that was provided on create.
func (u *TaskStepUpsertOne) UpdateDisabled() *TaskStepUpsertOne {
	return u.Update(func(s *TaskStepUpsert) {
		s.UpdateDisabled()
	})
}

// ClearDisabled clears the value of the "disabled" field.
func (u *TaskStepUpsertOne) ClearDisabled() *TaskStepUpsertOne {
	return u.Update(func(s *TaskStepUpsert) {
		s.ClearDisabled()
	})
}

// SetMessage sets the "message" field.
func (u *TaskStepUpsertOne) SetMessage(v string) *TaskStepUpsertOne {
	return u.Update(func(s *TaskStepUpsert) {
		s.SetMessage(v)
	})
}

// UpdateMessage sets the "message" field to the value that was provided on create.
func (u *TaskStepUpsertOne) UpdateMessage() *TaskStepUpsertOne {
	return u.Update(func(s *TaskStepUpsert) {
		s.UpdateMessage()
	})
}

// ClearMessage clears the value of the "message" field.
func (u *TaskStepUpsertOne) ClearMessage() *TaskStepUpsertOne {
	return u.Update(func(s *TaskStepUpsert) {
		s.ClearMessage()
	})
}

// SetState sets the "state" field.
func (u *TaskStepUpsertOne) SetState(v taskstep.State) *TaskStepUpsertOne {
	return u.Update(func(s *TaskStepUpsert) {
		s.SetState(v)
	})
}

// UpdateState sets the "state" field to the value that was provided on create.
func (u *TaskStepUpsertOne) UpdateState() *TaskStepUpsertOne {
	return u.Update(func(s *TaskStepUpsert) {
		s.UpdateState()
	})
}

// ClearState clears the value of the "state" field.
func (u *TaskStepUpsertOne) ClearState() *TaskStepUpsertOne {
	return u.Update(func(s *TaskStepUpsert) {
		s.ClearState()
	})
}

// SetPreviousState sets the "previous_state" field.
func (u *TaskStepUpsertOne) SetPreviousState(v taskstep.PreviousState) *TaskStepUpsertOne {
	return u.Update(func(s *TaskStepUpsert) {
		s.SetPreviousState(v)
	})
}

// UpdatePreviousState sets the "previous_state" field to the value that was provided on create.
func (u *TaskStepUpsertOne) UpdatePreviousState() *TaskStepUpsertOne {
	return u.Update(func(s *TaskStepUpsert) {
		s.UpdatePreviousState()
	})
}

// ClearPreviousState clears the value of the "previous_state" field.
func (u *TaskStepUpsertOne) ClearPreviousState() *TaskStepUpsertOne {
	return u.Update(func(s *TaskStepUpsert) {
		s.ClearPreviousState()
	})
}

// SetStartTime sets the "start_time" field.
func (u *TaskStepUpsertOne) SetStartTime(v time.Time) *TaskStepUpsertOne {
	return u.Update(func(s *TaskStepUpsert) {
		s.SetStartTime(v)
	})
}

// UpdateStartTime sets the "start_time" field to the value that was provided on create.
func (u *TaskStepUpsertOne) UpdateStartTime() *TaskStepUpsertOne {
	return u.Update(func(s *TaskStepUpsert) {
		s.UpdateStartTime()
	})
}

// ClearStartTime clears the value of the "start_time" field.
func (u *TaskStepUpsertOne) ClearStartTime() *TaskStepUpsertOne {
	return u.Update(func(s *TaskStepUpsert) {
		s.ClearStartTime()
	})
}

// SetEndTime sets the "end_time" field.
func (u *TaskStepUpsertOne) SetEndTime(v time.Time) *TaskStepUpsertOne {
	return u.Update(func(s *TaskStepUpsert) {
		s.SetEndTime(v)
	})
}

// UpdateEndTime sets the "end_time" field to the value that was provided on create.
func (u *TaskStepUpsertOne) UpdateEndTime() *TaskStepUpsertOne {
	return u.Update(func(s *TaskStepUpsert) {
		s.UpdateEndTime()
	})
}

// ClearEndTime clears the value of the "end_time" field.
func (u *TaskStepUpsertOne) ClearEndTime() *TaskStepUpsertOne {
	return u.Update(func(s *TaskStepUpsert) {
		s.ClearEndTime()
	})
}

// SetTaskID sets the "task_id" field.
func (u *TaskStepUpsertOne) SetTaskID(v uint64) *TaskStepUpsertOne {
	return u.Update(func(s *TaskStepUpsert) {
		s.SetTaskID(v)
	})
}

// UpdateTaskID sets the "task_id" field to the value that was provided on create.
func (u *TaskStepUpsertOne) UpdateTaskID() *TaskStepUpsertOne {
	return u.Update(func(s *TaskStepUpsert) {
		s.UpdateTaskID()
	})
}

// SetStepID sets the "step_id" field.
func (u *TaskStepUpsertOne) SetStepID(v uint64) *TaskStepUpsertOne {
	return u.Update(func(s *TaskStepUpsert) {
		s.SetStepID(v)
	})
}

// UpdateStepID sets the "step_id" field to the value that was provided on create.
func (u *TaskStepUpsertOne) UpdateStepID() *TaskStepUpsertOne {
	return u.Update(func(s *TaskStepUpsert) {
		s.UpdateStepID()
	})
}

// SetSeqNo sets the "seq_no" field.
func (u *TaskStepUpsertOne) SetSeqNo(v int64) *TaskStepUpsertOne {
	return u.Update(func(s *TaskStepUpsert) {
		s.SetSeqNo(v)
	})
}

// AddSeqNo adds v to the "seq_no" field.
func (u *TaskStepUpsertOne) AddSeqNo(v int64) *TaskStepUpsertOne {
	return u.Update(func(s *TaskStepUpsert) {
		s.AddSeqNo(v)
	})
}

// UpdateSeqNo sets the "seq_no" field to the value that was provided on create.
func (u *TaskStepUpsertOne) UpdateSeqNo() *TaskStepUpsertOne {
	return u.Update(func(s *TaskStepUpsert) {
		s.UpdateSeqNo()
	})
}

// ClearSeqNo clears the value of the "seq_no" field.
func (u *TaskStepUpsertOne) ClearSeqNo() *TaskStepUpsertOne {
	return u.Update(func(s *TaskStepUpsert) {
		s.ClearSeqNo()
	})
}

// SetCode sets the "code" field.
func (u *TaskStepUpsertOne) SetCode(v int64) *TaskStepUpsertOne {
	return u.Update(func(s *TaskStepUpsert) {
		s.SetCode(v)
	})
}

// AddCode adds v to the "code" field.
func (u *TaskStepUpsertOne) AddCode(v int64) *TaskStepUpsertOne {
	return u.Update(func(s *TaskStepUpsert) {
		s.AddCode(v)
	})
}

// UpdateCode sets the "code" field to the value that was provided on create.
func (u *TaskStepUpsertOne) UpdateCode() *TaskStepUpsertOne {
	return u.Update(func(s *TaskStepUpsert) {
		s.UpdateCode()
	})
}

// ClearCode clears the value of the "code" field.
func (u *TaskStepUpsertOne) ClearCode() *TaskStepUpsertOne {
	return u.Update(func(s *TaskStepUpsert) {
		s.ClearCode()
	})
}

// Exec executes the query.
func (u *TaskStepUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("entv1: missing options for TaskStepCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *TaskStepUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *TaskStepUpsertOne) ID(ctx context.Context) (id uint64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *TaskStepUpsertOne) IDX(ctx context.Context) uint64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// TaskStepCreateBulk is the builder for creating many TaskStep entities in bulk.
type TaskStepCreateBulk struct {
	config
	err      error
	builders []*TaskStepCreate
	conflict []sql.ConflictOption
}

// Save creates the TaskStep entities in the database.
func (_c *TaskStepCreateBulk) Save(ctx context.Context) ([]*TaskStep, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*TaskStep, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TaskStepMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = uint64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *TaskStepCreateBulk) SaveX(ctx context.Context) []*TaskStep {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TaskStepCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TaskStepCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.TaskStep.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.TaskStepUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *TaskStepCreateBulk) OnConflict(opts ...sql.ConflictOption) *TaskStepUpsertBulk {
	_c.conflict = opts
	return &TaskStepUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.TaskStep.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *TaskStepCreateBulk) OnConflictColumns(columns ...string) *TaskStepUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &TaskStepUpsertBulk{
		create: _c,
	}
}

// TaskStepUpsertBulk is the builder for "upsert"-ing
// a bulk of TaskStep nodes.
type TaskStepUpsertBulk struct {
	create *TaskStepCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.TaskStep.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(taskstep.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *TaskStepUpsertBulk) UpdateNewValues() *TaskStepUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(taskstep.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(taskstep.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.TaskStep.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *TaskStepUpsertBulk) Ignore() *TaskStepUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *TaskStepUpsertBulk) DoNothing() *TaskStepUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the TaskStepCreateBulk.OnConflict
// documentation for more info.
func (u *TaskStepUpsertBulk) Update(set func(*TaskStepUpsert)) *TaskStepUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&TaskStepUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *TaskStepUpsertBulk) SetUpdatedAt(v time.Time) *TaskStepUpsertBulk {
	return u.Update(func(s *TaskStepUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *TaskStepUpsertBulk) UpdateUpdatedAt() *TaskStepUpsertBulk {
	return u.Update(func(s *TaskStepUpsert) {
		s.UpdateUpdatedAt()
	})
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (u *TaskStepUpsertBulk) ClearUpdatedAt() *TaskStepUpsertBulk {
	return u.Update(func(s *TaskStepUpsert) {
		s.ClearUpdatedAt()
	})
}

// SetCreatedBy sets the "created_by" field.
func (u *TaskStepUpsertBulk) SetCreatedBy(v string) *TaskStepUpsertBulk {
	return u.Update(func(s *TaskStepUpsert) {
		s.SetCreatedBy(v)
	})
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *TaskStepUpsertBulk) UpdateCreatedBy() *TaskStepUpsertBulk {
	return u.Update(func(s *TaskStepUpsert) {
		s.UpdateCreatedBy()
	})
}

// ClearCreatedBy clears the value of the "created_by" field.
func (u *TaskStepUpsertBulk) ClearCreatedBy() *TaskStepUpsertBulk {
	return u.Update(func(s *TaskStepUpsert) {
		s.ClearCreatedBy()
	})
}

// SetUpdatedBy sets the "updated_by" field.
func (u *TaskStepUpsertBulk) SetUpdatedBy(v string) *TaskStepUpsertBulk {
	return u.Update(func(s *TaskStepUpsert) {
		s.SetUpdatedBy(v)
	})
}

// UpdateUpdatedBy sets the "updated_by" field to the value that was provided on create.
func (u *TaskStepUpsertBulk) UpdateUpdatedBy() *TaskStepUpsertBulk {
	return u.Update(func(s *TaskStepUpsert) {
		s.UpdateUpdatedBy()
	})
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (u *TaskStepUpsertBulk) ClearUpdatedBy() *TaskStepUpsertBulk {
	return u.Update(func(s *TaskStepUpsert) {
		s.ClearUpdatedBy()
	})
}

// SetDisabled sets the "disabled" field.
func (u *TaskStepUpsertBulk) SetDisabled(v bool) *TaskStepUpsertBulk {
	return u.Update(func(s *TaskStepUpsert) {
		s.SetDisabled(v)
	})
}

// UpdateDisabled sets the "disabled" field to the value that was provided on create.
func (u *TaskStepUpsertBulk) UpdateDisabled() *TaskStepUpsertBulk {
	return u.Update(func(s *TaskStepUpsert) {
		s.UpdateDisabled()
	})
}

// ClearDisabled clears the value of the "disabled" field.
func (u *TaskStepUpsertBulk) ClearDisabled() *TaskStepUpsertBulk {
	return u.Update(func(s *TaskStepUpsert) {
		s.ClearDisabled()
	})
}

// SetMessage sets the "message" field.
func (u *TaskStepUpsertBulk) SetMessage(v string) *TaskStepUpsertBulk {
	return u.Update(func(s *TaskStepUpsert) {
		s.SetMessage(v)
	})
}

// UpdateMessage sets the "message" field to the value that was provided on create.
func (u *TaskStepUpsertBulk) UpdateMessage() *TaskStepUpsertBulk {
	return u.Update(func(s *TaskStepUpsert) {
		s.UpdateMessage()
	})
}

// ClearMessage clears the value of the "message" field.
func (u *TaskStepUpsertBulk) ClearMessage() *TaskStepUpsertBulk {
	return u.Update(func(s *TaskStepUpsert) {
		s.ClearMessage()
	})
}

// SetState sets the "state" field.
func (u *TaskStepUpsertBulk) SetState(v taskstep.State) *TaskStepUpsertBulk {
	return u.Update(func(s *TaskStepUpsert) {
		s.SetState(v)
	})
}

// UpdateState sets the "state" field to the value that was provided on create.
func (u *TaskStepUpsertBulk) UpdateState() *TaskStepUpsertBulk {
	return u.Update(func(s *TaskStepUpsert) {
		s.UpdateState()
	})
}

// ClearState clears the value of the "state" field.
func (u *TaskStepUpsertBulk) ClearState() *TaskStepUpsertBulk {
	return u.Update(func(s *TaskStepUpsert) {
		s.ClearState()
	})
}

// SetPreviousState sets the "previous_state" field.
func (u *TaskStepUpsertBulk) SetPreviousState(v taskstep.PreviousState) *TaskStepUpsertBulk {
	return u.Update(func(s *TaskStepUpsert) {
		s.SetPreviousState(v)
	})
}

// UpdatePreviousState sets the "previous_state" field to the value that was provided on create.
func (u *TaskStepUpsertBulk) UpdatePreviousState() *TaskStepUpsertBulk {
	return u.Update(func(s *TaskStepUpsert) {
		s.UpdatePreviousState()
	})
}

// ClearPreviousState clears the value of the "previous_state" field.
func (u *TaskStepUpsertBulk) ClearPreviousState() *TaskStepUpsertBulk {
	return u.Update(func(s *TaskStepUpsert) {
		s.ClearPreviousState()
	})
}

// SetStartTime sets the "start_time" field.
func (u *TaskStepUpsertBulk) SetStartTime(v time.Time) *TaskStepUpsertBulk {
	return u.Update(func(s *TaskStepUpsert) {
		s.SetStartTime(v)
	})
}

// UpdateStartTime sets the "start_time" field to the value that was provided on create.
func (u *TaskStepUpsertBulk) UpdateStartTime() *TaskStepUpsertBulk {
	return u.Update(func(s *TaskStepUpsert) {
		s.UpdateStartTime()
	})
}

// ClearStartTime clears the value of the "start_time" field.
func (u *TaskStepUpsertBulk) ClearStartTime() *TaskStepUpsertBulk {
	return u.Update(func(s *TaskStepUpsert) {
		s.ClearStartTime()
	})
}

// SetEndTime sets the "end_time" field.
func (u *TaskStepUpsertBulk) SetEndTime(v time.Time) *TaskStepUpsertBulk {
	return u.Update(func(s *TaskStepUpsert) {
		s.SetEndTime(v)
	})
}

// UpdateEndTime sets the "end_time" field to the value that was provided on create.
func (u *TaskStepUpsertBulk) UpdateEndTime() *TaskStepUpsertBulk {
	return u.Update(func(s *TaskStepUpsert) {
		s.UpdateEndTime()
	})
}

// ClearEndTime clears the value of the "end_time" field.
func (u *TaskStepUpsertBulk) ClearEndTime() *TaskStepUpsertBulk {
	return u.Update(func(s *TaskStepUpsert) {
		s.ClearEndTime()
	})
}

// SetTaskID sets the "task_id" field.
func (u *TaskStepUpsertBulk) SetTaskID(v uint64) *TaskStepUpsertBulk {
	return u.Update(func(s *TaskStepUpsert) {
		s.SetTaskID(v)
	})
}

// UpdateTaskID sets the "task_id" field to the value that was provided on create.
func (u *TaskStepUpsertBulk) UpdateTaskID() *TaskStepUpsertBulk {
	return u.Update(func(s *TaskStepUpsert) {
		s.UpdateTaskID()
	})
}

// SetStepID sets the "step_id" field.
func (u *TaskStepUpsertBulk) SetStepID(v uint64) *TaskStepUpsertBulk {
	return u.Update(func(s *TaskStepUpsert) {
		s.SetStepID(v)
	})
}

// UpdateStepID sets the "step_id" field to the value that was provided on create.
func (u *TaskStepUpsertBulk) UpdateStepID() *TaskStepUpsertBulk {
	return u.Update(func(s *TaskStepUpsert) {
		s.UpdateStepID()
	})
}

// SetSeqNo sets the "seq_no" field.
func (u *TaskStepUpsertBulk) SetSeqNo(v int64) *TaskStepUpsertBulk {
	return u.Update(func(s *TaskStepUpsert) {
		s.SetSeqNo(v)
	})
}

// AddSeqNo adds v to the "seq_no" field.
func (u *TaskStepUpsertBulk) AddSeqNo(v int64) *TaskStepUpsertBulk {
	return u.Update(func(s *TaskStepUpsert) {
		s.AddSeqNo(v)
	})
}

// UpdateSeqNo sets the "seq_no" field to the value that was provided on create.
func (u *TaskStepUpsertBulk) UpdateSeqNo() *TaskStepUpsertBulk {
	return u.Update(func(s *TaskStepUpsert) {
		s.UpdateSeqNo()
	})
}

// ClearSeqNo clears the value of the "seq_no" field.
func (u *TaskStepUpsertBulk) ClearSeqNo() *TaskStepUpsertBulk {
	return u.Update(func(s *TaskStepUpsert) {
		s.ClearSeqNo()
	})
}

// SetCode sets the "code" field.
func (u *TaskStepUpsertBulk) SetCode(v int64) *TaskStepUpsertBulk {
	return u.Update(func(s *TaskStepUpsert) {
		s.SetCode(v)
	})
}

// AddCode adds v to the "code" field.
func (u *TaskStepUpsertBulk) AddCode(v int64) *TaskStepUpsertBulk {
	return u.Update(func(s *TaskStepUpsert) {
		s.AddCode(v)
	})
}

// UpdateCode sets the "code" field to the value that was provided on create.
func (u *TaskStepUpsertBulk) UpdateCode() *TaskStepUpsertBulk {
	return u.Update(func(s *TaskStepUpsert) {
		s.UpdateCode()
	})
}

// ClearCode clears the value of the "code" field.
func (u *TaskStepUpsertBulk) ClearCode() *TaskStepUpsertBulk {
	return u.Update(func(s *TaskStepUpsert) {
		s.ClearCode()
	})
}

// Exec executes the query.
func (u *TaskStepUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("entv1: OnConflict was set for builder %d. Set it on the TaskStepCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("entv1: missing options for TaskStepCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *TaskStepUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
