// Code generated by ent, DO NOT EDIT.

package entv1

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/busyster996/dagflow/internal/entv1/param"
	"github.com/busyster996/dagflow/internal/entv1/predicate"
	"github.com/busyster996/dagflow/internal/entv1/schema"
	"github.com/busyster996/dagflow/internal/entv1/step"
	"github.com/busyster996/dagflow/internal/entv1/task"
	"github.com/busyster996/dagflow/internal/entv1/taskparam"
	"github.com/busyster996/dagflow/internal/entv1/taskstep"
)

// TaskUpdate is the builder for updating Task entities.
type TaskUpdate struct {
	config
	hooks     []Hook
	mutation  *TaskMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the TaskUpdate builder.
func (_u *TaskUpdate) Where(ps ...predicate.Task) *TaskUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *TaskUpdate) SetUpdatedAt(v time.Time) *TaskUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (_u *TaskUpdate) ClearUpdatedAt() *TaskUpdate {
	_u.mutation.ClearUpdatedAt()
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *TaskUpdate) SetCreatedBy(v string) *TaskUpdate {
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *TaskUpdate) SetNillableCreatedBy(v *string) *TaskUpdate {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (_u *TaskUpdate) ClearCreatedBy() *TaskUpdate {
	_u.mutation.ClearCreatedBy()
	return _u
}

// SetUpdatedBy sets the "updated_by" field.
func (_u *TaskUpdate) SetUpdatedBy(v string) *TaskUpdate {
	_u.mutation.SetUpdatedBy(v)
	return _u
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_u *TaskUpdate) SetNillableUpdatedBy(v *string) *TaskUpdate {
	if v != nil {
		_u.SetUpdatedBy(*v)
	}
	return _u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (_u *TaskUpdate) ClearUpdatedBy() *TaskUpdate {
	_u.mutation.ClearUpdatedBy()
	return _u
}

// SetDisabled sets the "disabled" field.
func (_u *TaskUpdate) SetDisabled(v bool) *TaskUpdate {
	_u.mutation.SetDisabled(v)
	return _u
}

// SetNillableDisabled sets the "disabled" field if the given value is not nil.
func (_u *TaskUpdate) SetNillableDisabled(v *bool) *TaskUpdate {
	if v != nil {
		_u.SetDisabled(*v)
	}
	return _u
}

// ClearDisabled clears the value of the "disabled" field.
func (_u *TaskUpdate) ClearDisabled() *TaskUpdate {
	_u.mutation.ClearDisabled()
	return _u
}

// SetMessage sets the "message" field.
func (_u *TaskUpdate) SetMessage(v string) *TaskUpdate {
	_u.mutation.SetMessage(v)
	return _u
}

// SetNillableMessage sets the "message" field if the given value is not nil.
func (_u *TaskUpdate) SetNillableMessage(v *string) *TaskUpdate {
	if v != nil {
		_u.SetMessage(*v)
	}
	return _u
}

// ClearMessage clears the value of the "message" field.
func (_u *TaskUpdate) ClearMessage() *TaskUpdate {
	_u.mutation.ClearMessage()
	return _u
}

// SetState sets the "state" field.
func (_u *TaskUpdate) SetState(v task.State) *TaskUpdate {
	_u.mutation.SetState(v)
	return _u
}

// SetNillableState sets the "state" field if the given value is not nil.
func (_u *TaskUpdate) SetNillableState(v *task.State) *TaskUpdate {
	if v != nil {
		_u.SetState(*v)
	}
	return _u
}

// ClearState clears the value of the "state" field.
func (_u *TaskUpdate) ClearState() *TaskUpdate {
	_u.mutation.ClearState()
	return _u
}

// SetPreviousState sets the "previous_state" field.
func (_u *TaskUpdate) SetPreviousState(v task.PreviousState) *TaskUpdate {
	_u.mutation.SetPreviousState(v)
	return _u
}

// SetNillablePreviousState sets the "previous_state" field if the given value is not nil.
func (_u *TaskUpdate) SetNillablePreviousState(v *task.PreviousState) *TaskUpdate {
	if v != nil {
		_u.SetPreviousState(*v)
	}
	return _u
}

// ClearPreviousState clears the value of the "previous_state" field.
func (_u *TaskUpdate) ClearPreviousState() *TaskUpdate {
	_u.mutation.ClearPreviousState()
	return _u
}

// SetStartTime sets the "start_time" field.
func (_u *TaskUpdate) SetStartTime(v time.Time) *TaskUpdate {
	_u.mutation.SetStartTime(v)
	return _u
}

// SetNillableStartTime sets the "start_time" field if the given value is not nil.
func (_u *TaskUpdate) SetNillableStartTime(v *time.Time) *TaskUpdate {
	if v != nil {
		_u.SetStartTime(*v)
	}
	return _u
}

// ClearStartTime clears the value of the "start_time" field.
func (_u *TaskUpdate) ClearStartTime() *TaskUpdate {
	_u.mutation.ClearStartTime()
	return _u
}

// SetEndTime sets the "end_time" field.
func (_u *TaskUpdate) SetEndTime(v time.Time) *TaskUpdate {
	_u.mutation.SetEndTime(v)
	return _u
}

// SetNillableEndTime sets the "end_time" field if the given value is not nil.
func (_u *TaskUpdate) SetNillableEndTime(v *time.Time) *TaskUpdate {
	if v != nil {
		_u.SetEndTime(*v)
	}
	return _u
}

// ClearEndTime clears the value of the "end_time" field.
func (_u *TaskUpdate) ClearEndTime() *TaskUpdate {
	_u.mutation.ClearEndTime()
	return _u
}

// SetName sets the "name" field.
func (_u *TaskUpdate) SetName(v string) *TaskUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *TaskUpdate) SetNillableName(v *string) *TaskUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDesc sets the "desc" field.
func (_u *TaskUpdate) SetDesc(v string) *TaskUpdate {
	_u.mutation.SetDesc(v)
	return _u
}

// SetNillableDesc sets the "desc" field if the given value is not nil.
func (_u *TaskUpdate) SetNillableDesc(v *string) *TaskUpdate {
	if v != nil {
		_u.SetDesc(*v)
	}
	return _u
}

// ClearDesc clears the value of the "desc" field.
func (_u *TaskUpdate) ClearDesc() *TaskUpdate {
	_u.mutation.ClearDesc()
	return _u
}

// SetKind sets the "kind" field.
func (_u *TaskUpdate) SetKind(v string) *TaskUpdate {
	_u.mutation.SetKind(v)
	return _u
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (_u *TaskUpdate) SetNillableKind(v *string) *TaskUpdate {
	if v != nil {
		_u.SetKind(*v)
	}
	return _u
}

// ClearKind clears the value of the "kind" field.
func (_u *TaskUpdate) ClearKind() *TaskUpdate {
	_u.mutation.ClearKind()
	return _u
}

// SetNode sets the "node" field.
func (_u *TaskUpdate) SetNode(v string) *TaskUpdate {
	_u.mutation.SetNode(v)
	return _u
}

// SetNillableNode sets the "node" field if the given value is not nil.
func (_u *TaskUpdate) SetNillableNode(v *string) *TaskUpdate {
	if v != nil {
		_u.SetNode(*v)
	}
	return _u
}

// ClearNode clears the value of the "node" field.
func (_u *TaskUpdate) ClearNode() *TaskUpdate {
	_u.mutation.ClearNode()
	return _u
}

// SetTimeout sets the "timeout" field.
func (_u *TaskUpdate) SetTimeout(v int64) *TaskUpdate {
	_u.mutation.ResetTimeout()
	_u.mutation.SetTimeout(v)
	return _u
}

// SetNillableTimeout sets the "timeout" field if the given value is not nil.
func (_u *TaskUpdate) SetNillableTimeout(v *int64) *TaskUpdate {
	if v != nil {
		_u.SetTimeout(*v)
	}
	return _u
}

// AddTimeout adds value to the "timeout" field.
func (_u *TaskUpdate) AddTimeout(v int64) *TaskUpdate {
	_u.mutation.AddTimeout(v)
	return _u
}

// ClearTimeout clears the value of the "timeout" field.
func (_u *TaskUpdate) ClearTimeout() *TaskUpdate {
	_u.mutation.ClearTimeout()
	return _u
}

// SetRetryPolicy sets the "retry_policy" field.
func (_u *TaskUpdate) SetRetryPolicy(v *schema.RetryPolicy) *TaskUpdate {
	_u.mutation.SetRetryPolicy(v)
	return _u
}

// ClearRetryPolicy clears the value of the "retry_policy" field.
func (_u *TaskUpdate) ClearRetryPolicy() *TaskUpdate {
	_u.mutation.ClearRetryPolicy()
	return _u
}

// SetIsTpl sets the "is_tpl" field.
func (_u *TaskUpdate) SetIsTpl(v bool) *TaskUpdate {
	_u.mutation.SetIsTpl(v)
	return _u
}

// SetNillableIsTpl sets the "is_tpl" field if the given value is not nil.
func (_u *TaskUpdate) SetNillableIsTpl(v *bool) *TaskUpdate {
	if v != nil {
		_u.SetIsTpl(*v)
	}
	return _u
}

// ClearIsTpl clears the value of the "is_tpl" field.
func (_u *TaskUpdate) ClearIsTpl() *TaskUpdate {
	_u.mutation.ClearIsTpl()
	return _u
}

// AddStepIDs adds the "steps" edge to the Step entity by IDs.
func (_u *TaskUpdate) AddStepIDs(ids ...uint64) *TaskUpdate {
	_u.mutation.AddStepIDs(ids...)
	return _u
}

// AddSteps adds the "steps" edges to the Step entity.
func (_u *TaskUpdate) AddSteps(v ...*Step) *TaskUpdate {
	ids := make([]uint64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddStepIDs(ids...)
}

// AddParamIDs adds the "params" edge to the Param entity by IDs.
func (_u *TaskUpdate) AddParamIDs(ids ...uint64) *TaskUpdate {
	_u.mutation.AddParamIDs(ids...)
	return _u
}

// AddParams adds the "params" edges to the Param entity.
func (_u *TaskUpdate) AddParams(v ...*Param) *TaskUpdate {
	ids := make([]uint64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddParamIDs(ids...)
}

// AddTaskStepIDs adds the "task_steps" edge to the TaskStep entity by IDs.
func (_u *TaskUpdate) AddTaskStepIDs(ids ...uint64) *TaskUpdate {
	_u.mutation.AddTaskStepIDs(ids...)
	return _u
}

// AddTaskSteps adds the "task_steps" edges to the TaskStep entity.
func (_u *TaskUpdate) AddTaskSteps(v ...*TaskStep) *TaskUpdate {
	ids := make([]uint64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddTaskStepIDs(ids...)
}

// AddTaskParamIDs adds the "task_params" edge to the TaskParam entity by IDs.
func (_u *TaskUpdate) AddTaskParamIDs(ids ...uint64) *TaskUpdate {
	_u.mutation.AddTaskParamIDs(ids...)
	return _u
}

// AddTaskParams adds the "task_params" edges to the TaskParam entity.
func (_u *TaskUpdate) AddTaskParams(v ...*TaskParam) *TaskUpdate {
	ids := make([]uint64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddTaskParamIDs(ids...)
}

// Mutation returns the TaskMutation object of the builder.
func (_u *TaskUpdate) Mutation() *TaskMutation {
	return _u.mutation
}

// ClearSteps clears all "steps" edges to the Step entity.
func (_u *TaskUpdate) ClearSteps() *TaskUpdate {
	_u.mutation.ClearSteps()
	return _u
}

// RemoveStepIDs removes the "steps" edge to Step entities by IDs.
func (_u *TaskUpdate) RemoveStepIDs(ids ...uint64) *TaskUpdate {
	_u.mutation.RemoveStepIDs(ids...)
	return _u
}

// RemoveSteps removes "steps" edges to Step entities.
func (_u *TaskUpdate) RemoveSteps(v ...*Step) *TaskUpdate {
	ids := make([]uint64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveStepIDs(ids...)
}

// ClearParams clears all "params" edges to the Param entity.
func (_u *TaskUpdate) ClearParams() *TaskUpdate {
	_u.mutation.ClearParams()
	return _u
}

// RemoveParamIDs removes the "params" edge to Param entities by IDs.
func (_u *TaskUpdate) RemoveParamIDs(ids ...uint64) *TaskUpdate {
	_u.mutation.RemoveParamIDs(ids...)
	return _u
}

// RemoveParams removes "params" edges to Param entities.
func (_u *TaskUpdate) RemoveParams(v ...*Param) *TaskUpdate {
	ids := make([]uint64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveParamIDs(ids...)
}

// ClearTaskSteps clears all "task_steps" edges to the TaskStep entity.
func (_u *TaskUpdate) ClearTaskSteps() *TaskUpdate {
	_u.mutation.ClearTaskSteps()
	return _u
}

// RemoveTaskStepIDs removes the "task_steps" edge to TaskStep entities by IDs.
func (_u *TaskUpdate) RemoveTaskStepIDs(ids ...uint64) *TaskUpdate {
	_u.mutation.RemoveTaskStepIDs(ids...)
	return _u
}

// RemoveTaskSteps removes "task_steps" edges to TaskStep entities.
func (_u *TaskUpdate) RemoveTaskSteps(v ...*TaskStep) *TaskUpdate {
	ids := make([]uint64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveTaskStepIDs(ids...)
}

// ClearTaskParams clears all "task_params" edges to the TaskParam entity.
func (_u *TaskUpdate) ClearTaskParams() *TaskUpdate {
	_u.mutation.ClearTaskParams()
	return _u
}

// RemoveTaskParamIDs removes the "task_params" edge to TaskParam entities by IDs.
func (_u *TaskUpdate) RemoveTaskParamIDs(ids ...uint64) *TaskUpdate {
	_u.mutation.RemoveTaskParamIDs(ids...)
	return _u
}

// RemoveTaskParams removes "task_params" edges to TaskParam entities.
func (_u *TaskUpdate) RemoveTaskParams(v ...*TaskParam) *TaskUpdate {
	ids := make([]uint64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveTaskParamIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *TaskUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TaskUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *TaskUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TaskUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *TaskUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok && !_u.mutation.UpdatedAtCleared() {
		v := task.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TaskUpdate) check() error {
	if v, ok := _u.mutation.State(); ok {
		if err := task.StateValidator(v); err != nil {
			return &ValidationError{Name: "state", err: fmt.Errorf(`entv1: validator failed for field "Task.state": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PreviousState(); ok {
		if err := task.PreviousStateValidator(v); err != nil {
			return &ValidationError{Name: "previous_state", err: fmt.Errorf(`entv1: validator failed for field "Task.previous_state": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := task.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`entv1: validator failed for field "Task.name": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *TaskUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *TaskUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *TaskUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(task.Table, task.Columns, sqlgraph.NewFieldSpec(task.FieldID, field.TypeUint64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.CreatedAtCleared() {
		_spec.ClearField(task.FieldCreatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(task.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UpdatedAtCleared() {
		_spec.ClearField(task.FieldUpdatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(task.FieldCreatedBy, field.TypeString, value)
	}
	if _u.mutation.CreatedByCleared() {
		_spec.ClearField(task.FieldCreatedBy, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedBy(); ok {
		_spec.SetField(task.FieldUpdatedBy, field.TypeString, value)
	}
	if _u.mutation.UpdatedByCleared() {
		_spec.ClearField(task.FieldUpdatedBy, field.TypeString)
	}
	if value, ok := _u.mutation.Disabled(); ok {
		_spec.SetField(task.FieldDisabled, field.TypeBool, value)
	}
	if _u.mutation.DisabledCleared() {
		_spec.ClearField(task.FieldDisabled, field.TypeBool)
	}
	if value, ok := _u.mutation.Message(); ok {
		_spec.SetField(task.FieldMessage, field.TypeString, value)
	}
	if _u.mutation.MessageCleared() {
		_spec.ClearField(task.FieldMessage, field.TypeString)
	}
	if value, ok := _u.mutation.State(); ok {
		_spec.SetField(task.FieldState, field.TypeEnum, value)
	}
	if _u.mutation.StateCleared() {
		_spec.ClearField(task.FieldState, field.TypeEnum)
	}
	if value, ok := _u.mutation.PreviousState(); ok {
		_spec.SetField(task.FieldPreviousState, field.TypeEnum, value)
	}
	if _u.mutation.PreviousStateCleared() {
		_spec.ClearField(task.FieldPreviousState, field.TypeEnum)
	}
	if value, ok := _u.mutation.StartTime(); ok {
		_spec.SetField(task.FieldStartTime, field.TypeTime, value)
	}
	if _u.mutation.StartTimeCleared() {
		_spec.ClearField(task.FieldStartTime, field.TypeTime)
	}
	if value, ok := _u.mutation.EndTime(); ok {
		_spec.SetField(task.FieldEndTime, field.TypeTime, value)
	}
	if _u.mutation.EndTimeCleared() {
		_spec.ClearField(task.FieldEndTime, field.TypeTime)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(task.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Desc(); ok {
		_spec.SetField(task.FieldDesc, field.TypeString, value)
	}
	if _u.mutation.DescCleared() {
		_spec.ClearField(task.FieldDesc, field.TypeString)
	}
	if value, ok := _u.mutation.Kind(); ok {
		_spec.SetField(task.FieldKind, field.TypeString, value)
	}
	if _u.mutation.KindCleared() {
		_spec.ClearField(task.FieldKind, field.TypeString)
	}
	if value, ok := _u.mutation.Node(); ok {
		_spec.SetField(task.FieldNode, field.TypeString, value)
	}
	if _u.mutation.NodeCleared() {
		_spec.ClearField(task.FieldNode, field.TypeString)
	}
	if value, ok := _u.mutation.Timeout(); ok {
		_spec.SetField(task.FieldTimeout, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedTimeout(); ok {
		_spec.AddField(task.FieldTimeout, field.TypeInt64, value)
	}
	if _u.mutation.TimeoutCleared() {
		_spec.ClearField(task.FieldTimeout, field.TypeInt64)
	}
	if value, ok := _u.mutation.RetryPolicy(); ok {
		_spec.SetField(task.FieldRetryPolicy, field.TypeJSON, value)
	}
	if _u.mutation.RetryPolicyCleared() {
		_spec.ClearField(task.FieldRetryPolicy, field.TypeJSON)
	}
	if value, ok := _u.mutation.IsTpl(); ok {
		_spec.SetField(task.FieldIsTpl, field.TypeBool, value)
	}
	if _u.mutation.IsTplCleared() {
		_spec.ClearField(task.FieldIsTpl, field.TypeBool)
	}
	if _u.mutation.StepsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   task.StepsTable,
			Columns: task.StepsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(step.FieldID, field.TypeUint64),
			},
		}
		createE := &TaskStepCreate{config: _u.config, mutation: newTaskStepMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedStepsIDs(); len(nodes) > 0 && !_u.mutation.StepsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   task.StepsTable,
			Columns: task.StepsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(step.FieldID, field.TypeUint64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		createE := &TaskStepCreate{config: _u.config, mutation: newTaskStepMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.StepsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   task.StepsTable,
			Columns: task.StepsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(step.FieldID, field.TypeUint64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		createE := &TaskStepCreate{config: _u.config, mutation: newTaskStepMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ParamsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   task.ParamsTable,
			Columns: task.ParamsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(param.FieldID, field.TypeUint64),
			},
		}
		createE := &TaskParamCreate{config: _u.config, mutation: newTaskParamMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedParamsIDs(); len(nodes) > 0 && !_u.mutation.ParamsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   task.ParamsTable,
			Columns: task.ParamsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(param.FieldID, field.TypeUint64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		createE := &TaskParamCreate{config: _u.config, mutation: newTaskParamMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ParamsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   task.ParamsTable,
			Columns: task.ParamsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(param.FieldID, field.TypeUint64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		createE := &TaskParamCreate{config: _u.config, mutation: newTaskParamMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TaskStepsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   task.TaskStepsTable,
			Columns: []string{task.TaskStepsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(taskstep.FieldID, field.TypeUint64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedTaskStepsIDs(); len(nodes) > 0 && !_u.mutation.TaskStepsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   task.TaskStepsTable,
			Columns: []string{task.TaskStepsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(taskstep.FieldID, field.TypeUint64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TaskStepsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   task.TaskStepsTable,
			Columns: []string{task.TaskStepsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(taskstep.FieldID, field.TypeUint64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TaskParamsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   task.TaskParamsTable,
			Columns: []string{task.TaskParamsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(taskparam.FieldID, field.TypeUint64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedTaskParamsIDs(); len(nodes) > 0 && !_u.mutation.TaskParamsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   task.TaskParamsTable,
			Columns: []string{task.TaskParamsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(taskparam.FieldID, field.TypeUint64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TaskParamsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   task.TaskParamsTable,
			Columns: []string{task.TaskParamsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(taskparam.FieldID, field.TypeUint64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{task.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// TaskUpdateOne is the builder for updating a single Task entity.
type TaskUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *TaskMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *TaskUpdateOne) SetUpdatedAt(v time.Time) *TaskUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (_u *TaskUpdateOne) ClearUpdatedAt() *TaskUpdateOne {
	_u.mutation.ClearUpdatedAt()
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *TaskUpdateOne) SetCreatedBy(v string) *TaskUpdateOne {
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *TaskUpdateOne) SetNillableCreatedBy(v *string) *TaskUpdateOne {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (_u *TaskUpdateOne) ClearCreatedBy() *TaskUpdateOne {
	_u.mutation.ClearCreatedBy()
	return _u
}

// SetUpdatedBy sets the "updated_by" field.
func (_u *TaskUpdateOne) SetUpdatedBy(v string) *TaskUpdateOne {
	_u.mutation.SetUpdatedBy(v)
	return _u
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_u *TaskUpdateOne) SetNillableUpdatedBy(v *string) *TaskUpdateOne {
	if v != nil {
		_u.SetUpdatedBy(*v)
	}
	return _u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (_u *TaskUpdateOne) ClearUpdatedBy() *TaskUpdateOne {
	_u.mutation.ClearUpdatedBy()
	return _u
}

// SetDisabled sets the "disabled" field.
func (_u *TaskUpdateOne) SetDisabled(v bool) *TaskUpdateOne {
	_u.mutation.SetDisabled(v)
	return _u
}

// SetNillableDisabled sets the "disabled" field if the given value is not nil.
func (_u *TaskUpdateOne) SetNillableDisabled(v *bool) *TaskUpdateOne {
	if v != nil {
		_u.SetDisabled(*v)
	}
	return _u
}

// ClearDisabled clears the value of the "disabled" field.
func (_u *TaskUpdateOne) ClearDisabled() *TaskUpdateOne {
	_u.mutation.ClearDisabled()
	return _u
}

// SetMessage sets the "message" field.
func (_u *TaskUpdateOne) SetMessage(v string) *TaskUpdateOne {
	_u.mutation.SetMessage(v)
	return _u
}

// SetNillableMessage sets the "message" field if the given value is not nil.
func (_u *TaskUpdateOne) SetNillableMessage(v *string) *TaskUpdateOne {
	if v != nil {
		_u.SetMessage(*v)
	}
	return _u
}

// ClearMessage clears the value of the "message" field.
func (_u *TaskUpdateOne) ClearMessage() *TaskUpdateOne {
	_u.mutation.ClearMessage()
	return _u
}

// SetState sets the "state" field.
func (_u *TaskUpdateOne) SetState(v task.State) *TaskUpdateOne {
	_u.mutation.SetState(v)
	return _u
}

// SetNillableState sets the "state" field if the given value is not nil.
func (_u *TaskUpdateOne) SetNillableState(v *task.State) *TaskUpdateOne {
	if v != nil {
		_u.SetState(*v)
	}
	return _u
}

// ClearState clears the value of the "state" field.
func (_u *TaskUpdateOne) ClearState() *TaskUpdateOne {
	_u.mutation.ClearState()
	return _u
}

// SetPreviousState sets the "previous_state" field.
func (_u *TaskUpdateOne) SetPreviousState(v task.PreviousState) *TaskUpdateOne {
	_u.mutation.SetPreviousState(v)
	return _u
}

// SetNillablePreviousState sets the "previous_state" field if the given value is not nil.
func (_u *TaskUpdateOne) SetNillablePreviousState(v *task.PreviousState) *TaskUpdateOne {
	if v != nil {
		_u.SetPreviousState(*v)
	}
	return _u
}

// ClearPreviousState clears the value of the "previous_state" field.
func (_u *TaskUpdateOne) ClearPreviousState() *TaskUpdateOne {
	_u.mutation.ClearPreviousState()
	return _u
}

// SetStartTime sets the "start_time" field.
func (_u *TaskUpdateOne) SetStartTime(v time.Time) *TaskUpdateOne {
	_u.mutation.SetStartTime(v)
	return _u
}

// SetNillableStartTime sets the "start_time" field if the given value is not nil.
func (_u *TaskUpdateOne) SetNillableStartTime(v *time.Time) *TaskUpdateOne {
	if v != nil {
		_u.SetStartTime(*v)
	}
	return _u
}

// ClearStartTime clears the value of the "start_time" field.
func (_u *TaskUpdateOne) ClearStartTime() *TaskUpdateOne {
	_u.mutation.ClearStartTime()
	return _u
}

// SetEndTime sets the "end_time" field.
func (_u *TaskUpdateOne) SetEndTime(v time.Time) *TaskUpdateOne {
	_u.mutation.SetEndTime(v)
	return _u
}

// SetNillableEndTime sets the "end_time" field if the given value is not nil.
func (_u *TaskUpdateOne) SetNillableEndTime(v *time.Time) *TaskUpdateOne {
	if v != nil {
		_u.SetEndTime(*v)
	}
	return _u
}

// ClearEndTime clears the value of the "end_time" field.
func (_u *TaskUpdateOne) ClearEndTime() *TaskUpdateOne {
	_u.mutation.ClearEndTime()
	return _u
}

// SetName sets the "name" field.
func (_u *TaskUpdateOne) SetName(v string) *TaskUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *TaskUpdateOne) SetNillableName(v *string) *TaskUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDesc sets the "desc" field.
func (_u *TaskUpdateOne) SetDesc(v string) *TaskUpdateOne {
	_u.mutation.SetDesc(v)
	return _u
}

// SetNillableDesc sets the "desc" field if the given value is not nil.
func (_u *TaskUpdateOne) SetNillableDesc(v *string) *TaskUpdateOne {
	if v != nil {
		_u.SetDesc(*v)
	}
	return _u
}

// ClearDesc clears the value of the "desc" field.
func (_u *TaskUpdateOne) ClearDesc() *TaskUpdateOne {
	_u.mutation.ClearDesc()
	return _u
}

// SetKind sets the "kind" field.
func (_u *TaskUpdateOne) SetKind(v string) *TaskUpdateOne {
	_u.mutation.SetKind(v)
	return _u
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (_u *TaskUpdateOne) SetNillableKind(v *string) *TaskUpdateOne {
	if v != nil {
		_u.SetKind(*v)
	}
	return _u
}

// ClearKind clears the value of the "kind" field.
func (_u *TaskUpdateOne) ClearKind() *TaskUpdateOne {
	_u.mutation.ClearKind()
	return _u
}

// SetNode sets the "node" field.
func (_u *TaskUpdateOne) SetNode(v string) *TaskUpdateOne {
	_u.mutation.SetNode(v)
	return _u
}

// SetNillableNode sets the "node" field if the given value is not nil.
func (_u *TaskUpdateOne) SetNillableNode(v *string) *TaskUpdateOne {
	if v != nil {
		_u.SetNode(*v)
	}
	return _u
}

// ClearNode clears the value of the "node" field.
func (_u *TaskUpdateOne) ClearNode() *TaskUpdateOne {
	_u.mutation.ClearNode()
	return _u
}

// SetTimeout sets the "timeout" field.
func (_u *TaskUpdateOne) SetTimeout(v int64) *TaskUpdateOne {
	_u.mutation.ResetTimeout()
	_u.mutation.SetTimeout(v)
	return _u
}

// SetNillableTimeout sets the "timeout" field if the given value is not nil.
func (_u *TaskUpdateOne) SetNillableTimeout(v *int64) *TaskUpdateOne {
	if v != nil {
		_u.SetTimeout(*v)
	}
	return _u
}

// AddTimeout adds value to the "timeout" field.
func (_u *TaskUpdateOne) AddTimeout(v int64) *TaskUpdateOne {
	_u.mutation.AddTimeout(v)
	return _u
}

// ClearTimeout clears the value of the "timeout" field.
func (_u *TaskUpdateOne) ClearTimeout() *TaskUpdateOne {
	_u.mutation.ClearTimeout()
	return _u
}

// SetRetryPolicy sets the "retry_policy" field.
func (_u *TaskUpdateOne) SetRetryPolicy(v *schema.RetryPolicy) *TaskUpdateOne {
	_u.mutation.SetRetryPolicy(v)
	return _u
}

// ClearRetryPolicy clears the value of the "retry_policy" field.
func (_u *TaskUpdateOne) ClearRetryPolicy() *TaskUpdateOne {
	_u.mutation.ClearRetryPolicy()
	return _u
}

// SetIsTpl sets the "is_tpl" field.
func (_u *TaskUpdateOne) SetIsTpl(v bool) *TaskUpdateOne {
	_u.mutation.SetIsTpl(v)
	return _u
}

// SetNillableIsTpl sets the "is_tpl" field if the given value is not nil.
func (_u *TaskUpdateOne) SetNillableIsTpl(v *bool) *TaskUpdateOne {
	if v != nil {
		_u.SetIsTpl(*v)
	}
	return _u
}

// ClearIsTpl clears the value of the "is_tpl" field.
func (_u *TaskUpdateOne) ClearIsTpl() *TaskUpdateOne {
	_u.mutation.ClearIsTpl()
	return _u
}

// AddStepIDs adds the "steps" edge to the Step entity by IDs.
func (_u *TaskUpdateOne) AddStepIDs(ids ...uint64) *TaskUpdateOne {
	_u.mutation.AddStepIDs(ids...)
	return _u
}

// AddSteps adds the "steps" edges to the Step entity.
func (_u *TaskUpdateOne) AddSteps(v ...*Step) *TaskUpdateOne {
	ids := make([]uint64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddStepIDs(ids...)
}

// AddParamIDs adds the "params" edge to the Param entity by IDs.
func (_u *TaskUpdateOne) AddParamIDs(ids ...uint64) *TaskUpdateOne {
	_u.mutation.AddParamIDs(ids...)
	return _u
}

// AddParams adds the "params" edges to the Param entity.
func (_u *TaskUpdateOne) AddParams(v ...*Param) *TaskUpdateOne {
	ids := make([]uint64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddParamIDs(ids...)
}

// AddTaskStepIDs adds the "task_steps" edge to the TaskStep entity by IDs.
func (_u *TaskUpdateOne) AddTaskStepIDs(ids ...uint64) *TaskUpdateOne {
	_u.mutation.AddTaskStepIDs(ids...)
	return _u
}

// AddTaskSteps adds the "task_steps" edges to the TaskStep entity.
func (_u *TaskUpdateOne) AddTaskSteps(v ...*TaskStep) *TaskUpdateOne {
	ids := make([]uint64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddTaskStepIDs(ids...)
}

// AddTaskParamIDs adds the "task_params" edge to the TaskParam entity by IDs.
func (_u *TaskUpdateOne) AddTaskParamIDs(ids ...uint64) *TaskUpdateOne {
	_u.mutation.AddTaskParamIDs(ids...)
	return _u
}

// AddTaskParams adds the "task_params" edges to the TaskParam entity.
func (_u *TaskUpdateOne) AddTaskParams(v ...*TaskParam) *TaskUpdateOne {
	ids := make([]uint64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddTaskParamIDs(ids...)
}

// Mutation returns the TaskMutation object of the builder.
func (_u *TaskUpdateOne) Mutation() *TaskMutation {
	return _u.mutation
}

// ClearSteps clears all "steps" edges to the Step entity.
func (_u *TaskUpdateOne) ClearSteps() *TaskUpdateOne {
	_u.mutation.ClearSteps()
	return _u
}

// RemoveStepIDs removes the "steps" edge to Step entities by IDs.
func (_u *TaskUpdateOne) RemoveStepIDs(ids ...uint64) *TaskUpdateOne {
	_u.mutation.RemoveStepIDs(ids...)
	return _u
}

// RemoveSteps removes "steps" edges to Step entities.
func (_u *TaskUpdateOne) RemoveSteps(v ...*Step) *TaskUpdateOne {
	ids := make([]uint64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveStepIDs(ids...)
}

// ClearParams clears all "params" edges to the Param entity.
func (_u *TaskUpdateOne) ClearParams() *TaskUpdateOne {
	_u.mutation.ClearParams()
	return _u
}

// RemoveParamIDs removes the "params" edge to Param entities by IDs.
func (_u *TaskUpdateOne) RemoveParamIDs(ids ...uint64) *TaskUpdateOne {
	_u.mutation.RemoveParamIDs(ids...)
	return _u
}

// RemoveParams removes "params" edges to Param entities.
func (_u *TaskUpdateOne) RemoveParams(v ...*Param) *TaskUpdateOne {
	ids := make([]uint64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveParamIDs(ids...)
}

// ClearTaskSteps clears all "task_steps" edges to the TaskStep entity.
func (_u *TaskUpdateOne) ClearTaskSteps() *TaskUpdateOne {
	_u.mutation.ClearTaskSteps()
	return _u
}

// RemoveTaskStepIDs removes the "task_steps" edge to TaskStep entities by IDs.
func (_u *TaskUpdateOne) RemoveTaskStepIDs(ids ...uint64) *TaskUpdateOne {
	_u.mutation.RemoveTaskStepIDs(ids...)
	return _u
}

// RemoveTaskSteps removes "task_steps" edges to TaskStep entities.
func (_u *TaskUpdateOne) RemoveTaskSteps(v ...*TaskStep) *TaskUpdateOne {
	ids := make([]uint64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveTaskStepIDs(ids...)
}

// ClearTaskParams clears all "task_params" edges to the TaskParam entity.
func (_u *TaskUpdateOne) ClearTaskParams() *TaskUpdateOne {
	_u.mutation.ClearTaskParams()
	return _u
}

// RemoveTaskParamIDs removes the "task_params" edge to TaskParam entities by IDs.
func (_u *TaskUpdateOne) RemoveTaskParamIDs(ids ...uint64) *TaskUpdateOne {
	_u.mutation.RemoveTaskParamIDs(ids...)
	return _u
}

// RemoveTaskParams removes "task_params" edges to TaskParam entities.
func (_u *TaskUpdateOne) RemoveTaskParams(v ...*TaskParam) *TaskUpdateOne {
	ids := make([]uint64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveTaskParamIDs(ids...)
}

// Where appends a list predicates to the TaskUpdate builder.
func (_u *TaskUpdateOne) Where(ps ...predicate.Task) *TaskUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *TaskUpdateOne) Select(field string, fields ...string) *TaskUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Task entity.
func (_u *TaskUpdateOne) Save(ctx context.Context) (*Task, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TaskUpdateOne) SaveX(ctx context.Context) *Task {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *TaskUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TaskUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *TaskUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok && !_u.mutation.UpdatedAtCleared() {
		v := task.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TaskUpdateOne) check() error {
	if v, ok := _u.mutation.State(); ok {
		if err := task.StateValidator(v); err != nil {
			return &ValidationError{Name: "state", err: fmt.Errorf(`entv1: validator failed for field "Task.state": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PreviousState(); ok {
		if err := task.PreviousStateValidator(v); err != nil {
			return &ValidationError{Name: "previous_state", err: fmt.Errorf(`entv1: validator failed for field "Task.previous_state": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := task.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`entv1: validator failed for field "Task.name": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *TaskUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *TaskUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *TaskUpdateOne) sqlSave(ctx context.Context) (_node *Task, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(task.Table, task.Columns, sqlgraph.NewFieldSpec(task.FieldID, field.TypeUint64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`entv1: missing "Task.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, task.FieldID)
		for _, f := range fields {
			if !task.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("entv1: invalid field %q for query", f)}
			}
			if f != task.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.CreatedAtCleared() {
		_spec.ClearField(task.FieldCreatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(task.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UpdatedAtCleared() {
		_spec.ClearField(task.FieldUpdatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(task.FieldCreatedBy, field.TypeString, value)
	}
	if _u.mutation.CreatedByCleared() {
		_spec.ClearField(task.FieldCreatedBy, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedBy(); ok {
		_spec.SetField(task.FieldUpdatedBy, field.TypeString, value)
	}
	if _u.mutation.UpdatedByCleared() {
		_spec.ClearField(task.FieldUpdatedBy, field.TypeString)
	}
	if value, ok := _u.mutation.Disabled(); ok {
		_spec.SetField(task.FieldDisabled, field.TypeBool, value)
	}
	if _u.mutation.DisabledCleared() {
		_spec.ClearField(task.FieldDisabled, field.TypeBool)
	}
	if value, ok := _u.mutation.Message(); ok {
		_spec.SetField(task.FieldMessage, field.TypeString, value)
	}
	if _u.mutation.MessageCleared() {
		_spec.ClearField(task.FieldMessage, field.TypeString)
	}
	if value, ok := _u.mutation.State(); ok {
		_spec.SetField(task.FieldState, field.TypeEnum, value)
	}
	if _u.mutation.StateCleared() {
		_spec.ClearField(task.FieldState, field.TypeEnum)
	}
	if value, ok := _u.mutation.PreviousState(); ok {
		_spec.SetField(task.FieldPreviousState, field.TypeEnum, value)
	}
	if _u.mutation.PreviousStateCleared() {
		_spec.ClearField(task.FieldPreviousState, field.TypeEnum)
	}
	if value, ok := _u.mutation.StartTime(); ok {
		_spec.SetField(task.FieldStartTime, field.TypeTime, value)
	}
	if _u.mutation.StartTimeCleared() {
		_spec.ClearField(task.FieldStartTime, field.TypeTime)
	}
	if value, ok := _u.mutation.EndTime(); ok {
		_spec.SetField(task.FieldEndTime, field.TypeTime, value)
	}
	if _u.mutation.EndTimeCleared() {
		_spec.ClearField(task.FieldEndTime, field.TypeTime)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(task.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Desc(); ok {
		_spec.SetField(task.FieldDesc, field.TypeString, value)
	}
	if _u.mutation.DescCleared() {
		_spec.ClearField(task.FieldDesc, field.TypeString)
	}
	if value, ok := _u.mutation.Kind(); ok {
		_spec.SetField(task.FieldKind, field.TypeString, value)
	}
	if _u.mutation.KindCleared() {
		_spec.ClearField(task.FieldKind, field.TypeString)
	}
	if value, ok := _u.mutation.Node(); ok {
		_spec.SetField(task.FieldNode, field.TypeString, value)
	}
	if _u.mutation.NodeCleared() {
		_spec.ClearField(task.FieldNode, field.TypeString)
	}
	if value, ok := _u.mutation.Timeout(); ok {
		_spec.SetField(task.FieldTimeout, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedTimeout(); ok {
		_spec.AddField(task.FieldTimeout, field.TypeInt64, value)
	}
	if _u.mutation.TimeoutCleared() {
		_spec.ClearField(task.FieldTimeout, field.TypeInt64)
	}
	if value, ok := _u.mutation.RetryPolicy(); ok {
		_spec.SetField(task.FieldRetryPolicy, field.TypeJSON, value)
	}
	if _u.mutation.RetryPolicyCleared() {
		_spec.ClearField(task.FieldRetryPolicy, field.TypeJSON)
	}
	if value, ok := _u.mutation.IsTpl(); ok {
		_spec.SetField(task.FieldIsTpl, field.TypeBool, value)
	}
	if _u.mutation.IsTplCleared() {
		_spec.ClearField(task.FieldIsTpl, field.TypeBool)
	}
	if _u.mutation.StepsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   task.StepsTable,
			Columns: task.StepsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(step.FieldID, field.TypeUint64),
			},
		}
		createE := &TaskStepCreate{config: _u.config, mutation: newTaskStepMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedStepsIDs(); len(nodes) > 0 && !_u.mutation.StepsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   task.StepsTable,
			Columns: task.StepsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(step.FieldID, field.TypeUint64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		createE := &TaskStepCreate{config: _u.config, mutation: newTaskStepMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.StepsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   task.StepsTable,
			Columns: task.StepsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(step.FieldID, field.TypeUint64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		createE := &TaskStepCreate{config: _u.config, mutation: newTaskStepMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ParamsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   task.ParamsTable,
			Columns: task.ParamsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(param.FieldID, field.TypeUint64),
			},
		}
		createE := &TaskParamCreate{config: _u.config, mutation: newTaskParamMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedParamsIDs(); len(nodes) > 0 && !_u.mutation.ParamsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   task.ParamsTable,
			Columns: task.ParamsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(param.FieldID, field.TypeUint64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		createE := &TaskParamCreate{config: _u.config, mutation: newTaskParamMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ParamsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   task.ParamsTable,
			Columns: task.ParamsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(param.FieldID, field.TypeUint64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		createE := &TaskParamCreate{config: _u.config, mutation: newTaskParamMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TaskStepsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   task.TaskStepsTable,
			Columns: []string{task.TaskStepsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(taskstep.FieldID, field.TypeUint64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedTaskStepsIDs(); len(nodes) > 0 && !_u.mutation.TaskStepsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   task.TaskStepsTable,
			Columns: []string{task.TaskStepsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(taskstep.FieldID, field.TypeUint64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TaskStepsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   task.TaskStepsTable,
			Columns: []string{task.TaskStepsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(taskstep.FieldID, field.TypeUint64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TaskParamsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   task.TaskParamsTable,
			Columns: []string{task.TaskParamsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(taskparam.FieldID, field.TypeUint64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedTaskParamsIDs(); len(nodes) > 0 && !_u.mutation.TaskParamsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   task.TaskParamsTable,
			Columns: []string{task.TaskParamsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(taskparam.FieldID, field.TypeUint64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TaskParamsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   task.TaskParamsTable,
			Columns: []string{task.TaskParamsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(taskparam.FieldID, field.TypeUint64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &Task{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{task.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
