// Code generated by ent, DO NOT EDIT.

package entv1

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/busyster996/dagflow/internal/entv1/taskstep"
	"github.com/busyster996/dagflow/internal/entv1/taskstepoutput"
)

// TaskStepOutputCreate is the builder for creating a TaskStepOutput entity.
type TaskStepOutputCreate struct {
	config
	mutation *TaskStepOutputMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *TaskStepOutputCreate) SetCreatedAt(v time.Time) *TaskStepOutputCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *TaskStepOutputCreate) SetNillableCreatedAt(v *time.Time) *TaskStepOutputCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *TaskStepOutputCreate) SetUpdatedAt(v time.Time) *TaskStepOutputCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *TaskStepOutputCreate) SetNillableUpdatedAt(v *time.Time) *TaskStepOutputCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetCreatedBy sets the "created_by" field.
func (_c *TaskStepOutputCreate) SetCreatedBy(v string) *TaskStepOutputCreate {
	_c.mutation.SetCreatedBy(v)
	return _c
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_c *TaskStepOutputCreate) SetNillableCreatedBy(v *string) *TaskStepOutputCreate {
	if v != nil {
		_c.SetCreatedBy(*v)
	}
	return _c
}

// SetUpdatedBy sets the "updated_by" field.
func (_c *TaskStepOutputCreate) SetUpdatedBy(v string) *TaskStepOutputCreate {
	_c.mutation.SetUpdatedBy(v)
	return _c
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_c *TaskStepOutputCreate) SetNillableUpdatedBy(v *string) *TaskStepOutputCreate {
	if v != nil {
		_c.SetUpdatedBy(*v)
	}
	return _c
}

// SetExecID sets the "exec_id" field.
func (_c *TaskStepOutputCreate) SetExecID(v uint64) *TaskStepOutputCreate {
	_c.mutation.SetExecID(v)
	return _c
}

// SetTimestamp sets the "timestamp" field.
func (_c *TaskStepOutputCreate) SetTimestamp(v int64) *TaskStepOutputCreate {
	_c.mutation.SetTimestamp(v)
	return _c
}

// SetNillableTimestamp sets the "timestamp" field if the given value is not nil.
func (_c *TaskStepOutputCreate) SetNillableTimestamp(v *int64) *TaskStepOutputCreate {
	if v != nil {
		_c.SetTimestamp(*v)
	}
	return _c
}

// SetContent sets the "content" field.
func (_c *TaskStepOutputCreate) SetContent(v string) *TaskStepOutputCreate {
	_c.mutation.SetContent(v)
	return _c
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_c *TaskStepOutputCreate) SetNillableContent(v *string) *TaskStepOutputCreate {
	if v != nil {
		_c.SetContent(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *TaskStepOutputCreate) SetID(v uint64) *TaskStepOutputCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetTaskStepID sets the "task_step" edge to the TaskStep entity by ID.
func (_c *TaskStepOutputCreate) SetTaskStepID(id uint64) *TaskStepOutputCreate {
	_c.mutation.SetTaskStepID(id)
	return _c
}

// SetTaskStep sets the "task_step" edge to the TaskStep entity.
func (_c *TaskStepOutputCreate) SetTaskStep(v *TaskStep) *TaskStepOutputCreate {
	return _c.SetTaskStepID(v.ID)
}

// Mutation returns the TaskStepOutputMutation object of the builder.
func (_c *TaskStepOutputCreate) Mutation() *TaskStepOutputMutation {
	return _c.mutation
}

// Save creates the TaskStepOutput in the database.
func (_c *TaskStepOutputCreate) Save(ctx context.Context) (*TaskStepOutput, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *TaskStepOutputCreate) SaveX(ctx context.Context) *TaskStepOutput {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TaskStepOutputCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TaskStepOutputCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *TaskStepOutputCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := taskstepoutput.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := taskstepoutput.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Timestamp(); !ok {
		v := taskstepoutput.DefaultTimestamp()
		_c.mutation.SetTimestamp(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *TaskStepOutputCreate) check() error {
	if _, ok := _c.mutation.ExecID(); !ok {
		return &ValidationError{Name: "exec_id", err: errors.New(`entv1: missing required field "TaskStepOutput.exec_id"`)}
	}
	if len(_c.mutation.TaskStepIDs()) == 0 {
		return &ValidationError{Name: "task_step", err: errors.New(`entv1: missing required edge "TaskStepOutput.task_step"`)}
	}
	return nil
}

func (_c *TaskStepOutputCreate) sqlSave(ctx context.Context) (*TaskStepOutput, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = uint64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *TaskStepOutputCreate) createSpec() (*TaskStepOutput, *sqlgraph.CreateSpec) {
	var (
		_node = &TaskStepOutput{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(taskstepoutput.Table, sqlgraph.NewFieldSpec(taskstepoutput.FieldID, field.TypeUint64))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(taskstepoutput.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = &value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(taskstepoutput.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = &value
	}
	if value, ok := _c.mutation.CreatedBy(); ok {
		_spec.SetField(taskstepoutput.FieldCreatedBy, field.TypeString, value)
		_node.CreatedBy = &value
	}
	if value, ok := _c.mutation.UpdatedBy(); ok {
		_spec.SetField(taskstepoutput.FieldUpdatedBy, field.TypeString, value)
		_node.UpdatedBy = &value
	}
	if value, ok := _c.mutation.Timestamp(); ok {
		_spec.SetField(taskstepoutput.FieldTimestamp, field.TypeInt64, value)
		_node.Timestamp = &value
	}
	if value, ok := _c.mutation.Content(); ok {
		_spec.SetField(taskstepoutput.FieldContent, field.TypeString, value)
		_node.Content = &value
	}
	if nodes := _c.mutation.TaskStepIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   taskstepoutput.TaskStepTable,
			Columns: []string{taskstepoutput.TaskStepColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(taskstep.FieldID, field.TypeUint64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ExecID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.TaskStepOutput.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.TaskStepOutputUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *TaskStepOutputCreate) OnConflict(opts ...sql.ConflictOption) *TaskStepOutputUpsertOne {
	_c.conflict = opts
	return &TaskStepOutputUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.TaskStepOutput.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *TaskStepOutputCreate) OnConflictColumns(columns ...string) *TaskStepOutputUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &TaskStepOutputUpsertOne{
		create: _c,
	}
}

type (
	// TaskStepOutputUpsertOne is the builder for "upsert"-ing
	//  one TaskStepOutput node.
	TaskStepOutputUpsertOne struct {
		create *TaskStepOutputCreate
	}

	// TaskStepOutputUpsert is the "OnConflict" setter.
	TaskStepOutputUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *TaskStepOutputUpsert) SetUpdatedAt(v time.Time) *TaskStepOutputUpsert {
	u.Set(taskstepoutput.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *TaskStepOutputUpsert) UpdateUpdatedAt() *TaskStepOutputUpsert {
	u.SetExcluded(taskstepoutput.FieldUpdatedAt)
	return u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (u *TaskStepOutputUpsert) ClearUpdatedAt() *TaskStepOutputUpsert {
	u.SetNull(taskstepoutput.FieldUpdatedAt)
	return u
}

// SetCreatedBy sets the "created_by" field.
func (u *TaskStepOutputUpsert) SetCreatedBy(v string) *TaskStepOutputUpsert {
	u.Set(taskstepoutput.FieldCreatedBy, v)
	return u
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *TaskStepOutputUpsert) UpdateCreatedBy() *TaskStepOutputUpsert {
	u.SetExcluded(taskstepoutput.FieldCreatedBy)
	return u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (u *TaskStepOutputUpsert) ClearCreatedBy() *TaskStepOutputUpsert {
	u.SetNull(taskstepoutput.FieldCreatedBy)
	return u
}

// SetUpdatedBy sets the "updated_by" field.
func (u *TaskStepOutputUpsert) SetUpdatedBy(v string) *TaskStepOutputUpsert {
	u.Set(taskstepoutput.FieldUpdatedBy, v)
	return u
}

// UpdateUpdatedBy sets the "updated_by" field to the value that was provided on create.
func (u *TaskStepOutputUpsert) UpdateUpdatedBy() *TaskStepOutputUpsert {
	u.SetExcluded(taskstepoutput.FieldUpdatedBy)
	return u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (u *TaskStepOutputUpsert) ClearUpdatedBy() *TaskStepOutputUpsert {
	u.SetNull(taskstepoutput.FieldUpdatedBy)
	return u
}

// SetExecID sets the "exec_id" field.
func (u *TaskStepOutputUpsert) SetExecID(v uint64) *TaskStepOutputUpsert {
	u.Set(taskstepoutput.FieldExecID, v)
	return u
}

// UpdateExecID sets the "exec_id" field to the value that was provided on create.
func (u *TaskStepOutputUpsert) UpdateExecID() *TaskStepOutputUpsert {
	u.SetExcluded(taskstepoutput.FieldExecID)
	return u
}

// SetTimestamp sets the "timestamp" field.
func (u *TaskStepOutputUpsert) SetTimestamp(v int64) *TaskStepOutputUpsert {
	u.Set(taskstepoutput.FieldTimestamp, v)
	return u
}

// UpdateTimestamp sets the "timestamp" field to the value that was provided on create.
func (u *TaskStepOutputUpsert) UpdateTimestamp() *TaskStepOutputUpsert {
	u.SetExcluded(taskstepoutput.FieldTimestamp)
	return u
}

// AddTimestamp adds v to the "timestamp" field.
func (u *TaskStepOutputUpsert) AddTimestamp(v int64) *TaskStepOutputUpsert {
	u.Add(taskstepoutput.FieldTimestamp, v)
	return u
}

// ClearTimestamp clears the value of the "timestamp" field.
func (u *TaskStepOutputUpsert) ClearTimestamp() *TaskStepOutputUpsert {
	u.SetNull(taskstepoutput.FieldTimestamp)
	return u
}

// SetContent sets the "content" field.
func (u *TaskStepOutputUpsert) SetContent(v string) *TaskStepOutputUpsert {
	u.Set(taskstepoutput.FieldContent, v)
	return u
}

// UpdateContent sets the "content" field to the value that was provided on create.
func (u *TaskStepOutputUpsert) UpdateContent() *TaskStepOutputUpsert {
	u.SetExcluded(taskstepoutput.FieldContent)
	return u
}

// ClearContent clears the value of the "content" field.
func (u *TaskStepOutputUpsert) ClearContent() *TaskStepOutputUpsert {
	u.SetNull(taskstepoutput.FieldContent)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.TaskStepOutput.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(taskstepoutput.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *TaskStepOutputUpsertOne) UpdateNewValues() *TaskStepOutputUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(taskstepoutput.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(taskstepoutput.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.TaskStepOutput.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *TaskStepOutputUpsertOne) Ignore() *TaskStepOutputUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *TaskStepOutputUpsertOne) DoNothing() *TaskStepOutputUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the TaskStepOutputCreate.OnConflict
// documentation for more info.
func (u *TaskStepOutputUpsertOne) Update(set func(*TaskStepOutputUpsert)) *TaskStepOutputUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&TaskStepOutputUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *TaskStepOutputUpsertOne) SetUpdatedAt(v time.Time) *TaskStepOutputUpsertOne {
	return u.Update(func(s *TaskStepOutputUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *TaskStepOutputUpsertOne) UpdateUpdatedAt() *TaskStepOutputUpsertOne {
	return u.Update(func(s *TaskStepOutputUpsert) {
		s.UpdateUpdatedAt()
	})
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (u *TaskStepOutputUpsertOne) ClearUpdatedAt() *TaskStepOutputUpsertOne {
	return u.Update(func(s *TaskStepOutputUpsert) {
		s.ClearUpdatedAt()
	})
}

// SetCreatedBy sets the "created_by" field.
func (u *TaskStepOutputUpsertOne) SetCreatedBy(v string) *TaskStepOutputUpsertOne {
	return u.Update(func(s *TaskStepOutputUpsert) {
		s.SetCreatedBy(v)
	})
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *TaskStepOutputUpsertOne) UpdateCreatedBy() *TaskStepOutputUpsertOne {
	return u.Update(func(s *TaskStepOutputUpsert) {
		s.UpdateCreatedBy()
	})
}

// ClearCreatedBy clears the value of the "created_by" field.
func (u *TaskStepOutputUpsertOne) ClearCreatedBy() *TaskStepOutputUpsertOne {
	return u.Update(func(s *TaskStepOutputUpsert) {
		s.ClearCreatedBy()
	})
}

// SetUpdatedBy sets the "updated_by" field.
func (u *TaskStepOutputUpsertOne) SetUpdatedBy(v string) *TaskStepOutputUpsertOne {
	return u.Update(func(s *TaskStepOutputUpsert) {
		s.SetUpdatedBy(v)
	})
}

// UpdateUpdatedBy sets the "updated_by" field to the value that was provided on create.
func (u *TaskStepOutputUpsertOne) UpdateUpdatedBy() *TaskStepOutputUpsertOne {
	return u.Update(func(s *TaskStepOutputUpsert) {
		s.UpdateUpdatedBy()
	})
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (u *TaskStepOutputUpsertOne) ClearUpdatedBy() *TaskStepOutputUpsertOne {
	return u.Update(func(s *TaskStepOutputUpsert) {
		s.ClearUpdatedBy()
	})
}

// SetExecID sets the "exec_id" field.
func (u *TaskStepOutputUpsertOne) SetExecID(v uint64) *TaskStepOutputUpsertOne {
	return u.Update(func(s *TaskStepOutputUpsert) {
		s.SetExecID(v)
	})
}

// UpdateExecID sets the "exec_id" field to the value that was provided on create.
func (u *TaskStepOutputUpsertOne) UpdateExecID() *TaskStepOutputUpsertOne {
	return u.Update(func(s *TaskStepOutputUpsert) {
		s.UpdateExecID()
	})
}

// SetTimestamp sets the "timestamp" field.
func (u *TaskStepOutputUpsertOne) SetTimestamp(v int64) *TaskStepOutputUpsertOne {
	return u.Update(func(s *TaskStepOutputUpsert) {
		s.SetTimestamp(v)
	})
}

// AddTimestamp adds v to the "timestamp" field.
func (u *TaskStepOutputUpsertOne) AddTimestamp(v int64) *TaskStepOutputUpsertOne {
	return u.Update(func(s *TaskStepOutputUpsert) {
		s.AddTimestamp(v)
	})
}

// UpdateTimestamp sets the "timestamp" field to the value that was provided on create.
func (u *TaskStepOutputUpsertOne) UpdateTimestamp() *TaskStepOutputUpsertOne {
	return u.Update(func(s *TaskStepOutputUpsert) {
		s.UpdateTimestamp()
	})
}

// ClearTimestamp clears the value of the "timestamp" field.
func (u *TaskStepOutputUpsertOne) ClearTimestamp() *TaskStepOutputUpsertOne {
	return u.Update(func(s *TaskStepOutputUpsert) {
		s.ClearTimestamp()
	})
}

// SetContent sets the "content" field.
func (u *TaskStepOutputUpsertOne) SetContent(v string) *TaskStepOutputUpsertOne {
	return u.Update(func(s *TaskStepOutputUpsert) {
		s.SetContent(v)
	})
}

// UpdateContent sets the "content" field to the value that was provided on create.
func (u *TaskStepOutputUpsertOne) UpdateContent() *TaskStepOutputUpsertOne {
	return u.Update(func(s *TaskStepOutputUpsert) {
		s.UpdateContent()
	})
}

// ClearContent clears the value of the "content" field.
func (u *TaskStepOutputUpsertOne) ClearContent() *TaskStepOutputUpsertOne {
	return u.Update(func(s *TaskStepOutputUpsert) {
		s.ClearContent()
	})
}

// Exec executes the query.
func (u *TaskStepOutputUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("entv1: missing options for TaskStepOutputCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *TaskStepOutputUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *TaskStepOutputUpsertOne) ID(ctx context.Context) (id uint64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *TaskStepOutputUpsertOne) IDX(ctx context.Context) uint64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// TaskStepOutputCreateBulk is the builder for creating many TaskStepOutput entities in bulk.
type TaskStepOutputCreateBulk struct {
	config
	err      error
	builders []*TaskStepOutputCreate
	conflict []sql.ConflictOption
}

// Save creates the TaskStepOutput entities in the database.
func (_c *TaskStepOutputCreateBulk) Save(ctx context.Context) ([]*TaskStepOutput, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*TaskStepOutput, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TaskStepOutputMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = uint64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *TaskStepOutputCreateBulk) SaveX(ctx context.Context) []*TaskStepOutput {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TaskStepOutputCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TaskStepOutputCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.TaskStepOutput.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.TaskStepOutputUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *TaskStepOutputCreateBulk) OnConflict(opts ...sql.ConflictOption) *TaskStepOutputUpsertBulk {
	_c.conflict = opts
	return &TaskStepOutputUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.TaskStepOutput.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *TaskStepOutputCreateBulk) OnConflictColumns(columns ...string) *TaskStepOutputUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &TaskStepOutputUpsertBulk{
		create: _c,
	}
}

// TaskStepOutputUpsertBulk is the builder for "upsert"-ing
// a bulk of TaskStepOutput nodes.
type TaskStepOutputUpsertBulk struct {
	create *TaskStepOutputCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.TaskStepOutput.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(taskstepoutput.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *TaskStepOutputUpsertBulk) UpdateNewValues() *TaskStepOutputUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(taskstepoutput.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(taskstepoutput.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.TaskStepOutput.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *TaskStepOutputUpsertBulk) Ignore() *TaskStepOutputUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *TaskStepOutputUpsertBulk) DoNothing() *TaskStepOutputUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the TaskStepOutputCreateBulk.OnConflict
// documentation for more info.
func (u *TaskStepOutputUpsertBulk) Update(set func(*TaskStepOutputUpsert)) *TaskStepOutputUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&TaskStepOutputUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *TaskStepOutputUpsertBulk) SetUpdatedAt(v time.Time) *TaskStepOutputUpsertBulk {
	return u.Update(func(s *TaskStepOutputUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *TaskStepOutputUpsertBulk) UpdateUpdatedAt() *TaskStepOutputUpsertBulk {
	return u.Update(func(s *TaskStepOutputUpsert) {
		s.UpdateUpdatedAt()
	})
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (u *TaskStepOutputUpsertBulk) ClearUpdatedAt() *TaskStepOutputUpsertBulk {
	return u.Update(func(s *TaskStepOutputUpsert) {
		s.ClearUpdatedAt()
	})
}

// SetCreatedBy sets the "created_by" field.
func (u *TaskStepOutputUpsertBulk) SetCreatedBy(v string) *TaskStepOutputUpsertBulk {
	return u.Update(func(s *TaskStepOutputUpsert) {
		s.SetCreatedBy(v)
	})
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *TaskStepOutputUpsertBulk) UpdateCreatedBy() *TaskStepOutputUpsertBulk {
	return u.Update(func(s *TaskStepOutputUpsert) {
		s.UpdateCreatedBy()
	})
}

// ClearCreatedBy clears the value of the "created_by" field.
func (u *TaskStepOutputUpsertBulk) ClearCreatedBy() *TaskStepOutputUpsertBulk {
	return u.Update(func(s *TaskStepOutputUpsert) {
		s.ClearCreatedBy()
	})
}

// SetUpdatedBy sets the "updated_by" field.
func (u *TaskStepOutputUpsertBulk) SetUpdatedBy(v string) *TaskStepOutputUpsertBulk {
	return u.Update(func(s *TaskStepOutputUpsert) {
		s.SetUpdatedBy(v)
	})
}

// UpdateUpdatedBy sets the "updated_by" field to the value that was provided on create.
func (u *TaskStepOutputUpsertBulk) UpdateUpdatedBy() *TaskStepOutputUpsertBulk {
	return u.Update(func(s *TaskStepOutputUpsert) {
		s.UpdateUpdatedBy()
	})
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (u *TaskStepOutputUpsertBulk) ClearUpdatedBy() *TaskStepOutputUpsertBulk {
	return u.Update(func(s *TaskStepOutputUpsert) {
		s.ClearUpdatedBy()
	})
}

// SetExecID sets the "exec_id" field.
func (u *TaskStepOutputUpsertBulk) SetExecID(v uint64) *TaskStepOutputUpsertBulk {
	return u.Update(func(s *TaskStepOutputUpsert) {
		s.SetExecID(v)
	})
}

// UpdateExecID sets the "exec_id" field to the value that was provided on create.
func (u *TaskStepOutputUpsertBulk) UpdateExecID() *TaskStepOutputUpsertBulk {
	return u.Update(func(s *TaskStepOutputUpsert) {
		s.UpdateExecID()
	})
}

// SetTimestamp sets the "timestamp" field.
func (u *TaskStepOutputUpsertBulk) SetTimestamp(v int64) *TaskStepOutputUpsertBulk {
	return u.Update(func(s *TaskStepOutputUpsert) {
		s.SetTimestamp(v)
	})
}

// AddTimestamp adds v to the "timestamp" field.
func (u *TaskStepOutputUpsertBulk) AddTimestamp(v int64) *TaskStepOutputUpsertBulk {
	return u.Update(func(s *TaskStepOutputUpsert) {
		s.AddTimestamp(v)
	})
}

// UpdateTimestamp sets the "timestamp" field to the value that was provided on create.
func (u *TaskStepOutputUpsertBulk) UpdateTimestamp() *TaskStepOutputUpsertBulk {
	return u.Update(func(s *TaskStepOutputUpsert) {
		s.UpdateTimestamp()
	})
}

// ClearTimestamp clears the value of the "timestamp" field.
func (u *TaskStepOutputUpsertBulk) ClearTimestamp() *TaskStepOutputUpsertBulk {
	return u.Update(func(s *TaskStepOutputUpsert) {
		s.ClearTimestamp()
	})
}

// SetContent sets the "content" field.
func (u *TaskStepOutputUpsertBulk) SetContent(v string) *TaskStepOutputUpsertBulk {
	return u.Update(func(s *TaskStepOutputUpsert) {
		s.SetContent(v)
	})
}

// UpdateContent sets the "content" field to the value that was provided on create.
func (u *TaskStepOutputUpsertBulk) UpdateContent() *TaskStepOutputUpsertBulk {
	return u.Update(func(s *TaskStepOutputUpsert) {
		s.UpdateContent()
	})
}

// ClearContent clears the value of the "content" field.
func (u *TaskStepOutputUpsertBulk) ClearContent() *TaskStepOutputUpsertBulk {
	return u.Update(func(s *TaskStepOutputUpsert) {
		s.ClearContent()
	})
}

// Exec executes the query.
func (u *TaskStepOutputUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("entv1: OnConflict was set for builder %d. Set it on the TaskStepOutputCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("entv1: missing options for TaskStepOutputCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *TaskStepOutputUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
