// Code generated by ent, DO NOT EDIT.

package entv1

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/busyster996/dagflow/internal/entv1/predicate"
	"github.com/busyster996/dagflow/internal/entv1/taskstepoutput"
)

// TaskStepOutputDelete is the builder for deleting a TaskStepOutput entity.
type TaskStepOutputDelete struct {
	config
	hooks    []Hook
	mutation *TaskStepOutputMutation
}

// Where appends a list predicates to the TaskStepOutputDelete builder.
func (_d *TaskStepOutputDelete) Where(ps ...predicate.TaskStepOutput) *TaskStepOutputDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *TaskStepOutputDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *TaskStepOutputDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *TaskStepOutputDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(taskstepoutput.Table, sqlgraph.NewFieldSpec(taskstepoutput.FieldID, field.TypeUint64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// TaskStepOutputDeleteOne is the builder for deleting a single TaskStepOutput entity.
type TaskStepOutputDeleteOne struct {
	_d *TaskStepOutputDelete
}

// Where appends a list predicates to the TaskStepOutputDelete builder.
func (_d *TaskStepOutputDeleteOne) Where(ps ...predicate.TaskStepOutput) *TaskStepOutputDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *TaskStepOutputDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{taskstepoutput.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *TaskStepOutputDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
