// Code generated by ent, DO NOT EDIT.

package step

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/busyster996/dagflow/internal/entv1/schema"
)

const (
	// Label holds the string label denoting the step type in the database.
	Label = "step"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldCreatedBy holds the string denoting the created_by field in the database.
	FieldCreatedBy = "created_by"
	// FieldUpdatedBy holds the string denoting the updated_by field in the database.
	FieldUpdatedBy = "updated_by"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldDesc holds the string denoting the desc field in the database.
	FieldDesc = "desc"
	// FieldKind holds the string denoting the kind field in the database.
	FieldKind = "kind"
	// FieldContent holds the string denoting the content field in the database.
	FieldContent = "content"
	// FieldTimeout holds the string denoting the timeout field in the database.
	FieldTimeout = "timeout"
	// FieldAction holds the string denoting the action field in the database.
	FieldAction = "action"
	// FieldRule holds the string denoting the rule field in the database.
	FieldRule = "rule"
	// FieldRetryPolicy holds the string denoting the retry_policy field in the database.
	FieldRetryPolicy = "retry_policy"
	// FieldMetadata holds the string denoting the metadata field in the database.
	FieldMetadata = "metadata"
	// EdgeTasks holds the string denoting the tasks edge name in mutations.
	EdgeTasks = "tasks"
	// EdgeParams holds the string denoting the params edge name in mutations.
	EdgeParams = "params"
	// EdgeDependencies holds the string denoting the dependencies edge name in mutations.
	EdgeDependencies = "dependencies"
	// EdgeDependents holds the string denoting the dependents edge name in mutations.
	EdgeDependents = "dependents"
	// EdgeTaskSteps holds the string denoting the task_steps edge name in mutations.
	EdgeTaskSteps = "task_steps"
	// EdgeStepParams holds the string denoting the step_params edge name in mutations.
	EdgeStepParams = "step_params"
	// EdgeStepDepends holds the string denoting the step_depends edge name in mutations.
	EdgeStepDepends = "step_depends"
	// EdgeStepDependents holds the string denoting the step_dependents edge name in mutations.
	EdgeStepDependents = "step_dependents"
	// Table holds the table name of the step in the database.
	Table = "steps"
	// TasksTable is the table that holds the tasks relation/edge. The primary key declared below.
	TasksTable = "task_steps"
	// TasksInverseTable is the table name for the Task entity.
	// It exists in this package in order to avoid circular dependency with the "task" package.
	TasksInverseTable = "tasks"
	// ParamsTable is the table that holds the params relation/edge. The primary key declared below.
	ParamsTable = "step_params"
	// ParamsInverseTable is the table name for the Param entity.
	// It exists in this package in order to avoid circular dependency with the "param" package.
	ParamsInverseTable = "params"
	// DependenciesTable is the table that holds the dependencies relation/edge. The primary key declared below.
	DependenciesTable = "step_depends"
	// DependentsTable is the table that holds the dependents relation/edge. The primary key declared below.
	DependentsTable = "step_depends"
	// TaskStepsTable is the table that holds the task_steps relation/edge.
	TaskStepsTable = "task_steps"
	// TaskStepsInverseTable is the table name for the TaskStep entity.
	// It exists in this package in order to avoid circular dependency with the "taskstep" package.
	TaskStepsInverseTable = "task_steps"
	// TaskStepsColumn is the table column denoting the task_steps relation/edge.
	TaskStepsColumn = "step_id"
	// StepParamsTable is the table that holds the step_params relation/edge.
	StepParamsTable = "step_params"
	// StepParamsInverseTable is the table name for the StepParam entity.
	// It exists in this package in order to avoid circular dependency with the "stepparam" package.
	StepParamsInverseTable = "step_params"
	// StepParamsColumn is the table column denoting the step_params relation/edge.
	StepParamsColumn = "step_id"
	// StepDependsTable is the table that holds the step_depends relation/edge.
	StepDependsTable = "step_depends"
	// StepDependsInverseTable is the table name for the StepDepend entity.
	// It exists in this package in order to avoid circular dependency with the "stepdepend" package.
	StepDependsInverseTable = "step_depends"
	// StepDependsColumn is the table column denoting the step_depends relation/edge.
	StepDependsColumn = "step_id"
	// StepDependentsTable is the table that holds the step_dependents relation/edge.
	StepDependentsTable = "step_depends"
	// StepDependentsInverseTable is the table name for the StepDepend entity.
	// It exists in this package in order to avoid circular dependency with the "stepdepend" package.
	StepDependentsInverseTable = "step_depends"
	// StepDependentsColumn is the table column denoting the step_dependents relation/edge.
	StepDependentsColumn = "dependent_id"
)

// Columns holds all SQL columns for step fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldCreatedBy,
	FieldUpdatedBy,
	FieldName,
	FieldDesc,
	FieldKind,
	FieldContent,
	FieldTimeout,
	FieldAction,
	FieldRule,
	FieldRetryPolicy,
	FieldMetadata,
}

var (
	// TasksPrimaryKey and TasksColumn2 are the table columns denoting the
	// primary key for the tasks relation (M2M).
	TasksPrimaryKey = []string{"task_id", "step_id"}
	// ParamsPrimaryKey and ParamsColumn2 are the table columns denoting the
	// primary key for the params relation (M2M).
	ParamsPrimaryKey = []string{"step_id", "param_id"}
	// DependenciesPrimaryKey and DependenciesColumn2 are the table columns denoting the
	// primary key for the dependencies relation (M2M).
	DependenciesPrimaryKey = []string{"step_id", "dependent_id"}
	// DependentsPrimaryKey and DependentsColumn2 are the table columns denoting the
	// primary key for the dependents relation (M2M).
	DependentsPrimaryKey = []string{"step_id", "dependent_id"}
)

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// DefaultTimeout holds the default value on creation for the "timeout" field.
	DefaultTimeout int64
	// DefaultRetryPolicy holds the default value on creation for the "retry_policy" field.
	DefaultRetryPolicy *schema.RetryPolicy
)

// OrderOption defines the ordering options for the Step queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByCreatedBy orders the results by the created_by field.
func ByCreatedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedBy, opts...).ToFunc()
}

// ByUpdatedBy orders the results by the updated_by field.
func ByUpdatedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedBy, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByDesc orders the results by the desc field.
func ByDesc(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDesc, opts...).ToFunc()
}

// ByKind orders the results by the kind field.
func ByKind(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldKind, opts...).ToFunc()
}

// ByContent orders the results by the content field.
func ByContent(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldContent, opts...).ToFunc()
}

// ByTimeout orders the results by the timeout field.
func ByTimeout(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTimeout, opts...).ToFunc()
}

// ByAction orders the results by the action field.
func ByAction(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAction, opts...).ToFunc()
}

// ByRule orders the results by the rule field.
func ByRule(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRule, opts...).ToFunc()
}

// ByTasksCount orders the results by tasks count.
func ByTasksCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newTasksStep(), opts...)
	}
}

// ByTasks orders the results by tasks terms.
func ByTasks(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newTasksStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByParamsCount orders the results by params count.
func ByParamsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newParamsStep(), opts...)
	}
}

// ByParams orders the results by params terms.
func ByParams(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newParamsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByDependenciesCount orders the results by dependencies count.
func ByDependenciesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newDependenciesStep(), opts...)
	}
}

// ByDependencies orders the results by dependencies terms.
func ByDependencies(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newDependenciesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByDependentsCount orders the results by dependents count.
func ByDependentsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newDependentsStep(), opts...)
	}
}

// ByDependents orders the results by dependents terms.
func ByDependents(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newDependentsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByTaskStepsCount orders the results by task_steps count.
func ByTaskStepsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newTaskStepsStep(), opts...)
	}
}

// ByTaskSteps orders the results by task_steps terms.
func ByTaskSteps(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newTaskStepsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByStepParamsCount orders the results by step_params count.
func ByStepParamsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newStepParamsStep(), opts...)
	}
}

// ByStepParams orders the results by step_params terms.
func ByStepParams(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newStepParamsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByStepDependsCount orders the results by step_depends count.
func ByStepDependsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newStepDependsStep(), opts...)
	}
}

// ByStepDepends orders the results by step_depends terms.
func ByStepDepends(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newStepDependsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByStepDependentsCount orders the results by step_dependents count.
func ByStepDependentsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newStepDependentsStep(), opts...)
	}
}

// ByStepDependents orders the results by step_dependents terms.
func ByStepDependents(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newStepDependentsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newTasksStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(TasksInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2M, true, TasksTable, TasksPrimaryKey...),
	)
}
func newParamsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ParamsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2M, false, ParamsTable, ParamsPrimaryKey...),
	)
}
func newDependenciesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(Table, FieldID),
		sqlgraph.Edge(sqlgraph.M2M, false, DependenciesTable, DependenciesPrimaryKey...),
	)
}
func newDependentsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(Table, FieldID),
		sqlgraph.Edge(sqlgraph.M2M, true, DependentsTable, DependentsPrimaryKey...),
	)
}
func newTaskStepsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(TaskStepsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, true, TaskStepsTable, TaskStepsColumn),
	)
}
func newStepParamsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(StepParamsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, true, StepParamsTable, StepParamsColumn),
	)
}
func newStepDependsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(StepDependsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, true, StepDependsTable, StepDependsColumn),
	)
}
func newStepDependentsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(StepDependentsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, true, StepDependentsTable, StepDependentsColumn),
	)
}
